### ISSUE TITLE
The ":" in foo:bar packages names is illegal on windows

### ISSUE THREAD

**Issue by vjau** [meteor/windows-preview#1]
I know this is a known issue, but afaik this is not resolved in 0.0.8 preview, so i write it there so it can be tracked.
The ":" in packages name is illegal on windows, and cause a failure when trying to clone an existing repository.

**Comment by shirk3y** [comment]
Maybe File Name Character Translation could help? http://support.microsoft.com/kb/289627

**Comment by stubailo** [comment]
Try the new preview release: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

It's an almost complete rewrite and doesn't appear to have this issue anymore.

**Comment by LuisHerranz** [comment]
It looks like people is still having this issue. I've just received a PR to make my package work on Windows:
https://github.com/meteorflux/dispatcher/pull/1

**Comment by dandv** [comment]
@LuisHerranz: I think the PR you've received is independent of Meteor, and rather a git problem. Any repo with files that have characters disallowed by Windows will create problems.

My suggestion [earlier](https://github.com/meteor/windows-preview/issues/1#issuecomment-64155171) was to educate developers to avoid `:` and non-cross-filesystem characters in filenames. To that end, `meteor create --package foo:bar` now creates `bar-tests.js`, which is good change. The meteor repo doesn't contain any files with ':'.

I see you've created the repo on March 9... maybe meteor-tool still used to output `foo:bar-tests.js` files back then?

**Comment by LuisHerranz** [comment]
Ok, it's working fine. I created that repo with Meteor 1.0.3.2 and `meteor create --package foo:bar` creates `foo:bar` but updated the project to Meteor 1.1.0.2 and now it creates only `bar`.

Everything ok then :+1:
