### ISSUE TITLE
Uninstall Meteor says it's installing, not uninstalling

### ISSUE THREAD

**Issue by pdavidow** [meteor/windows-preview#102]
Uninstall from the ControlPanel on Windows7 64bit.
And when it's all done it says: 'Meteor is now installed on your computer.'

**Comment by PureConstant** [comment]
Same thing here.
Windows Server 2008 R2 64bit

**Comment by stubailo** [comment]
Confirmed! We will fix this for the final release.

**Comment by Slava** [comment]
Fixed in 1.1 RC0
