### ISSUE TITLE
Meteor is still in PATH variable after uninstall

### ISSUE THREAD

**Issue by pdavidow** [meteor/windows-preview#103]
There were actually three of these in my PATH after Meteor uninstall (from ControlPanel):
C:\Users\{user}\AppData\Local\.meteor
(perhaps one from each install)

Windows7, 64bit

**Comment by zhongdeliu** [comment]
It indeed stays there after uninstall

**Comment by Slava** [comment]
Looks like a thing to fix in the installer. @stubailo

**Comment by stubailo** [comment]
Seems to me like this isn't a release blocker, but something we should fix in the future.
