### ISSUE TITLE
Error: "Path too long" when trying to build package

### ISSUE THREAD

**Issue by fredrikekelund** [meteor/windows-preview#105]
I tried to publish fredrik:node-xmpp for Windows with `meteor admin get-machine os.windows.x86_32 --release WINDOWS-PREVIEW@0.3.0` and `meteor publish-for-arch fredrik:node-xmpp@1.0.2`, which worked fine until the final stages where Meteor was bundling the built package and protested that it encountered a too long path:

```
C:\Windows\System32\config\systemprofile\AppData\Local\.meteor\packages\meteor-t
ool\1.1.1-win.7\mt-os.windows.x86_32\tools\files.js:748                 
        throw new Error("Path too long: " + entry.path + " is " +               
              ^                                                                 
Error: Path too long: C:\Windows\TEMP\bp-1fxvbgv\fredrik_node-xmpp-1.0.2\npm\nod
e_modules\node-xmpp\node_modules\browserify\node_modules\insert-module-globals\n
ode_modules\browserify\node_modules\insert-module-globals\node_modules\lexical-s
cope\node_modules\astw\node_modules\.bin\esparse is 266 characters.             
    at FileReader.fstream.Reader.filter (C:\Windows\System32\config\systemprofil
e\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\to
ols\files.js:748:15)                                                            
    at statCb (C:\Windows\System32\config\systemprofile\AppData\Local\.meteor\pa
ckages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\
fstream\lib\reader.js:193:22)                                                   
    at Object.oncomplete (evalmachine.<anonymous>:108:15)                       
```

**Comment by fourseven** [comment]
I have this too now:

```
   Bundling build for fourseven:scss         /
C:\Windows\System32\config\systemprofile\AppData\Local\.meteor\packages\meteor-t
ool\1.1.1-win.7\mt-os.windows.x86_32\tools\files.js:748
        throw new Error("Path too long: " + entry.path + " is " +
              ^
Error: Path too long: C:\Windows\TEMP\bp-19dnyjt\fourseven_scss-2.0.1_4\plugin.c
ompileScss.os.windows.x86_32\npm\compileScss\node_modules\node-sass\node_modules
\sass-graph\node_modules\glob\node_modules\minimatch\node_modules\brace-expansio
n\node_modules\balanced-match\test\balanced.js is 264 characters.
    at FileReader.fstream.Reader.filter (C:\Windows\System32\config\systemprofil
e\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\to
ols\files.js:748:15)
    at statCb (C:\Windows\System32\config\systemprofile\AppData\Local\.meteor\pa
ckages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\
fstream\lib\reader.js:193:22)
    at Object.oncomplete (evalmachine.<anonymous>:108:15)
```

**Comment by stubailo** [comment]
@fredrikekelund: try this workaround: https://github.com/meteor/meteor/wiki/Publishing-a-package-with-binary-dependencies-for-the-Windows-preview#dealing-with-long-path-lengths

@fourseven: the above workaround doesn't work for build plugins. I'm going to try to implement it as a short term solution in the next few days.

In the long term, we hope to be able to lift the path length restriction entirely.

**Comment by avital** [comment]
Maybe we should instead find a way to use the "\\?\" prefix which supposedly lets you use long file paths.

**Comment by stubailo** [comment]
@avital I agree, that would be optimal.

**Comment by stubailo** [comment]
@fredrikekelund @fourseven We just fixed the root cause of the issue, and there is no longer a path limitation and you don't need to use Npm.strip anymore. Simply publish your package with `WINDOWS-PREVIEW@0.4.1`. I tested republishing `fourseven:scss` and `fredrik:node-xmpp` under different names just now with this release, and it seemed to work fine.

One caveat: for node-xmpp, I had to change the npm dependency to 1.0.0-alpha1 because npm couldn't find 1.0.0-alpha2.

**If you have time, please test this out for yourself** - we would like to send out an email to all binary package authors to ask them to publish their packages for Windows soon.

**Comment by fredrikekelund** [comment]
Yeah I know, `node-xmpp@1.0.0-alpha2` didn't seem to exist for Windows or something. Anyway, I tried building `fredrik:node-xmpp` for Windows with `WINDOWS-PREVIEW@0.4.1` and **it worked**! :clap: Thanks for your hard work on this!

Only issue I had was that my Ubuntu terminal (running Windows at work, Ubuntu on personal laptop) didn't clear properly when I entered the Windows SSH session, so the Windows terminal would overlay my previous terminal output and cause everything to look weird.

**Comment by fourseven** [comment]
Just downloading `WINDOWS-PREVIEW@0.4.1` myself now, do I need to publish a new version or can I just publish-for-arch again?

**Comment by fredrikekelund** [comment]
Try doing a publish-for-arch with the current version. I'm not sure, but it seems to me it should work if there is no previously published bundle for the current platform

**Comment by daveit** [comment]
Sorry for dumb Q, but how do you download WINDOWS-PREVIEW@0.4.1 ?

**Comment by fourseven** [comment]
@daveit `meteor --release WINDOWS-PREVIEW@0.4.1` will force that version

**Comment by fredrikekelund** [comment]
And `meteor admin get-machine os.windows.x86_32 --release WINDOWS-PREVIEW@0.4.1` for publishing. 0.4.1 doesn't seem to work yet for running a normal app for me, though, some unsatisfied dependencies

**Comment by daveit** [comment]
Cheers fourseven - appreciate that, Dave

**Comment by fourseven** [comment]
`fourseven:scss@2.0.1_5` is published for windows. It didn't ask me for login details when I exited the admin session on windows and re-connected (to then successfully `publish-for-arch`) - should I raise that as a separate issue??

**Comment by Slava** [comment]
@fourseven the machines are reused for the same user when accessed within an hour

**Comment by fourseven** [comment]
Ah okay thanks @Slava - got a little worried when it did that, which is different to the *nix boxes (I believe). Appreciate the work getting the windows port operational everyone!

**Comment by stubailo** [comment]
@fourseven thanks so much for publishing your package!

**Comment by Chos89** [comment]
I had to remove this package to deploy because I was getting the same error
https://atmospherejs.com/dfischer/prerenderio

**Comment by stubailo** [comment]
@Chos89 in the next release, this problem should be fixed and also there should be no version number issues.

**Comment by angela323** [comment]
Have you tried using Long Path Tool Program for this? I use if for several times now and it did help me. You should try it. It is very good program.
