### ISSUE TITLE
Error during meteor add iron:router

### ISSUE THREAD

**Issue by skeetmtp** [meteor/windows-preview#109]
Repro step : 
meteor create foobar
cd foobar
meteor add iron:router 

=> TypeError: Cannot convert null to object
with a huge callstack

Some other packages can be added and work fine, but not iron:router

**Comment by Slava** [comment]
What is the huge stack trace?

**Comment by skeetmtp** [comment]
For information I tried on a new windows 7 fresh install on a VM and it worked ...
But on my machine it does'nt.
I previously used the 0.1.7 version of meteor for windows. And today I download & run the new installer.


Here is the log : 

`
c:\temp>meteor create foobar
foobar: created.

To run your new app:
  cd foobar
  meteor
c:\temp>cd foobar

c:\temp\foobar>meteor add iron:router

C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\m
t-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:278
                                                throw(ex);
                                                      ^
TypeError: Cannot convert null to object
    at Object.Future.wait (C:\Users\LECOCQ.HOME\AppData\Local\.meteor\package
s\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fiber
s\future.js:398:15)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:556:31
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\LECOCQ.HOME\AppData\Local\.meteor\
packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\lib\node_module
s\underscore\underscore.js:79:11)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:554:9
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at enterJob (C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-t
ool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at Object.forkJoin (C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\m
eteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:531:3)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\Users\LECOCQ.
HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86
_32\tools\tropohouse.js:553:18)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\project-context.js:641:25
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at Object.enterJob (C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\m
eteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\project-context.js:640:20
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\catalog.js:96:5
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at Object.capture (C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\me
teor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\Users\LECOCQ.HOME\A
ppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools
\catalog.js:95:31)
    at ProjectContext._.extend._downloadMissingPackages (C:\Users\LECOCQ.HOME
\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\too
ls\project-context.js:639:13)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\project-context.js:228:35
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at Object.enterJob (C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\m
eteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at ProjectContext._.extend._completeStagesThrough (C:\Users\LECOCQ.HOME\A
ppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools
\project-context.js:218:18)
    at ProjectContext._.extend.saveChangedMetadata (C:\Users\LECOCQ.HOME\AppD
ata\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\pr
oject-context.js:206:10)
    at ProjectContext._.extend.prepareProjectForBuild (C:\Users\LECOCQ.HOME\A
ppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools
\project-context.js:211:10)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\commands-packages.js:1852:20
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at Object.capture (C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\me
teor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at Command.main.registerCommand.name [as func] (C:\Users\LECOCQ.HOME\AppD
ata\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\co
mmands-packages.js:1851:27)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\main.js:1345:23
    - - - - -
    at hasOwnProperty (native)
    at Function._.has (C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\me
teor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscor
e\underscore.js:1074:27)
    at [object Object]._.extend._loadUnibuildsFromPath (C:\Users\LECOCQ.HOME\
AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tool
s\isopack.js:622:11)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\tropohouse.js:469:19
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\LECOCQ.HOME\AppData\Local\.meteor\
packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\lib\node_module
s\underscore\underscore.js:79:11)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\tropohouse.js:468:11
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at Object.enterJob (C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\m
eteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at Object.download (C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\m
eteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\tropohouse.js:410:20)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\tropohouse.js:557:18
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:537:23
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\LECOCQ.HOME\AppData\Local
\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpe
rs.js:115:14)
    at enterJob (C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-t
ool\1.1.1-win.7\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:536:24
    at runWithEnvironment (C:\Users\LECOCQ.HOME\AppData\Local\.meteor\package
s\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:139:21)
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\fiber-helpers.js:146:14
    at C:\Users\LECOCQ.HOME\AppData\Local\.meteor\packages\meteor-tool\1.1.1-
win.7\mt-os.windows.x86_32\tools\buildmessage.js:549:11
c:\temp\foobar>
`

**Comment by Slava** [comment]
@skeetmtp did you mean to post your reply in #111 here?

**Comment by skeetmtp** [comment]
I tried Uninstall and install it again and now it works !
May be there was some old file remaining from the old version.
