### ISSUE TITLE
Unable to add any SASS/SCSS package

### ISSUE THREAD

**Issue by michaelbreyes** [meteor/windows-preview#110]
I've tried all the following:

meteor add particle4dev:sass
meteor add fourseven:scss
meteor add arsnebula:sass

All of them fail saying
error: No compatible build found

**Comment by Slava** [comment]
Package authors will have to republish their packages with binary dependencies (like sasslib) for Windows. You would need to contact @fourseven.

**Comment by fourseven** [comment]
Hi @michaelbreyes - see #105, that's what is blocking me from building the windows package at the moment.

(thanks for the ping, @Slava)

**Comment by stubailo** [comment]
@michaelbreyes, `fourseven:scss` should work now! Thanks to @fourseven for republishing.
