### ISSUE TITLE
Windows Preview

### ISSUE THREAD

**Issue by jeffschmitz** [meteor/windows-preview#111]
I just installed the new 1.1 Window Preview and when I start it in an existing project I get "Could not find file 'C:\users\...\.meteor\tools\latest' and meteor dies.  Here's the stack trace...

Unexpected exception: System.IO.FileNotFoundException: Could not find file 'C:\U
sers\si454a\AppData\Local\.meteor\tools\latest'.
File name: 'C:\Users\si454a\AppData\Local\.meteor\tools\latest'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, I
nt32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions o
ptions, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean
bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detec
tEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at LaunchMeteor.Program.Main(String[] args)

**Comment by Slava** [comment]
Looks like its trying to run the very old binary from unofficial community port. Can you make sure to delete it and try again?

**Comment by skeetmtp** [comment]
Ok while reading #111 I found the solution.
Uninstall and install it again. may be there was some old file remaining from the old version.

**Comment by jeffschmitz** [comment]
I did try that, but it doesn't look like the new installer is actually doing anything.  It immediately returns and tells me Meteor has been installed, but I don't know where, and meteor from the command line says unknown command.

**Comment by Slava** [comment]
@jeffschmitz are you on Windows 8.1 by any chance?

**Comment by jeffschmitz** [comment]
no, windows 7.

**Comment by Slava** [comment]
@jeffschmitz what is the value of your %PATH% after the installation?

**Comment by jeffschmitz** [comment]
C:\Users\si454a\AppData\Local\.meteor

But no such folder gets created by the installer.

**Comment by jeffschmitz** [comment]
OK, I had to uninstall the new Meteor program using Windows uninstall and then run the installer again.  I guess the new one had gotten partially installed before, so subsequent re-installs after removing the old Meteor didn't think it had to install it again.
