### ISSUE TITLE
Converting existing meteor project to run in Windows gets "error: No compatible build found"

### ISSUE THREAD

**Issue by Lean41** [meteor/windows-preview#113]
Pulled an existing repo that runs and tried it on Windows 8.1
got:
---
C:\Users\Bill\Desktop\lean biz\meteor\tps-demo>meteor run
This project uses METEOR@1.0.3.1, which isn't available on Windows. To
work with this app on all supported platforms, use
meteor update --release WINDOWS-PREVIEW@0.3.0 to pin this app to the
newest Windows-compatible release.
C:\Users\Bill\Desktop\lean biz\meteor\tps-demo>meteor update --release WINDOWS-PREVIEW@0.3.0
=> Errors while initializing project:

While checking for fourseven:scss@1.0.0:
error: No compatible build found

**Comment by marcelpanse** [comment]
I have the same issue with:
While checking for fourseven:scss@1.0.0:
error: No compatible build found

While checking for meteorhacks:kadira-binary-deps@1.3.1:
error: No compatible build found

**Comment by fourseven** [comment]
You'll have to raise issues with those package maintainers, and FYI `fourseven:scss@2.0.1_5` works on windows now :smile:

**Comment by stubailo** [comment]
@Slava There's actually a new problem here - the constraint solver doesn't take into account whether there exist builds for the current platform, so even if people republish their packages they might get this error.

**Comment by Slava** [comment]
And I don't think constraint solver should care about this. Slowly, all the packages will bump their dependencies to the more recent versions. Also, people can enforce the versions with builds by adding top-level constraints to their apps.

**Comment by stubailo** [comment]
@Lean41 the newest version of fourseven:scss works on Windows now. We filed this issue on Kadira: https://github.com/meteorhacks/kadira-binary-deps/issues/2

It's now up to @arunoda to republish his package for Windows.

**Comment by arunoda** [comment]
@marcelpanse Check now. I just published it for window.
Anyway, try to update kadira as well.

**Comment by marcelpanse** [comment]
Nice! :-)
