### ISSUE TITLE
Installation crashed - now cannot uninstall / reinstall / anything

### ISSUE THREAD

**Issue by ganySA** [meteor/windows-preview#114]
Hi

Similar problem to #102 meteor crashed during installation (ADSL dropped) and it didnt resume.

Now i cannot run or uninstall et.

Any ways to remove it / reinstall?

Update: 

I managed to run:
InstallMeteor.exe /reinstall then
InstallMeteor.exe /uninstall and then finally
InstallMeteor.exe /reinstall

And something kicked off the download again.

**Comment by stubailo** [comment]
Crazy. Looks like we should better handle the error of being disconnected.

**Comment by ganySA** [comment]
I think probably a re-install option somewhere would be best....

**Comment by stubailo** [comment]
@ganySA This should be less of the problem with the new installer, which doesn't do any downloading for you. We should document how to reinstall.
