### ISSUE TITLE
Installer login fails on Windows 7

### ISSUE THREAD

**Issue by keithn** [meteor/windows-preview#115]
![image](https://cloud.githubusercontent.com/assets/86080/6697276/63503fa0-cd54-11e4-9432-2d38cbd47967.png)

**Comment by stubailo** [comment]
Which version of Windows are you using? Did logging in with the correct password work correctly?

**Comment by keithn** [comment]
windows 7,  I ended up skipping, I couldn't remember what my password was.

**Comment by stubailo** [comment]
Ah - I suspect you would have gotten the same popup if you put in the correct password. I think it's a result of not being able to connect to the server for some reason. We should have better error handling here.

**Comment by Thomas-Lohrum** [comment]
I get the same error dialog with no error text. My password is correct which i verified online at meteor.com. I am also on Windows 7.

**Comment by stubailo** [comment]
@keithn @Thomas-Lohrum does calling `meteor login` from the command prompt work for you?

**Comment by Thomas-Lohrum** [comment]
Yes. I see the message: Logged in as [user]. Thanks for being a Meteor developer!

Please note, when i call meteor logout i get the following warning:
"couldn't confirm logout with www.meteor.com
Logged out."

**Comment by keithn** [comment]
yeah, I can sign in also using the command line.  Also had the same problem with logging out

**Comment by Thomas-Lohrum** [comment]
Since their is no error text, maybe the process fails during install because of the problem with logging out?
