### ISSUE TITLE
freezing during install when internet was lost

### ISSUE THREAD

**Issue by etshei** [meteor/windows-preview#118]
Hi,
I had a problem during installation (meteor download 8%) on a windows 7.
Internet was lost and the install didn't respond even after the internet was back (the cancel button didn't do anything) and i was forced to kill it using the task manager.
I can't reinstall it after because it thinks that the install is still going.
thanks for thinking about windows people :+1:

**Comment by ganySA** [comment]
Similar to  #102 and #112 

Reboot the PC and follow instructions as per #102 and you can get around this, but yes its a problem.

**Comment by stubailo** [comment]
Duplicate of #114
