### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by ewaldhorn** [meteor/windows-preview#119]
Interesting error on Windows 8.1 x64 with Node 0.12.0 x64 installed.

Could this be a 32bit vs 64bit issue?

module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\Users\Ewald\node_modules\sqlite3\lib\binding\node-v11-win32-ia32\node_sqlite3.no
de'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Ewald\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Ewald\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows
.x86_32\tools\catalog-remote.js:10:15)

**Comment by Slava** [comment]
It is weird that it tries to find a file in your home directory. Do you have a directory called "node_modules" in your home? If so, can you delete it and see if it helps?

**Comment by stubailo** [comment]
Yeah, this seems like one of those NODE_PATH issues

**Comment by ewaldhorn** [comment]
Hi.

Sure, I can remove that folder and try again.  Funny, it's a node module I
am actively using at the moment though.

I'll report in once I've done this.

Kind regards,
Ewald

**Comment by ewaldhorn** [comment]
Hi.

So I removed the offending package, and now Meteor is happy :)

Windows... Sigh.

Kind regards,
Ewald

**Comment by stubailo** [comment]
It's best to avoid keeping `node_modules` in your home directory, because node looks all of the way up from your current directory to find modules to load. It might cause unexpected modules to be loaded, like in this case.

**Comment by ewaldhorn** [comment]
Hi.

I hear you, it is interesting though that I had actively working NodeJS
applications that are now broken.

For now, I will restore the folder and rather try Meteor again later.

Kind regards,
Ewald

**Comment by stubailo** [comment]
You should install the `node_modules` directly in your application, rather than keeping them in your home directory. That way, your node apps will still work, but they will not interfere with other node apps on the same system (such as Meteor)

**Comment by ewaldhorn** [comment]
Hi.

It has always been like this on the machine. Windows has an AppData folder
for each user and NPM throws a whole bunch of stuff in there by default
from what I can tell.

My node_modules folder is over 1gb big!! So it seems that it places some
things there by default.

Interesting, I've never delved into this before, I will spend some time on
it again after my current project is complete. Then I will try to move
things around and run with the Meteor tutorial again.

Kind regards,
Ewald
