### ISSUE TITLE
Windows installer can't download Meteor - need to specify http proxy

### ISSUE THREAD

**Issue by headegg** [meteor/windows-preview#120]
I'm trying to install using the 0.3.0 InstallMeteor.exe but it fails to download Meteor, eventually saying "0x80070643 - Fatal error during installation". Is there a way to configure the installer to use my corporate http proxy? Or is there a way that I can manually download the required binaries and have the installer use them? Thanks, Alex.

**Comment by PureConstant** [comment]
+1 for this. I cannot install it behind my corporate proxy too.

**Comment by m2web** [comment]
Same here when at work.

**Comment by Slava** [comment]
I described a workaround here, please see if it helps: https://github.com/meteor/windows-preview/issues/123#issuecomment-83072214

**Comment by m2web** [comment]
Slava, The install is correct now using the tar ball, but I am getting the following when attempting to create a project:
```
C:\Users\mmcfadde\meteor>meteor create --example todos
=> Errors while creating your project

While downloading iron:core@0.3.4...:
error: CERT_UNTRUSTED

While downloading iron:dynamic-template@0.4.1...:
error: CERT_UNTRUSTED

While downloading iron:layout@0.4.1...:
error: CERT_UNTRUSTED

While downloading iron:router@0.9.4...:
error: CERT_UNTRUSTED

While downloading npm-bcrypt@0.7.8_2...:
error: CERT_UNTRUSTED

C:\Users\mmcfadde\meteor>

**Comment by Slava** [comment]
I guess because the meteor tool also doesn't know how to run behind your
proxy. How does software on Windows discover proxies?

**Comment by yeputons** [comment]
@Slava it either uses its own proxy configuration (like Firefox does) or uses system-wide proxy settings (usually they're imported from Internel Explorer; Chrome does this).

**Comment by m2web** [comment]
https://technet.microsoft.com/en-us/library/cc713344.aspx

**Comment by Slava** [comment]
The new installer contains the full tarball and doesn't download anything extra from the internet. Please try the latest RC: http://s3.amazonaws.com/meteor-windows/installers/1.1-rc.0/InstallMeteor.exe

**Comment by headegg** [comment]
Excellent! Thanks very much. Alll working now.

**Comment by m2web** [comment]
FYI, with the new installer I was able to get the todos app installed behind the firewall only after copying the iron_core, iron_dynamic_template, iron_layout, iron_router, iron_url, and npm_bcrypt package from my home system. Other than that, all works well.
