### ISSUE TITLE
spacebar tag prints as it is while running the application

### ISSUE THREAD

**Issue by CharLiPPS** [meteor/windows-preview#121]
Hi All,
I have copied the files from ubantu for leaderboard customized example but the spacebars handler prints as it is. Am I missing something here... I installed windows meteor exe without any issues.

In leaderboard,
- Removed insecure
- Removed autopublish
- Added Iron router ( there is no reaction in windows but it worked in ubantu)
- Added twbs bootstrap.

I have tried to call template inside the <head> since iron router is not having any effect but it prints as like below

{{ > Header }}
{{ > leaderboard> }}

In my understanding, the tag value should be replaced with actual template while compiling and running.

it works fine in Ubantu but not in windows.

Thanks.
Siva A

**Comment by Slava** [comment]
Hi,

Do you have any way to demonstrate your error in a form of a simple app that we can run on our computers?

Also, post an error you are getting.

**Comment by CharLiPPS** [comment]
Hi,

I had created more html, js and css files but i kept it in 3 generated files today to debug the problem. Now, I am getting blank page if I add the below code

Router.route('/', function () {
  this.render('Home');
});

otherwise, I get Iron router error in page if I am removing the above code from js.

Router.route('/', function () {
  this.render('Home', {
    data: function () { return Items.findOne({_id: this.params._id}); }
  });
});
Am I missing anything here?

**Comment by stubailo** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by CharLiPPS** [comment]
I am stupid... missed accounts-ui and accounts-password package ...

It would be better to show some warning message ( if loginButton added in coding but package is missed) rather than showing blank screen in run time.
.

**Comment by stubailo** [comment]
It would have printed an error in your developer console.
