### ISSUE TITLE
Option to set InstallDirectory

### ISSUE THREAD

**Issue by zhongdeliu** [meteor/windows-preview#122]
An Option to set the Install Directory would be great!

**Comment by Slava** [comment]
We had it initially but then decided not to have it in the installer. 

- it is simpler for the installer, Google Chrome and Dropbox always install to the same location per user and don't give an option to choose a folder
- it is another code-path to test
- on linux and mac, we don't give an option to choose the install location either

A workaround is to manually move the installation and then add its path to the PATH env variable.

**Comment by tomByrer** [comment]
> on linux and mac, we don't give an option to choose the install location either

IIRC, it is much easier to change /home or /bin or /usr to a different drive then Windows' \Users.

**Comment by Slava** [comment]
@tomByrer yes, but on Windows, you can as well move the folder with your meteor installation `.meteor` to any place and just call the meteor.bat from there. On linux/mac it is a lot trickier.

**Comment by Sabadios** [comment]
no, seriously this is dumb. and false. Chrome provides an admin installer. how can you compare apples & oranges?! dropbox is a dumb tool meant to serve as user dedicated cloud depot. meteor is development & deployment environment and must have customizable install options and the path is most likely the most important of all. this workaround just gives the feeling of a childish level of maturity and will not help adoption of the platform.

**Comment by stubailo** [comment]
@Sabadios what's the use case for changing the location? Where would you put it?

**Comment by Sabadios** [comment]
I'll leave it at users choice, isn't natural?!

**Comment by stubailo** [comment]
Well, there are benefits to everyone having a standard location as well. I feel like you haven't really given a good reason other than "childish level of maturity".

**Comment by tomByrer** [comment]
Use cases of different install folders:
I put work & fun programs on a different drive than my C:\Windows partition, so when it craps out, I can flip to my backup drive & still use what I need.  Also helpful when switching to different OS versions (eg Win7, 8, 10) for testing an application.

Also, if someone has little OS drive space (eg cheap laptop) & is using external drive for programs, they'll need to direct the install folder.

**Comment by Sabadios** [comment]
Thanks Tom for listing some - I find simple, naturally wide used, scenarios  - seriously, I find this argumentation so useless that it baffles me. Yeah - it is normal to have a standard installation as much as it is normal to have the opportunity to chose - haven't use any enterprise or web stack besides MS .NET in the last 15 years which didn't allowed this ...
