### ISSUE TITLE
Feature request: stand-alone offline installer

### ISSUE THREAD

**Issue by yeputons** [meteor/windows-preview#123]
While online installation have some benefits (such as getting the most recent version), it is unacceptable in some cases (and corporate proxy #120 is one of the least evils).

Real use case: if I want to give a hands-on experience in the summer camp, all attendees need Internet access in order to install Meteor, and generally the only Internet access available is through EDGE - it's both slow and expensive for everyone. So, while I can easily download Java Development Kit and other stuff in advance and distribute it among students, I'm unable to do so with Meteor, which is no good.

Another use case: mass installation. If I have 20 computers, I don't want to download Meteor 20 times instead of just one (sometimes Internet access is not very good, too)

**Comment by Slava** [comment]
We are considering changing the way we build installers. Ideally, like you said above, the distribution doesn't require the internet connection to function well.

We haven't done any research on how to compile our bootstrap tarballs into the installer exe and we don't know how much it would take us.

Here is a workaround though:

You can download the bootstrap tarball yourself, for example: METEOR-[PREVIEW@0.3.0](https://s3.amazonaws.com/com.meteor.static/packages-bootstrap/WINDOWS-PREVIEW@0.3.0/meteor-bootstrap-os.windows.x86_32.tar.gz).

Then unpack its contents (a `.meteor` folder) and put it somewhere, where you wish to have your installation. Then put its path to your PATH env variable.

**Comment by stubailo** [comment]
This could be as simple as adding a command line option to the installer to use a pre-downloaded tarball. We should see how hard that would be.

**Comment by avital** [comment]
Hi @yeputons,

The current installer comes fully bundled so there is no additional download step, which should solve your problem.

But we're consider changing it back to a small installer that downloads the latest version of Meteor and installs it. That means if you have an old installer you'll still get the latest version. The big benefit for us is that is simplifies our release process.

I'd like to address your concern about installing Meteor on several computers with a slow internet connection. How about the following: Install Meteor on one machine, and then copy the contents of `C:\Users\<Username>\AppData\Local\.meteor` to the other machines directly and add that directory to the PATH on those machine.

Does that sound reasonable to you? It's worth pointing out that the Linux and Mac installers work the same way at the moment, and the process I just described is what you'd do for those OSs as well if you'd want to download once and install on multiple machines.

**Comment by avital** [comment]
Another benefit of the approach I outlined for your summer camp is that if you want your students to use certain packages you can make sure they're downloaded before copying the contents of the `.meteor` directory, whereas if they would all install Meteor with the installer they'd still have to go through their slow internet connection every time they add a package.

**Comment by yeputons** [comment]
@avital Sounds reasonable. I'd use that if I'm completely sure that these actions and only them are performed by standard installer. It's not always the case on Windows: most programs like to silently install some additional software, register DLLs, modify user registry, etc, and simple copying usually does not work smoothly.

Something like 'Stand-alone installation'/'Offline installation' official guide with links to the most recent tarball would be good. Just a description "how do I behave like an installer with no internet"

**Comment by stubailo** [comment]
Actually we could solve this by just shipping a "portable version" of Meteor which is just a .zip file with all of the stuff that the installer unpacks (right now, it is in .tar.gz format, which I think is pretty inconvenient on Windows)

**Comment by Slava** [comment]
@stubailo there is no "portable" versions per se, Meteor relies on the internet connection to download missing packages from atmosphere.

**Comment by stubailo** [comment]
That's true. I guess maybe it's not worth addressing a super niche case where you have internet, but it's very slow - fast enough to download packages but too slow to download the install bundle.

**Comment by yeputons** [comment]
@stubailo Actually, this is more like 'no Internet' situation. I.e. I, as a teacher, has some Internet to download everything I need, but I we do not give it to students, because there are too many of them and not enough bandwidth.

So, yes, what I need is portable version or stand-alone installer plus packages, @avital's suggestion is very good, if the installer does absolutely nothing but unpacking archive and adding Meteor to PATH.

**Comment by avital** [comment]
Yeah we should just document how to install Meteor on a machine, add whatever packages and releases you'll want and make an archive out them that you can copy to any computer.

And this isn't unique to Windows.

**Comment by avital** [comment]
(That task I just described is on my list for this focus period)

**Comment by avital** [comment]
Here are the instructions for installing Meteor manually without the installer: https://github.com/meteor/meteor/wiki/Meteor-on-Windows:-Alternate-installation

Hope this helps!

**Comment by stubailo** [comment]
For completeness, there is now an issue about this on the main repo: https://github.com/meteor/meteor/issues/4589
