### ISSUE TITLE
Meteor installer for Windows works only "Executing with Administrator"

### ISSUE THREAD

**Issue by diegofaria** [meteor/windows-preview#125]
Windows 7.

**Simulate the error:**
1) Download the [Preview of Meteor on Windows](https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows).
2) Double-click on InstallMeteor.exe
3) The installation fails.

**How I did:**
When I "Execute with Administrator" it works fine.

**How to hot fix (suggestion):**
include the "Execute with Administrator" step on [Preview of Meteor on Windows](https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows) documentation.

**Comment by stubailo** [comment]
What is the error it displays? What do you mean by "The installation will fail"?

**Comment by dotnetwise** [comment]
This still happens as on `1.1 rtm`

**Comment by stubailo** [comment]
Can we get more details about what it means for the installer to fail? Can you please post a screenshot of the error page, and the log in %LOCALAPPDATA%\Temp?

**Comment by dotnetwise** [comment]
Try yourself to run the installed on a Windows 2012 Server (e.g. local or on azure)

**Comment by stubailo** [comment]
Yes, it worked for us when we ran it on a Windows Server 2012 machine on Amazon EC2

**Comment by diegofaria** [comment]
I will do it tonight and i will post the exactly error.
Sorry for the lack of information.

diegofaria.

2015-04-02 14:42 GMT-03:00 Sashko Stubailo <notifications@github.com>:

**Comment by avital** [comment]
@diegofaria Any updates?

**Comment by diegofaria** [comment]
Sorry @avital, I can't simulate the error again.
I unnistalled meteor, and installed again. No more problem.

The only thing is that when I unninstall, the screen that is showed to me is the same as when installing, there is the image below.

![image](https://cloud.githubusercontent.com/assets/334264/7081668/7b0710e0-df1c-11e4-8e96-f80e69f62102.png)

**Comment by avital** [comment]
Thanks, we should fix the final message when uninstalling.

Happy to hear the issue is resolved.

**Comment by diegofaria** [comment]
I'm glad to help meteor :+1:

**Comment by stubailo** [comment]
@avital I think the current version of the installer should have a correct final screen.
