### ISSUE TITLE
Cross-platform use with .meteor/release file

### ISSUE THREAD

**Issue by Alber70g** [meteor/windows-preview#126]
It's *not* a big issue. 

When you have a repository and working on both Windows and Mac OS X (in my case), you'll get into a problem when starting the application. I'm not sure if this file should be in the repository, or should not exist at all, because it's dependent on the version installed on the server?

Windows
```
WINDOWS-PREVIEW@0.3.0
```

Unix-like
```
METEOR@1.0.4.1
```

**Comment by stubailo** [comment]
You should have both platforms use `WINDOWS-PREVIEW@0.3.0`.
