### ISSUE TITLE
Can't use GridFS

### ISSUE THREAD

**Issue by cyrus-za** [meteor/windows-preview#127]
When I saw the e-mail about 1.1 on windows, first thing I did was install it and run it inside one of my projects that I've been working on with ubuntu. 

Then I get this error: 
```
This project uses METEOR@1.0.1, which isn't available on Windows. To work with this app on all supported platforms, use meteor update --release WINDOWS-PREVIEW@0.3.0 to pin this app to the newest Windows-compatible release.
```

So automatically I go and type `meteor update --release WINDOWS-PREVIEW@0.3.0` and get this error: 
```
=> Errors while initializing project:

While checking for cfs:gridfs@0.0.0:
error: No compatible build found
```

Any ideas why this happens? Is GridFS still on a older version or what?

**Comment by ganySA** [comment]
There is no specific build for many packages specifically for windows. There is a workaround to this.

1) Go find GridFS package on git, clone the repo into your /packages folder
2) go to .meteor/package.conf and manually edit/add the package line item



exec meteor - and it should find its way to compile it as you need!

This is a general workaround that has helped me for a number of builds

this is how i got file-collection to work, which uses gridFS.... hope it works for you.

**Comment by cyrus-za** [comment]
This might sounds like a silly question, but what do you put in the package.conf? The relative path to the repo? Also I don't see package.conf in there, just package with no extension. I assume that is what you were refering to. 

Maybe if you link to your solution in file-collection I can check

**Comment by ganySA** [comment]
Hi

Yes sorry i thought it had a .conf extension. Package is the correct file - you dont need any relative paths just the exact meteor package name.

e.g:
vsivsi:file-collection

Then you download/clone the entire GridFS meteor package repo into /packages/

So you end up with /packages/meteor-file-collection-master 

Re-run meteor, it should build everything in packages with the right npm modules for windows.

**Comment by cyrus-za** [comment]
all the dependencies are already in the package file. So I assume I just need to clone into the folder. What about the folder name? Does that play a role when cloning or does it search for package.json files in all sub folders? Or how does this work? Sounds very hacky

**Comment by ganySA** [comment]
Yes it is a hacky.... but it is also the standard approach one would use when building/testing their own package before deploying it to atmosphere/meteor packages system.

Meteor  is clever enough to build the package from source using the contents of the package folder - iteratively... so not sure folder names matter much!

**Comment by cyrus-za** [comment]
No wonder meteor builds are so slow :)

**Comment by stubailo** [comment]
Filed the issue here: https://github.com/CollectionFS/Meteor-CollectionFS/issues/623

It's now up to the creators of GridFS to publish their package for Windows. Thanks for reporting!
