### ISSUE TITLE
Installer Flags

### ISSUE THREAD

**Issue by tim-faase** [meteor/windows-preview#129]
Is there any documentation on the installation flags/switches available via command line?

/q works for silent but only found that through trial and error.

Ta

**Comment by avital** [comment]
Run the installer with /help

**Comment by digeratisolutions** [comment]
Does nothing except open an empty installer window?

(Server 12 R2 on Powershell)

**Comment by stubailo** [comment]
Here is the help text from the source code of the installer. Printing it using `/help` seems to be broken, you're right! We should fix it, but we might not get to it right away.

```
/passive | /quiet -  displays minimal UI with no prompts or displays no UI and no prompts. By default UI and all prompts are displayed.

/toconsole   - similar to /quiet except that progress is redirected to console.

/log log.txt - logs to a specific file. By default a log file is created in %TEMP%.
```

**Comment by digeratisolutions** [comment]
Thanks.

Can there be consideration to add a flag for skipping the MongoDB installation?

**Comment by avital** [comment]
Why? Meteor installs a local version of MongoDB _within_ the Meteor directory and shouldn't affect your machine in any way unless you're running Meteor.

**Comment by tim-faase** [comment]
We're using an external MongoDB instance which is correctly backed up. Not installing it gives us a method to ensure DB's aren't instantiated locally. If not, totally fine.

**Comment by stubailo** [comment]
Wouldn't you want every developer to have their own local db for development/testing?

The `meteor` command line tool should not be used to host your app in production, and the production deployment directions specify how to use your own database: http://docs.meteor.com/#/full/deploying

**Comment by tim-faase** [comment]
The request is for an *optional* flag to stop the Windows installer from setting up MongoDB. Doesn't stop devs from installing an instance of the DB.

**Comment by avital** [comment]
The installer doesn't actually install Mongo -- it just extracts an archive that contains all of the Meteor dependencies (another examples is Node), so this request is actually "change the way we build Meteor releases to have a separate version without Mongo", which seems like something that would add a lot of work to our release process and benefit very few users.

And if this actually seems to be a feature people want there's nothing special about WIndows here.

Hey, if you /really/ want to disable local Mongo, you can always find and delete all instances of `mongod.exe` that can be found under the Meteor install at C:\Users\<Username>\AppData\Local\.meteor\

Closing this ticket.
