### ISSUE TITLE
"Error: EBADF, read"  on every server refresh

### ISSUE THREAD

**Issue by batjko** [meteor/windows-preview#130]
This comes from the StackOverflow thread [here](http://stackoverflow.com/questions/26737053/w20141104-192353-8485-5-stderr-error-ebadf-read-meteor-js-error/29168406#29168406).

Essentially, every time the Meteor server refreshes (i.e. after a file change), it spits out this error to the console / command window:

![image](https://cloud.githubusercontent.com/assets/7287076/6756151/d9d6378e-cf1f-11e4-8899-f65129bfa6bd.png)

Note that the functionality seems to be unaffected (I was able to run through the entire standard tutorial on the Meteor.com site without problems). Just thought I'd log it and was directed to do so here.

**Comment by Schonne** [comment]
Same here. On Windows 7 64-bit using Meteor 1.1-rc.0

**Comment by DJviolin** [comment]
Same: Windows 7 64-bit using Meteor 1.1-rc.0

**Comment by Dessix** [comment]
Same on 8.1x64.

**Comment by Slava** [comment]
Any antivirus software?

**Comment by Dessix** [comment]
Nope.

**Comment by jaypanares** [comment]
Same here, Win8.1 64bit, installer ver. 1.1.0.1

**Comment by Slava** [comment]
I got a similar error on my Mac while recompiling the app:

```
						      ^
Error: EBADF, fstat
  at Object.Future.wait (/Users/imslavko/.meteor/packages/meteor-tool/.1.0.45.zcukhx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
  at Object.wrapper [as readFile] (/Users/imslavko/.meteor/packages/meteor-tool/.1.0.45.zcukhx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/files.js:1330:24)
  at readFile (/Users/imslavko/.meteor/packages/meteor-tool/.1.0.45.zcukhx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:226:18)
  at [object Object]._.extend._fireIfFileChanged (/Users/imslavko/.meteor/packages/meteor-tool/.1.0.45.zcukhx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:339:20)
  at onWatchEvent (/Users/imslavko/.meteor/packages/meteor-tool/.1.0.45.zcukhx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/watch.js:478:16)
  at [object Object].<anonymous> (/Users/imslavko/.meteor/packages/meteor-tool/.1.0.45.zcukhx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/func-utils.js:35:18)
  at /Users/imslavko/.meteor/packages/meteor-tool/.1.0.45.zcukhx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:161:12
```

**Comment by GiraffeSlacks** [comment]
+1

**Comment by Lenin7** [comment]
+1

**Comment by joegillon** [comment]
+2 - Windows 7 and Windows 8.

**Comment by Geen-Henk** [comment]
+1

**Comment by harryhurry** [comment]
I use both meteor on Windows and on Linux, the EBADF errors occur on both systems, on Windows much more often. For me it seems to be related to have source files open in editors, not happening always but sometimes. Atom seems to cause this quite often. So I doubt, that this error is related to windows only.

**Comment by Tallyb** [comment]
+1

**Comment by sebakerckhof** [comment]
Also seeing this

**Comment by DannyFeliz** [comment]
+1

**Comment by jwvdiermen** [comment]
+1

**Comment by Geen-Henk** [comment]
It rarely outputs `Error: OK, read` too

**Comment by sotarules** [comment]
+1  Just seeing on console from time to time, Windows 7 x64 with Meteor 1.1.0.2

**Comment by dandv** [comment]
Same here with Meteor 1.1.0.2. Windows 7 64-bit, no antivirus (but don't tell anyone). The message appears on every server refresh.

**Comment by rohanray** [comment]
+1 . Windows 7 x64 with Meteor 1.1.0.2

**Comment by midder** [comment]
+1 W7

**Comment by nwalters512** [comment]
+1 Windows 8.1

**Comment by ericgopak** [comment]
+1 Windows 8.1 x64 with Meteor 1.1.0.2, MongoDB 2.6.6

**Comment by wildeyes** [comment]
+1

**Comment by llaine** [comment]
+1

**Comment by mankowitz** [comment]
+1

**Comment by EvilJohnny** [comment]
+1 Windows 8.1 x64 with Meteor 1.1.0.2

**Comment by jackkav** [comment]
+1

**Comment by sami-t** [comment]
+1

**Comment by vinaydate** [comment]
+1 Windows 8.1 x64 with Meteor 1.1.0.2
Packages:
meteor-platform
msavin:mongol
accounts-password
accounts-ui
autopublish
insecure
gadicohen:famous-views
mquandalle:harmony
mjn:famous

**Comment by flaborda** [comment]
+1 Windows 7 x64

**Comment by goodseller** [comment]
same here windows 8 x64

**Comment by shrimpster00** [comment]
I have the same error; Windows 8.1 x64 and Ubuntu 14.04 x64. It doesn't seem to have an effect on the application when it's running, however.

**Comment by cyounghusband** [comment]
I just started getting this error on an app that I've been developing for a month.  Doesn't seem to have an effect yet.   I can't think of any package changes that would cause this.

**Comment by ramdev6498** [comment]
I am getting the same error:  (STDERR) Error: EBADF, read; Windows 8.1 x64.

**Comment by stubailo** [comment]
I'm closing this repo. The main thread is here: https://github.com/meteor/meteor/issues/4201
