### ISSUE TITLE
Cordova built app with 1.0.4.1  doesn't get hot-code-pushes from a 0.3.0 windows preview

### ISSUE THREAD

**Issue by dotnetwise** [meteor/windows-preview#131]
Hot-code-pushes doesn't seem to work from windows backend to the meteor/ngix generated apk/ipa counterpart app.

**Comment by stubailo** [comment]
@Slava does the different version number have something to do with this? It might just be that having the matching version numbers on final release will fix everything.

@dotnetwise, can you try building the cordova app on Mac/Linux using the `WINDOWS-PREVIEW@0.3.0` release, and then see if it hot code pushes from Windows?

**Comment by dotnetwise** [comment]
Release :WINDOWS-PREVIEW@0.3.0 does not exist on ngix

**Comment by Slava** [comment]
@stubailo the actual reason is this: when Meteor doesn't see the mobile platforms to add, it doesn't even bother building them. Then, on Windows Preview releases, you cannot add any platforms and all the existing platforms are ignored, thus there is nothing to hot-code-push.

**Comment by stubailo** [comment]
@dotnetwise, what are you using to run your app with Nginx?

**Comment by dotnetwise** [comment]
Uhm, I can see now on MAC the `WINDOWS-PREVIEW@0.3.0` and also `WINDOWS-PREVIEW@0.4.1` !

I will try to see if hot code pushes will work from windows. 
@Slava you think it should work?

**Comment by dotnetwise** [comment]
Since 1.1 is out this is no more relevant
