### ISSUE TITLE
localhost:3000 doesn't work

### ISSUE THREAD

**Issue by corentin-branquet** [meteor/windows-preview#134]
I created my first meteor app, then I run meteor. 
But this kind of error appear..

![capture](https://cloud.githubusercontent.com/assets/1494224/6779666/ca9c850c-d15e-11e4-8720-aee9fc0eb96c.PNG)

**Comment by batjko** [comment]
Did you try and specify a different port? It seems to look at 127.0.0.1**:3002** for soem reason?

**Comment by stubailo** [comment]
Port 3002 is where mongo runs when you run the meteor server on port 3000.

Do you have mongodb installer on your computer separately from Meteor?

**Comment by corentin-branquet** [comment]
Sorry for the lately response, yes MongoDB is installed separately

**Comment by stubailo** [comment]
I see you have Meteor inside Program Files - can you install it to the default location with the newest installer, remove it from Program Files, and try again?

**Comment by avital** [comment]
@corentin-branquet have you tried @stubailo's suggestion? We don't support installing Meteor to any directory other that the user's local AppData directory anymore. Can you uninstall Meteor from the control panel and the re-install it from the [latest installer](https://install.meteor.com/windows) and see if the error reproduces?

**Comment by corentin-branquet** [comment]
@avital I'll try it tonight, I keep you in touch

**Comment by corentin-branquet** [comment]
I re-installed meteor correctly then I created an app. I ran meteor but there is still a problem
![capture](https://cloud.githubusercontent.com/assets/1494224/7260392/92ca5ec8-e861-11e4-8a46-d8f451ace387.PNG)

**Comment by corentin-branquet** [comment]
Everything is working; I just had to set C:\Window\System32 in the windows path

**Comment by Air2air** [comment]
C:\Windows\System32>meteor create myapp

C:\Users\Todd\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86
_32\dev_bundle\lib\node_modules\fibers\future.js:278
                                                throw(ex);
                                                      ^
Error: EPERM, mkdir 'C:\Windows\System32\myapp'
    at Object.Future.wait (C:\Users\Todd\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:398:15)
    at Object.wrapper [as mkdir] (C:\Users\Todd\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:1350:24)
    at Object.files.mkdir_p (C:\Users\Todd\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:403:11)
    at Object.files.cp_r (C:\Users\Todd\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\files.js:442:9)
    at Command.buildCommands.minArgs [as func] (C:\Users\Todd\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\commands.js:660:11)
    at C:\Users\Todd\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\main.js:1363:23
    - - - - -

It's funny, on the first install it went OK, I was able to cd to myapp.  However it threw this error installing simple-todos.  So I reinstalled and this is as far as I can get.

**Comment by corentin-branquet** [comment]
I don't think that create your app in System32 folder is a good idea.
What I did is to create a folder call "meteor-dev" or whatever and create your meteor app's in this folder
This folder is located here  : C:\meteor-dev

**Comment by Air2air** [comment]
Muchas gracias corentin!

**Comment by corentin-branquet** [comment]
You're welcome ;)
