### ISSUE TITLE
Unable to update package catalog (are you offline?) - Corporate Proxy

### ISSUE THREAD

**Issue by thehogg13** [meteor/windows-preview#135]
I am using a corporate proxy (Cisco Ironport) to try and update meteor or add packages and it doesn't appear to be sending the requests to the proxy. When i clear my HTTP_PROXY and HTTPS_PROXY env variables, i can see the requests making it to the Firewall, and being dropped. As soon as i set the variables again, the Firewall no longer has any drops, which leads me to believe the requests are going to the proxy, however, i cant find anything in the proxy logs for the attempted connection.

![aa_ 20150325_44](https://cloud.githubusercontent.com/assets/11642507/6819106/d78e2bb4-d30f-11e4-92c9-2fb8dc61de30.jpg)

**Comment by thehogg13** [comment]
![aa_ 20150325_45](https://cloud.githubusercontent.com/assets/11642507/6819122/1d293704-d310-11e4-831d-ea4ad8ca9ae5.jpg)

**Comment by ganySA** [comment]
I think 4.1 came out so must relate to that. i dont have package catalog problems but the catalog doesnt have the packages i need to update to 4.1 :/

**Comment by stubailo** [comment]
@ganySA are you saying updating didn't work for you? Can you post the full output of when you tried to update?

@thehogg13 I think for the initial release we aren't going to support developing from behind a proxy, but it's near the top of our priorities for the future. @debergalis does this sound right?

**Comment by thehogg13** [comment]
Thanks for the reply @stubailo  , at least that explains it ... Happy to test any releases that support proxy if and when you get to it mate.

**Comment by Slava** [comment]
@thehogg13 on unix we lookup the `http_proxy` env variable. Can you try setting it in your cmd.exe before running meteor and seeing if this works?

**Comment by thehogg13** [comment]
Yeah i have set the variables, and it seems to attempt to use them, but i dont see the traffic routing through our proxy.

**Comment by Slava** [comment]
@thehogg13 I just checked on my machine, setting `HTTP_PROXY` and `HTTPS_PROXY` env variables works for me. Here is what it looks like for me:

```batch
set HTTP_PROXY=http://slava:password@138.128.30.2:60099
set HTTPS_PROXY=http://slava:password@138.128.30.2:60099
meteor update
```

Can you try something similar? Notice the `http://` part for both HTTP and HTTPS.

**Comment by thehogg13** [comment]
YOU ARE A GUN! That has absolutely fixed the issues ... I had these defined without the http:// ... Now that these are defined correctly I am updating and adding packages with keys of fury ... thanks @Slava

**Comment by Slava** [comment]
Glad it worked!

**Comment by stubailo** [comment]
@Slava We should document this somewhere!

**Comment by Slava** [comment]
@stubailo https://github.com/meteor/meteor/wiki/Using-Meteor-behind-a-proxy

**Comment by thehogg13** [comment]
What is interesting , is that using cf tools to upload to IBM Bluemix, the build fails if the env variables contain the http:// , so what i have been doing is setting them to inlclude http:// when doing meteor commands , and then removing the http:// to use cf tools. The dream would be that both used the same construct ... but ill jst keep dreaming :) , thanks again for your help @Slava @stubailo

**Comment by Slava** [comment]
I don't think it will be right for meteor to guess the protocol of your proxy when it can be both http and https

**Comment by thehogg13** [comment]
*sigh* - Now with release 1.1 neither option works ...

**Comment by Slava** [comment]
I don't know why you reopened this ticket. I received an email with you saying this doesn't work anymore, but later you removed the comment. So I assume everything is resolved now.

**Comment by thehogg13** [comment]
Yeah, didn't work for like 30 mins in the morning, then as soon as I commented it just "started working" ... Felt like my days back on Helpdesk all over again ... Did forget to reclose though ... thanks

**Comment by stubailo** [comment]
Good times.
