### ISSUE TITLE
update constraints problem

### ISSUE THREAD

**Issue by ganySA** [meteor/windows-preview#136]
Hi

I am trying to upgrade to 4.1. and i get a limitation:

"This project is at the latest release which is compatible with your current package constraints."

How can i identify what is constraining my update and bypass it?

When i do meteor list i see that the following packages have upgrades:
accounts-password                     1.1.0-win.1* Password support for accounts
http                               1.1.0-rc.0* Make HTTP calls to remote servers
insecure                           1.0.3-rc.0* Allow all database writes by default
reactive-var                       1.0.5-rc.0* Reactive variable
service-configuration              1.0.4-rc.0* Manage the configuration for third-party services

thanks

**Comment by stubailo** [comment]
Try running `meteor update --release WINDOWS-PREVIEW@0.4.1 --allow-incompatible-update`

**Comment by ganySA** [comment]
doesnt work :(

**Comment by ganySA** [comment]
tried to create a new project even using meteor create and i get the following, any ideas?

While selecting package versions:
error: Conflict: Constraint autoupdate@1.2.0 is not satisfied by autoupdate 1.2.0-pre.win.1.
Constraints on package "autoupdate":
* autoupdate@=1.2.0-pre.win.1 <- top level
* autoupdate@1.2.0 <- meteor-platform 1.2.2

**Comment by ganySA** [comment]
Yeah something is pretty 'sick' at the moment. even after meteor create i keep getting this error... autoupdate seems to be wrong.. but i have no idea how to fix that!

**Comment by avital** [comment]
We should look into this, but generally I don't think there's no reason at the moment to upgrade to 0.4.1 -- we only made the release to help with publishing binary packages: https://github.com/meteor/windows-preview/issues/105#issuecomment-85848856

**Comment by stubailo** [comment]
OK @ganySA I would recommend going back to WINDOWS-PREVIEW@0.3.0 for now.

**Comment by stubailo** [comment]
@ganySA try using `METEOR@1.1-rc.0`

**Comment by ganySA** [comment]
Great working thanks :)

**Comment by avital** [comment]
Awesome!
