### ISSUE TITLE
Meteor install vs. PATH length

### ISSUE THREAD

**Issue by gingerbooth** [meteor/windows-preview#137]
Just FYI, when I installed Meteor on Windows7, I was unable to run "meteor". Tracking this down, I was able to execute "node" and "npm", but not "meteor" because the meteor directory wasn't on the PATH. I removed something from the PATH variable, and now "meteor" works.

That is -

Start | Computer | System properties | Advanced system settings | Environment Variables 

and edited CLASSPATH under "system variables" to remove something, so that the "User variables for Ginger" PATH would fit, and execute properly. 

People are likely to have this issue if they program with a bunch of techs. I've got jre's, assorted Windows directories, Zend server, mysql, git... It's a bloated path.

**Comment by gingerbooth** [comment]
![installmeteorpath](https://cloud.githubusercontent.com/assets/6087993/6850590/712b3be0-d3b0-11e4-8e15-31e7f6d53a5c.png)

**Comment by liJiansheng** [comment]
Hi I only have jre under the CLASSPATH but I am still unable to run meteor. Would you happen to know why?

**Comment by stubailo** [comment]
@gingerbooth were you able to resolve this issue?

If not, post a new issue on meteor/meteor

**Comment by gingerbooth** [comment]
I worked around it.
