### ISSUE TITLE
Meteor reset does not work in Meteor 1.1-rc.0

### ISSUE THREAD

**Issue by mesosteros** [meteor/windows-preview#138]
When I run the meteor reset command it incorrectly interprets meteor as still running when it's not.
The following messages show on the command line:

C:\Users\mesos_000\Desktop\Projects\testingStuff>meteor reset
reset: Meteor is running.

This command does not work while Meteor is running your application. Exit the running Meteor development server.

**Comment by avital** [comment]
Thanks for the report -- I was able to reproduce this locally.

**Comment by avital** [comment]
Should be fixed in https://github.com/meteor/meteor/commit/120febbf8a40f262e436d907ff36e469a19d7698, will be out in the next 1.1 release candidate.

Thanks again for the report!

**Comment by stubailo** [comment]
Out now: try doing `meteor update --release 1.1-rc.1`, and see if `meteor reset` works for you!

**Comment by mesosteros** [comment]
Tested it today. Now working :+1:  Thanks!

**Comment by lhidalgo-** [comment]
i had the same problem,
but now works fine
thanks
