### ISSUE TITLE
meteor.bat does not work when the path contains spaces

### ISSUE THREAD

**Issue by marfago** [meteor/windows-preview#14]
This is a very common problem with Windows, and the way to solve it is just to wrap the variables with quotes. Example

%~dp0\packages\meteor-tool\1.0.36-win.0\meteor-tool-os.windows.x86_32\meteor.bat --release WINDOWS-PREVIEW@0.0.10 %* should be
"%~dp0\packages\meteor-tool\1.0.36-win.0\meteor-tool-os.windows.x86_32\meteor.bat" --release WINDOWS-PREVIEW@0.0.10 %*

It is needed in all the bat files.

**Comment by Slava** [comment]
Should be fixed in the latest preview, can anyone confirm?

**Comment by gulgiraf** [comment]
not fixed

**Comment by stubailo** [comment]
Just fixed this for real and tested it: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows
