### ISSUE TITLE
password becomes username - *nasty*

### ISSUE THREAD

**Issue by gingerbooth** [meteor/windows-preview#140]
Using the Meteor Windows install, I created a new account when prompted to, with my email address, and a password. Later, I tried logging into the Meteor site. What I thought was my username, was unrecognized, but no problem, it recognized my email address. And I entered my password. At that point, I was logged in correctly, but it was using my PASSWORD as my username. I think.

**Comment by stubailo** [comment]
We've never seen this happen - is it possible for you to try to reproduce it again and send us screenshots?

**Comment by gingerbooth** [comment]
I'll try to remember to uninstall/reinstall after I finish the tutorial. I think it was the install that did this - unless that dialog only asks for email address and username, and not for a password, and I misread it?

**Comment by stubailo** [comment]
Thanks!

**Comment by gingerbooth** [comment]
OK! I think I must have typed in the password twice (for verification) instead of username and password, on automatic. Kinda sleepwalking today. Usually these forms ask for email address, or username, not both, and verify hidden password. At any rate, I could not reproduce, but would not be astonished if the same thing happened to other people. Sorry to bother you. Did take pictures of other minor stuff along the way:

![uninstallingmeteor](https://cloud.githubusercontent.com/assets/6087993/6856034/7e8eac54-d3d3-11e4-8fa0-a63a5df21cea.png)
![meteorctrlc](https://cloud.githubusercontent.com/assets/6087993/6856038/82d01c58-d3d3-11e4-8696-d0078ae59109.png)

**Comment by gingerbooth** [comment]
As a request, maybe the validation could disallow Username === password?

**Comment by stubailo** [comment]
@gingerbooth one workaround would be to change the email address on the old account to something invalid, and then add that email address to your new account.

**Comment by gingerbooth** [comment]
Oh, cool. Then uninstall/reinstall Meteor again, I assume.

**Comment by stubailo** [comment]
No, you can use `meteor logout` and `meteor login` on the command line :]
