### ISSUE TITLE
Name the installer with the version

### ISSUE THREAD

**Issue by keithn** [meteor/windows-preview#141]
Small issue, but it's nice if the installers have unique names based on their versions. Otherwise you end up with windows giving it a new name like :-
![image](https://cloud.githubusercontent.com/assets/86080/6858003/f0faa594-d46f-11e4-8e06-5cdde56b1173.png)

Not a huge issue, but just something to consider.

**Comment by stubailo** [comment]
Great idea! We will consider it in the near future, but not for the initial release.

**Comment by avital** [comment]
We're probably switching to an installer that always installs the latest version of Meteor, so there won't be versioning for the installer.

It's worth pointing out that you can use any release of Meteor once you have it installed by creating an app with `meteor create --release 1.x.y`.
