### ISSUE TITLE
Meteor Windows 1.1-rc0: Use external Node.js, MongoDB installations from PATH.

### ISSUE THREAD

**Issue by DJviolin** [meteor/windows-preview#143]
I installed Meteor preview on Windows 7. I have Node.js and MongoDB installed locally and in my PATH. I noticed that Meteor Preview using his own local Node and Mongodb. Is it same on Linux? Is there any options available to abandone the packed-in Node.js, MongoDB with Meteor and use them from my PATH?

Why not give an option to a separate Zip file on Windows?

**Comment by stubailo** [comment]
@DJviolin Meteor does this on all platforms, to ensure that the versions of Node and Mongo are exactly what we expect. Otherwise it will be easy to run into a multitude of compatibility errors depending on what versions of Node/Mongo you have installed.
