### ISSUE TITLE
Any idea who is behind the "windows" MD account?

### ISSUE THREAD

**Issue by dandv** [meteor/windows-preview#144]
https://atmospherejs.com/windows/npm-bcrypt
and
https://atmospherejs.com/windows/meteor-tool

should probably be deprecated.

The package have no GitHub information whatsoever, and I found it impossible to track who's behind them.

**Comment by dandv** [comment]
It's [apparently](https://github.com/meteor/windows-preview/issues/16#issuecomment-87115548) @sdarnesll.

Would be good to `meteor admin set-unmigrated` windows:* packages.

**Comment by dandv** [comment]
It's [apparently](https://github.com/meteor/windows-preview/issues/16#issuecomment-87115548) @sdarnell.

Would be good to `meteor admin set-unmigrated` windows:* packages.

**Comment by dandv** [comment]
@sdarnell - is "junk" also your namespace? Looks like some Windows testing work has gone in there. https://atmospherejs.com/junk

**Comment by stubailo** [comment]
Nope, junk is me and @Slava, we should clean that up eventually

**Comment by dandv** [comment]
Those junk packages show up as false results for various searches, so it would be nice to unmigrate them, and also write something more descriptive in the https://atmospherejs.com/junk profile (e.g. set the Twitter username to meteorjs at least).

Here, I've made the unmigration easy:

```text
meteor admin set-unmigrated avital:junk-with-colons 
meteor admin set-unmigrated junk:bla                
meteor admin set-unmigrated junk:has-colons         
meteor admin set-unmigrated junk:junk1              
meteor admin set-unmigrated junk:junk10             
meteor admin set-unmigrated junk:junk11             
meteor admin set-unmigrated junk:junk12             
meteor admin set-unmigrated junk:junk13             
meteor admin set-unmigrated junk:junk14             
meteor admin set-unmigrated junk:junk15             
meteor admin set-unmigrated junk:junk2              
meteor admin set-unmigrated junk:junk3              
meteor admin set-unmigrated junk:junk4              
meteor admin set-unmigrated junk:junk5              
meteor admin set-unmigrated junk:junk6              
meteor admin set-unmigrated junk:junk7              
meteor admin set-unmigrated junk:junk8              
meteor admin set-unmigrated junk:junk9              
meteor admin set-unmigrated junk:katex              
meteor admin set-unmigrated junk:lol                
meteor admin set-unmigrated junk:markdown-templating
meteor admin set-unmigrated junk:node-xmpp          
meteor admin set-unmigrated junk:npm-bcrypt         
meteor admin set-unmigrated junk:npm-node-aes-gcm   
meteor admin set-unmigrated junk:scss               
meteor admin set-unmigrated junk:testtar
```

**Comment by Slava** [comment]
I unmigrated most of them, I left out the ones with colons, because I think we still use them in manual tests.

**Comment by Slava** [comment]
The `windows` organization is by @sdarnell if I am not mistaken

**Comment by dandv** [comment]
Thanks @Slava, I don't see any more junk packages now. You've probably unmigrated the colon ones too because they're sill installable if unmigrated, just not searchable from Atmosphere.

Same thing for https://atmospherejs.com/test please, if it's an org you control?

**Comment by sdarnell** [comment]
I've done the windows ones.

**Comment by stubailo** [comment]
@sdarnell - how can we update win.meteor.com when the official release of 1.1 happens? Of course, we can override it completely but I think it would be nice to involve the current maintainer.

**Comment by sdarnell** [comment]
You need to speak to @gabrielhpugliese (as I was too slow to get the win.meteor.com app).

**Comment by gabrielhpugliese** [comment]
What are your meteor usernames? I'll give all permissions

**Comment by Slava** [comment]
@gabrielhpugliese add "mdg"

**Comment by gabrielhpugliese** [comment]
```
~$meteor authorized win.meteor.com
gabrielhpugliese
mdg
```
