### ISSUE TITLE
"Unexpected mongo exit code 100" in a path with non-ASCII characters

### ISSUE THREAD

**Issue by Slava** [meteor/windows-preview#145]
subj, you can run glasser's newest test for running mongo in a folder with unicode chars and see the failure of Mongo failing to start with code 100. Probably half of our previous reports are related.

**Comment by glasser** [comment]
`meteor self-test unicode`

**Comment by avital** [comment]
We should either see if we can fix this, or at the very least print a message to the user describing the problem.

**Comment by glasser** [comment]
In fact, self-test fails on devel on windows because of this (intentionally).
