### ISSUE TITLE
Meteor fails to run the todos app

### ISSUE THREAD

**Issue by Heyho-letsgo** [meteor/windows-preview#146]
C:\Users\André\Desktop\meteortest\todos>meteor
[[[[[ C:\Users\André\Desktop\meteortest\todos ]]]]]

=> Started proxy.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Unexpected mongo exit code 100. Restarting.
Can't start Mongo server.
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.

**Comment by Slava** [comment]
There are multiple reasons why you might fail to run mongo on your computer. See #8 for the discussion.

**Comment by Heyho-letsgo** [comment]
Finaly I've created a partition of 10G on C: (E:) Then I ran meteor create todos and after I ran meteor and it was ok ! ;-)
