### ISSUE TITLE
Problem while logging in on the installer

### ISSUE THREAD

**Issue by laosb** [meteor/windows-preview#147]
![image](https://cloud.githubusercontent.com/assets/2545261/6884015/49e7a910-d608-11e4-8147-7b687da9b62f.png)
The system is Windows XP SP2, on PD10 for Mac.

I just want to log in, but when I click `Sign In` it show me an empty alert.

**Comment by laosb** [comment]
I skipped and then use `meteor login`, it's fine.
![image](https://cloud.githubusercontent.com/assets/2545261/6884029/20f76134-d609-11e4-8830-548716c65abc.png)

**Comment by wreiske** [comment]
Same issue here from inside the installer. 
![image](https://cloud.githubusercontent.com/assets/6295044/6893584/28d441a4-d69c-11e4-89af-6054e994d58c.png)

**Comment by laosb** [comment]
Wondering if Meteor for Windows v1.1.01 has the same problem. Testing out.

**Comment by stubailo** [comment]
I think we fixed this in 1.1 actually - by fixed I mean we display a better error now

**Comment by laosb** [comment]
Yeah you guys fixed it - Good job!
