### ISSUE TITLE
Constraint autoupdate@1.2.0 is not satisfied by autoupdate 1.2.0-pre.win.1.

### ISSUE THREAD

**Issue by skpatel20** [meteor/windows-preview#148]
I had installed meteor preview version on `Windows 8.1` a couple of days back, and was able to practice the quickstart application (available at `meteor.com`). But today when I tried to create another application using the command
```
meteor create microscope
```
I am getting this error
```
error: Conflict: Constraint autoupdate@1.2.0 is not satisfied by autoupdate 1.2.0-pre.win.1.
Constraints on package "autoupdate":
* autoupdate@=1.2.0-pre.win.1 <- top level
* autoupdate@1.2.0 <- meteor-platform 1.2.2
```

**Comment by stubailo** [comment]
Are you running the most recent released version? That's `1.1-rc.0`.

**Comment by skpatel20** [comment]
`meteor --version` shows WINDOWS-PREVIEW@0.3.0

`meteor update` tells that "The latest version of Meteor, 0.3.0, is already installed on this computer. Run 'meteor update' inside of a particular project directory to update that project to WINDOWS-PREVIEW@0.3.0"

**Comment by skpatel20** [comment]
It's now working. Didn't do any change. No idea why it was not working before, and it's working now.

**Comment by stubailo** [comment]
@skpatel20 we changed some things between that release and now, please use the newest installer to update. `meteor update` should work flawlessly starting with the official release, but before now we had to do some version number hacks to get things to work correctly.
