### ISSUE TITLE
scripts in package.json not OS agnostic

### ISSUE THREAD

**Issue by robfallows** [meteor/windows-preview#149]
We use scripts and have this:

    "scripts": {
      "start": "meteor --settings config/settings.json",
      "stop":  "kill $(ps ax | grep 'meteor' | awk '{print $1}')"
    }

which clearly won't (and indeed doesn't) work under Windows. I sort of expected the `start` to work, since it only requires a change of slash, but even that failed.

A workaround would be root-level script filenames, with OS detection logic, but that seems overly complex.

**Comment by stubailo** [comment]
Which package.json are you talking about? As far as I am aware there is no officially supported Meteor feature that involves this type of file. Is this related to a community package or tool?

**Comment by robfallows** [comment]
This is one of our internal packages (so, it's no big deal for us). However, I have read of community package writers (as in on atmosphere) using scripts and that may be a problem.
