### ISSUE TITLE
Adding a package report wrong (old) info

### ISSUE THREAD

**Issue by vjau** [meteor/windows-preview#15]
On win preview 0.0.10
When doing "meteor add foo" (with foo a local package),
then when doing 
"meteor add bar" (with bar a local package),
the installer reports:

added foo at version 1.0.0
bar: do stuff 

Instead, it shoud report only "bar: do stuff", since bar has no dependency on foo. It seems there is a bug that show previous updating in place of only the last addition.

**Comment by stubailo** [comment]
Does this still happen with the newest preview? https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

Let me know!

**Comment by vjau** [comment]
Sorry @stubailo , i have not been running the preview lately, due to other erros preventing me from running it.

**Comment by stubailo** [comment]
I think this is fixed in the newest release.
