### ISSUE TITLE
Package Issues & release says WINDOWS-PREVIEW@0.3.0

### ISSUE THREAD

**Issue by bluebay** [meteor/windows-preview#151]
There are several incompatible packages which are very important for example sanjo:jasmine. 
When I try to install this package, I get error:No compatible build found.

Does this error has anything to do with the release no?
I tried installing the package after downloading today's latest windows package.

**Comment by stubailo** [comment]
Try uninstalling and re-installing using the new Meteor 1.1 installer. Some of the hacks in the `WINDOWS-PREVIEW@0.3.0` release are making it hard for people to update using `meteor update`. Let me know if that helps.

**Comment by bluebay** [comment]
@stubailo Thanks. I did that. Here are the steps:
 
1. Uninstalled meteor using control panel.
2. Using the latest windows installer, I installed meteor.
3. Go the the meteor project folder and typed meteor
   I saw this message in the console:
   Downloading meteor-tool@1.1.1-win.7...
4. After this, it downloaded all the packages in the project.
5. I tried to install sanjo:jasmine again: I get:

 => Errors while adding packages:

While checking for sanjo:karma@1.4.2:
error: No compatible build found

**Comment by benjick** [comment]
I uninstalled Meteor, installed Meteor and restarted. Meteor update still gives me `This project is already at WINDOWS-PREVIEW@0.3.0, the latest release.`

Can I specify something like `meteor update --release 1.1.0`?

**Comment by andmitsch** [comment]
@benjick it's --release METEOR@1.1 yet you still need to get rid of the local/.meteor folder. Take a look at that if you've used the uninstaller, maybe it's still there.

**Comment by benjick** [comment]
Cheers.

After uninstalling, deleting %localappdata%\.meteor and reinstalling I was able to update with `meteor update --release METEOR@1.1`

**Comment by stubailo** [comment]
Thanks, sorry the transition is not optimal. Starting from the official
release you shouldn't have to do anything weird like uninstall.

**Comment by benjick** [comment]
It's what previews are for :) 

Thank you so much for bringing 1.1 to Windows!

**Comment by GilbertMizrahi** [comment]
I haven't been able to update from WINDOWS-PREVIEW@0.3.0 to the latest release.
I Uninstalled meteor using control panel; Using the latest windows installer, I installed meteor, but when i run meteor update it says that I have the latest version WINDOWS-PREVIEW@0.3.0.

I am trying to find %localappdata%.meteor to delete it, but I don't see it anywhere.


.

**Comment by benjick** [comment]
Win key + r and type it there. It's a variable.

**Comment by GilbertMizrahi** [comment]
It says that it doesn't exist.
I ran meteor update --release METEOR@1.1.0.2 and that worked fine.

**Comment by sdarnell** [comment]
You might need to put a slash before .meteor

Also note that winxp doesn't have a LOCALAPPDATA, on winxp look in APPDATA.
