### ISSUE TITLE
Can't run Meteor anymore - mini-files.js?

### ISSUE THREAD

**Issue by mastastealth** [meteor/windows-preview#154]
Last night I was trying this: https://forums.meteor.com/t/help-test-the-preview-release-with-new-upcoming-blaze-features-each-in-let-index/637

It was working fine, but today I tried running the same project and it failed. No problem, I'll just switch back to my main branch without the each-in stuff and it should be back to normal - I thought. Nope, same error. Basically any meteor commands now shows:

![sadface](https://cloud.githubusercontent.com/assets/1221228/7026907/a9a82ec4-dd1a-11e4-9ccd-ddedf8089cc3.png)

**Comment by stubailo** [comment]
@mastastealth you're running an old preview version of Windows. Try reinstalling using the newest installer from meteor.com

I'm closing this repo. Post any new issues on meteor/meteor.
