### ISSUE TITLE
Meteor update command very slow

### ISSUE THREAD

**Issue by mesosteros** [meteor/windows-preview#155]
The meteor update command is still very slow. After the progress bar completes it becomes a constantly rotating dash (/) and it takes a very long time to complete.
The components that are slow are meteor-tool@1.1.0-winr.8 and meteor-tool@1.1.1-win.7. Previous versions were also slow but from what I perceive this one is taking the longest.

Here is a gif of the problem:
![meteor update](https://cloud.githubusercontent.com/assets/1943233/7064626/23dc32d8-dea8-11e4-9a38-59e6eaa199f4.gif)

**Comment by stubailo** [comment]
@mesosteros try reinstalling Meteor using the newest installer from Meteor.com. You're still running an old preview version.

Closing this repo. Please post any new issues on meteor/meteor.
