### ISSUE TITLE
Command to prepare the app, launch it, and immediately exit

### ISSUE THREAD

**Issue by paralin** [meteor/windows-preview#156]
I don't see any other way to do this.

I need a command in the meteor tool to have Meteor install all packages, build the project, launch the server once successfully, and then exit. This is an important testing phase when deploying updates - I need to detect any errors in the installation/launch of the app, which works great with meteor error exit codes. But the problem is there's no way to have Meteor exit upon successfully launching the server.

A hacky way to do this is to use expect to watch for the success message and then quit.

**Comment by Slava** [comment]
Please reopen this on the main meteor repo.

**Comment by Slava** [comment]
to answer your question: `meteor run --once` is the command you are looking for

**Comment by paralin** [comment]
Crap. I didn't even realize I was on this repo. And thank you! I couldn't find that option.
