### ISSUE TITLE
Unexpected mongo exit code 100

### ISSUE THREAD

**Issue by ayal** [meteor/windows-preview#157]
I am pretty sure I am running the latest meteor-windows installation.. I still get this error once in a while and solving it by doing a "meteor reset" is how I get to keep working, unfortunately.

**Comment by avital** [comment]
Thanks, this is a dup of #8.

(If you run `meteor --version` what does it print?)

**Comment by avital** [comment]
If you're running 1.1.0.2, are you by chance using Google Drive to sync your app directory? One user reported that may be the cause of the issue: https://github.com/meteor/windows-preview/issues/8#issuecomment-92605319
