### ISSUE TITLE
While deploying from windows: error: npm-bcrypt is not compatible with architecture 'os.linux.x86_64'

### ISSUE THREAD

**Issue by ayal** [meteor/windows-preview#158]
The full error:
Errors prevented deploying:
While Building the application:
error: npm-bcrypt is not compatible with architecture 'os.linux.x86_64'

**Comment by avital** [comment]
I just deployed an app successfully.

If you run `meteor --version` from within your app's directory, what does it print?

**Comment by stubailo** [comment]
Closing, no reproduction
