### ISSUE TITLE
>ERROR meteor add sanjo:jasmine

### ISSUE THREAD

**Issue by pdavidow** [meteor/windows-preview#159]
METEOR@1.1.0.2 using 'default' meteor app.
I want to install and use Velocity with Jasmine...

meteor add sanjo:jasmine
 => Errors while adding packages:

While checking for sanjo:karma@1.4.3:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your
platform.

**Comment by avital** [comment]
As the error message suggests, please contact the package author and ask them to publish sanjo:karma@1.4.3 for Windows.

**Comment by pdavidow** [comment]
According to http://velocity.meteor.com/, Velocity is 'the officially sanctioned testing framework for Meteor'.  So I would think having Velocity work properly would be a prereq to the official Windows release.
