### ISSUE TITLE
Error: Couldn't run tasklist: {"code":"ENOENT","errno":"ENOENT","syscall":"spawn "}

### ISSUE THREAD

**Issue by jayedgar** [meteor/windows-preview#16]
first, thanks for the windows installer!  i created sample project without error and it appears to have the correct files in it. failed when starting meteor for the new project.

i am running windows 7 with latest servicepacks. just in case, also tried running with command prompt as admin, but get same error.

not sure if there are any dependencies i might not have installed or configured correctly before running your install.  i recall the meteor has a dependency on MongoDb?  I have that on my machine, although also just getting started with it.

a  copy of session follows...

C:\meteor-projects>meteor create --example todos

In order to resolve constraints, we had to use the following
experimental package versions:
  npm-bcrypt@0.7.8-win.0  Wrapper around the bcrypt npm package

todos: created.

To run your new app:
   cd todos
   meteor

C:\meteor-projects>cd todos

C:\meteor-projects\todos>meteor
[[[[[ C:\meteor-projects\todos ]]]]]

=> Started proxy.

C:\Users\JC\AppData\Local\.meteor\packages\meteor-tool\1.0.36-win.0\meteor-tool-
os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:206
                                                throw(ex);
                                                      ^
Error: Couldn't run tasklist: {"code":"ENOENT","errno":"ENOENT","syscall":"spawn
"}
    at Object.Future.wait (C:\Users\JC\AppData\Local\.meteor\packages\meteor-too
l\1.0.36-win.0\meteor-tool-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\
future.js:326:15)
    at findMongoPids (C:\Users\JC\AppData\Local\.meteor\packages\meteor-tool\1.0
.36-win.0\meteor-tool-os.windows.x86_32\tools\run-mongo.js:146:16)
    at findMongoAndKillItDead (C:\Users\JC\AppData\Local\.meteor\packages\meteor
-tool\1.0.36-win.0\meteor-tool-os.windows.x86_32\tools\run-mongo.js:176:14)
    at launchOneMongoAndWaitForReadyForInitiate (C:\Users\JC\AppData\Local\.mete
or\packages\meteor-tool\1.0.36-win.0\meteor-tool-os.windows.x86_32\tools\run-mon
go.js:291:5)
    at launchMongo (C:\Users\JC\AppData\Local\.meteor\packages\meteor-tool\1.0.3
6-win.0\meteor-tool-os.windows.x86_32\tools\run-mongo.js:550:7)
    at _.extend._startOrRestart (C:\Users\JC\AppData\Local\.meteor\packages\mete
or-tool\1.0.36-win.0\meteor-tool-os.windows.x86_32\tools\run-mongo.js:639:19)
    at _.extend.start (C:\Users\JC\AppData\Local\.meteor\packages\meteor-tool\1.
0.36-win.0\meteor-tool-os.windows.x86_32\tools\run-mongo.js:605:10)
    at C:\Users\JC\AppData\Local\.meteor\packages\meteor-tool\1.0.36-win.0\meteo
r-tool-os.windows.x86_32\tools\run-all.js:147:26
    at C:\Users\JC\AppData\Local\.meteor\packages\meteor-tool\1.0.36-win.0\meteo
r-tool-os.windows.x86_32\tools\buildmessage.js:313:18
    at _.extend.withValue (C:\Users\JC\AppData\Local\.meteor\packages\meteor-too
l\1.0.36-win.0\meteor-tool-os.windows.x86_32\tools\fiber-helpers.js:112:14)
    at C:\Users\JC\AppData\Local\.meteor\packages\meteor-tool\1.0.36-win.0\meteo
r-tool-os.windows.x86_32\tools\buildmessage.js:312:36
    at _.extend.withValue (C:\Users\JC\AppData\Local\.meteor\packages\meteor-too
l\1.0.36-win.0\meteor-tool-os.windows.x86_32\tools\fiber-helpers.js:112:14)
    at Object.enterJob (C:\Users\JC\AppData\Local\.meteor\packages\meteor-tool\1
.0.36-win.0\meteor-tool-os.windows.x86_32\tools\buildmessage.js:303:26)
    at _.extend.start (C:\Users\JC\AppData\Local\.meteor\packages\meteor-tool\1.
0.36-win.0\meteor-tool-os.windows.x86_32\tools\run-all.js:146:20)
    at Object.exports.run (C:\Users\JC\AppData\Local\.meteor\packages\meteor-too
l\1.0.36-win.0\meteor-tool-os.windows.x86_32\tools\run-all.js:318:10)
    at Command.doRunCommand [as func] (C:\Users\JC\AppData\Local\.meteor\package
s\meteor-tool\1.0.36-win.0\meteor-tool-os.windows.x86_32\tools\commands.js:347:1
7)
    at C:\Users\JC\AppData\Local\.meteor\packages\meteor-tool\1.0.36-win.0\meteo
r-tool-os.windows.x86_32\tools\main.js:1303:23
    - - - - -
    at C:\Users\JC\AppData\Local\.meteor\packages\meteor-tool\1.0.36-win.0\meteo
r-tool-os.windows.x86_32\tools\run-mongo.js:101:24
    at exithandler (child_process.js:644:7)
    at ChildProcess.errorhandler (child_process.js:660:5)
    at ChildProcess.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:808:12)

C:\meteor-projects\todos>

**Comment by stubailo** [comment]
@jayedgar, did the fix from @mushasun work for you? As far as I can tell the only reason this could happen is if `tasklist` isn't in your path or not on your computer at all. From my research it seems that this should only happen on Windows XP Home edition, but you're on Windows 7.

**Comment by sdarnell** [comment]
It is pretty unusual not to have system32 on your path, as there are some fairly crucial things in it.
However, in this case we could change meteor to use a full path i.e. `%SystemRoot%\System32\tasklist.exe`

But I suspect it is more likely that the PATH had got messed up. It may be worth waiting to see if @jayedgar  responds, and can explain if there was a good reason not to have system32 on the PATH before changing to using a fully qualified path.

**Comment by jayedgar** [comment]
Sorry for late reply, busy getting a release out at work.  Will try to get to it this weekend. Thanks for checking on status!

**Comment by jayedgar** [comment]
Will have to check my bug report, but don't believe system32 path not being present in path or on disk was the root issue. As you say, none of my development tools would even work if that were the case.

**Comment by jayedgar** [comment]
All is well now. Installed 0.1.6.  First simple todo now works. Will start trying more. Again, thanks for the follow up.

**Comment by stubailo** [comment]
OK, going to close this for now.

**Comment by dandv** [comment]
Hey @jayedgar, are you guys behind https://atmospherejs.com/windows/npm-bcrypt ?

It should be deprecated now that [MDG has added build for all platforms for npm-bcrypt](https://github.com/meteor/meteor/blob/devel/packages/non-core/npm-bcrypt/package.js).

**Comment by sdarnell** [comment]
I'm the owner if that one. I'll deprecate it, of transfer the group to MDG.

**Comment by SockMonster1** [comment]
Hey mushasun's answer didn't work however when I added the extra slash at the end:
"set path=%path%;C:\Windows\System32"
to
"set path=%path%;C:\Windows\System32\"
I managed to get mine working. Could Meteor be trying to find the file via:
"C:\Windows\System32" + "tasklist.exe" ("C:\Windows\System32tasklist.exe") <---- note the "System32tasklist.exe"
as opposed to
"C:\Windows\System32\" + "tasklist.exe" ("C:\Windows\System32\tasklist.exe")?

Just my 2 cents.
