### ISSUE TITLE
Android SDK for Windows

### ISSUE THREAD

**Issue by anuragmittal89** [meteor/windows-preview#161]
Hi Team,

I am new to Meteor, had a query in mind why meteor install-sdk android is not available for Microsoft Windows. I want ed to post this query on Forums but thought its a very basic query. It must have been asked by anyone there but I am unable to find it. Can you please help me to answer my question.

Is meteor install-sdk android really not available for windows or it is an issue?
Is there any alternative to create android app in windows using meteor?
Is there is no way to create android app using meteor, when can I expect this feature from Meteor Team?
Your response is awaited and any help will be appreciated .

Thanks in Advance.

Regards,
Anurag

**Comment by Orbyt** [comment]
+1

**Comment by lukemadera** [comment]
+1

**Comment by TWSgit** [comment]
+1

**Comment by charlieysc** [comment]
+1

**Comment by druzza** [comment]
+1

**Comment by whiplashoo** [comment]
+1

**Comment by stubailo** [comment]
Tracking this here: https://github.com/meteor/meteor/issues/4155
