### ISSUE TITLE
Can't install serialport package in Windows

### ISSUE THREAD

**Issue by wildeyes** [meteor/windows-preview#163]
It works on one machine, doesn't work on an exact same, but another machine.
I am able to `npm i serialport` outside of meteor (including building everything and running a test script connecting to a bot), but if I add `meteor create --package foo` and `Npm.depends({serialport:"1.7.1"})`, then I get a funny error that doesn't say anything.

The first is:
```
failed on node-pre-gyp install --fallback-to-build

=> Errors prevented startup:

   while building package foo
   error: coudln't install npm package
```

**Comment by stubailo** [comment]
I'm closing this repo. Moved: https://github.com/meteor/meteor/issues/4935
