### ISSUE TITLE
Install meteorjs on windows error

### ISSUE THREAD

**Issue by chesteremia** [meteor/windows-preview#168]
I've been trying to install Meteorjs on windows but error occurs. I already tried downloading another installer and restarting my computer but it doesn't work. It always pops 'failed to contact install server. Please try again' then displays the message 'One or more issues caused the setup to fail. Please fix the issues and then retry setup. For more information see the log file.'

Under that it displays '0x80070643. Fatal Error during installation.'

*I also tried running it as an admin and turning off the firewall

**Comment by stubailo** [comment]
I'm closing this repo. Posted the issue on meteor/meteor: https://github.com/meteor/meteor/issues/4932
