### ISSUE TITLE
Error when running after adding urigo:angular

### ISSUE THREAD

**Issue by tcastelli** [meteor/windows-preview#17]
I'm currently developing a project which I started on ubuntu and tried to use it with the last windows preview. Everything was going ok until i tried to install the package urigo:angular (and other related to that one). Seems like the bower package added by angular conflicts with the one from meteor-tools. (obviously tried this on ubuntu and everything is working fine).

the error that i get is:
Error: ENOENT, no such file or directory 'C:\Users\XXXXX\AppData\Local\Temp\meteor-temp-vo3nbd\plugin.bower.os\packages\bower:plugin.js'

tested on win 8.1 64 bits

**Comment by IGx89** [comment]
+1
Just ran into this issue myself :(

**Comment by JeremyBYU** [comment]
I'm having issues with nemo64:bootstrap, might be the same issue.  Are you saying external packages with the ':' character don't seem to work?

**Comment by stubailo** [comment]
I think this is fixed with the new preview release just now: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

Let me know!
