### ISSUE TITLE
meteor under windows 10

### ISSUE THREAD

**Issue by ViniciusAtaide** [meteor/windows-preview#170]
I've installed meteor as the image says under windows 10.
![Meteor Installer](http://i.stack.imgur.com/Ropyu.png)
The meteor command is still not recognized.
There's no .meteor folder in my \users\vinicius folder

**Comment by batjko** [comment]
Did you get a confirmation that the installation actually finished successfully?

If there is no `.meteor` folder, it looks like it failed rather early.

**Comment by ViniciusAtaide** [comment]
I think this is a confirmatino that the installation was finished, but it was instantaneous, the problem is that it doesn't show any error message, so I don't know what to do.

**Comment by stubailo** [comment]
I'm shutting down this repo. Posted this issue to meteor/meteor: https://github.com/meteor/meteor/issues/4931
