### ISSUE TITLE
Meteor Command Fails on Username with Space

### ISSUE THREAD

**Issue by jhprks** [meteor/windows-preview#18]
I just installed windows-preview on my 64bit win7 and entered meteor on a new command prompt window, but it it's giving the following error:

'C:\Users\FirstName' is not recognized as an internal or external command, operable program or batch file.

My username consists of my first name and my last name separated by a space.

It seems like meteor does not take into account the space in the username.

**Comment by shirk3y** [comment]
+1

**Comment by tcastelli** [comment]
+1

**Comment by stubailo** [comment]
Just fixed this in 0.1.1, try it out: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows
