### ISSUE TITLE
Fails to start mongodb if run from a non-admin command prompt

### ISSUE THREAD

**Issue by IGx89** [meteor/windows-preview#19]
If I try to start a meteor app on Windows 8.1 64-bit from a non-admin command prompt, I get the following error message:

    Error: rs.initiate error: exception: Can't take a write lock while out of disk space

I then deleted the .lock file from .meteor\local\db and manually ran mongodb on the created database and got the following error message:

    [FileAllocator] error: failed to allocate new file: .\local.0 size: 67108864
    error: couldn't rename .\_tmp\1419050025028371 to .\local.0 errno:5 Access is denied..

I then did a meteor reset, opened up an admin command prompt, and ran meteor again -- that did the trick, and now that the database is fully created I can run meteor on that project from a regular command prompt. I just have to remember to open up an admin command prompt next time I create a new project and run it for the first time.

**Comment by stubailo** [comment]
Do you have disk space on your computer? I don't get this error on the same Windows version.

**Comment by IGx89** [comment]
Yep, plenty -- was the first thing I checked. Maybe your command prompt was already elevated, or you have UAC disabled? I'll check with the latest version and see if that's fixed it and report back here.

**Comment by IGx89** [comment]
No luck with 0.1.5 either:

```
C:\Users\Matthew\Documents\Meteor\todos>meteor
[[[[[ C:\Users\Matthew\Documents\Meteor\todos ]]]]]

=> Started proxy.

C:\Users\Matthew\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.6\mt-os.w
indows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:173
                                                throw(ex);
                                                      ^
Error: rs.initiate error: exception: Can't take a write lock while out of disk s
pace
    at Error (<anonymous>)
    at initiateReplSetAndWaitForReady (C:\Users\Matthew\AppData\Local\.meteor\pa
ckages\meteor-tool\1.1.0-winr.6\mt-os.windows.x86_32\tools\run-mongo.js:475:17)
    at launchMongo (C:\Users\Matthew\AppData\Local\.meteor\packages\meteor-tool\
1.1.0-winr.6\mt-os.windows.x86_32\tools\run-mongo.js:558:9)
    at [object Object]._.extend._startOrRestart (C:\Users\Matthew\AppData\Local\
.meteor\packages\meteor-tool\1.1.0-winr.6\mt-os.windows.x86_32\tools\run-mongo.j
s:656:19)
    at [object Object]._.extend.start (C:\Users\Matthew\AppData\Local\.meteor\pa
ckages\meteor-tool\1.1.0-winr.6\mt-os.windows.x86_32\tools\run-mongo.js:614:10)
    at C:\Users\Matthew\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.6\
mt-os.windows.x86_32\tools\run-all.js:194:26
C:\Users\Matthew\Documents\Meteor\todos>
```

**Comment by stubailo** [comment]
Weird. I tried running with all combinations of admin on install/run.

**Comment by IGx89** [comment]
Interesting. I'm downloading a Modern.IE Windows VM and going to try it there, to see if I can reproduce it myself on a different Windows computer. That'll also allow me to compare permissions on folders and see if there's anything unique with my setup.

**Comment by stubailo** [comment]
Thanks, that would be really helpful. I'm currently testing on a Windows 7 Modern.IE VM and a Windows 8.1 laptop.

**Comment by stubailo** [comment]
Are you doing anything just creating a mapped or network drive, or using `subst`?

**Comment by IGx89** [comment]
No, just have a standard Documents folder that I created a Meteor folder inside to contain my Meteor projects

**Comment by IGx89** [comment]
It worked on the VM, though the permissions were definitely different. In both cases though, that VM and my computer, the user account that was logged in had full control. Do you know if mongod is running under a different user?

**Comment by stubailo** [comment]
No it's definitely the same user

**Comment by sdarnell** [comment]
@IGx89 Just a thought, but do you have (or have had) mongo running as a service on the machine that was failing?

Another possible thing to consider for diagnosing the issue is to run up sysinternals process monitor to see precisely what the error code is that comes back from the failed lock operation (or possibly some other file system failure).

You also mentioned that the permissions were different - could you clarify?

**Comment by IGx89** [comment]
I made the permissions on the IE VM exactly match mine, so that doesn't look to be the issue either. I'm a bit miffed. If no one else is having this problem, then I'm fine with you guys closing this -- I'll just use the workaround of using an elevated command prompt.
