### ISSUE TITLE
Preview update to 1.0.2

### ISSUE THREAD

**Issue by piffie** [meteor/windows-preview#23]
Hi,
As i believe the 0.10 preview is based on Meteor 1.0.1, Could you make an upgrade to 1.0.2? that would give the development on Windows a huge boost.

And is there something we can help in getting windows support a push?

Thanks

**Comment by Slava** [comment]
We are working hard on the next preview release. The best way you can help right now, is testing on as many Windows machines as possible as soon as we release it :)

Stay tuned

**Comment by piffie** [comment]
And the .10 preview quite often crashes during restarts... should i post the exceptions as issues here?

**Comment by Slava** [comment]
We just released the new preview based off version 1.0.2.
