### ISSUE TITLE
0.27 does not autooverride version.

### ISSUE THREAD

**Issue by piffie** [meteor/windows-preview#25]
when i type meteor it tells me that 1.0.2 is not installed. when i type meteor update the same message comes.
C:\dev\website\meteor>meteor update
Sorry, this project uses Meteor 1.0.2, which is not installed and could not be
downloaded. Please check to make sure that you are online.

**Comment by stubailo** [comment]
0.0.27 introduces the mechanics of running multiple releases. If you are working with a project created with 1.0.2, try `meteor --release WINDOWS-PREVIEW@0.0.27`. I think in the next preview we will need to add some smarter logic about automatically picking the right windows release if the app's Meteor version doesn't exist for Windows.

**Comment by tcastelli** [comment]
+1 (project was not created with 1.0.2 but i did a meteor update on linux and since then i get the previous could not be downloaded error). with the release option i can get through however

**Comment by stubailo** [comment]
Try the new release: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

We have added some workarounds for this issue. In particular, there are two things:

1. `meteor update` with no arguments on Windows now updates to the newest release that is compatible with Windows
2. New Windows previews are also compatible with Mac/Linux and have all of the features of the most recent 1.0.3.1 release, so you can collaborate with friends by both using WINDOWS-PREVIEW@0.1.0
