### ISSUE TITLE
Assertion Failed on Meteor Start

### ISSUE THREAD

**Issue by daemogar** [meteor/windows-preview#26]
I just installed the 0.27 install and tried ```meteor create --example todos``` (does not really matter) and get the following assertion error. Did I miss something in the install that was not mentioned?

![image](https://cloud.githubusercontent.com/assets/3753621/5690076/6ed2a2e6-9843-11e4-8a14-b359f2a603c2.png)

**Comment by stubailo** [comment]
Interesting, I have never seen this error before. Thanks for reporting!

**Comment by daemogar** [comment]
Also, admin mode for cmd did not make a difference.

**Comment by Slava** [comment]
@daemogar do you have any antivirus software running?

**Comment by daemogar** [comment]
I do, but now it seems to be working just fine and have not been able to recreate the problem. Maybe I did not restart after install and that did it.
