### ISSUE TITLE
Meteor Shell won't connect

### ISSUE THREAD

**Issue by emgee3** [meteor/windows-preview#27]
Reproduction:

    meteor create --example leaderboard
    meteor

In new Command Prompt:

    cd \path\to\example\leaderboard
    meteor shell

Returns the following:

    Server unavailable (waiting to reconnect)

I'm running Windows Server 2012 x64, Meteor Windows Preview 0.0.27. I tried disabling the Windows Firewall but no change.

**Comment by Slava** [comment]
Fixed on a branch but not yet released.

**Comment by emgee3** [comment]
Thx @Slava !

**Comment by emgee3** [comment]
I can confirm it works as of Windows Preview 0.0.37

**Comment by stubailo** [comment]
Curious - how did you get 0.0.37? Did you use `meteor update`?

**Comment by emgee3** [comment]
meteor update --release WINDOWS-PREVIEW@0.0.37

I noticed it got pushed earlier today :)

**Comment by stubailo** [comment]
Very cool - good to know meteor update worked for you, we only implemented it very recently :]
