### ISSUE TITLE
Installer not putting meteor in the path

### ISSUE THREAD

**Issue by indcoder** [meteor/windows-preview#28]
First time I run this.....I get that the meteor has been added to the path and I should click any key to continue. After clicking, the installer mentions in the install console that they were some issues during installation; do I want to run the installer again. Once I go ahead with the re-install, everything goes smoothly with no errors being reported[Also no mention about command prompt in the installation console either]. But when I run meteor command in a new command prompt, its not recognizable => meteor was not added to the path. 

OS: Win 7

**Comment by stubailo** [comment]
Do you still have this issue with the new preview? https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

**Comment by Slava** [comment]
The new installer doesn't have this issue. Closing.

**Comment by indcoder** [comment]
@Slava This issue still exists in the current installer\ [9th Feb]
![screenshot 2015-02-12 18 24 37](https://cloud.githubusercontent.com/assets/2099300/6168004/fe5c7b90-b2e6-11e4-8ce8-3e75c1185e83.png)
![screenshot 2015-02-12 18 24 53](https://cloud.githubusercontent.com/assets/2099300/6168006/00462546-b2e7-11e4-99e5-ea21dfc25f50.png)

**Comment by batjko** [comment]
Still happens with version 1.1.0.2.
The installer finished successfully, I open a new command window, type `meteor`, and cmd won't find it.
![image](https://cloud.githubusercontent.com/assets/7287076/8397161/0664b404-1dba-11e5-83a4-3ebcc2ec44e0.png)

**Comment by stubailo** [comment]
Did you restart your computer?

**Comment by batjko** [comment]
@stubailo Why would I have to do that? The Path variable gets re-applied every time a new command window is opened.

Do you mean that Meteor won't add a value to the PATH variable until the computer gets restarted? That would be extremely unnecessary.

**Comment by stubailo** [comment]
@batjko things are a little different in Windows 8+ (it works automatically in Windows 7, I think). It's possible to work around this but unfortunately we haven't had the time to modify our installer to remove the need for a restart.

Does it work once you restart?

**Comment by batjko** [comment]
Ah I see. Well no, didn't restart yet.
I updated the PATH variable manually, opened a command, et voila: off we went.

**Comment by stubailo** [comment]
Great. Thanks for your patience.
