### ISSUE TITLE
Kill Meteor Process on Windows

### ISSUE THREAD

**Issue by KyleMit** [meteor/windows-preview#30]
When I exit the terminal running meteor, the meteor server doesn't automatically close.

Consequently, when I try to restart the app I get the following message:

> Running two copies of Meteor in the same application directory will not work. If something else is using port 3000, you can specify an alternative port with `--port <port>`

So the question is how can I stop meteor and kill the current instance?

There are currently these questions on StackOverflow

* [How to stop Meteor?](http://stackoverflow.com/q/12238382/1366033)
* [Meteor app not showing up](http://stackoverflow.com/q/19372424/1366033)
* [How do I stop all the running meteor servers](http://stackoverflow.com/questions/14907397/how-do-i-stop-all-the-running-meteor-servers)

Some of the solutions include the following (none of which seem to work on Windows)

* Run <kbd>Ctrl</kbd> + <kbd>C</kbd> from terminal
* Open the `Activity Monitor` and select any processes called `node` and click `Quit Process`
* Run the following  
  ``kill -9 `ps ax | grep node | grep meteor | awk '{print $1}'` ``

**Comment by koolaid1551** [comment]
@KyleMit make sure you kill mongod as well with `kill -9 `ps ax | grep node | grep meteor | grep mongod | awk '{print $1}'``

**Comment by KyleMit** [comment]
@koolaid1551, those commands are for unix based command line utilities and won't work on windows

**Comment by koolaid1551** [comment]
@KyleMit You are correct, sorry I got a little confused at first when reading your issue.  I thought maybe you were connect to a linux terminal on windows like I did last night.

Basically I ran into a similar issue where I ssh to a linux vm through vagrant and noticed that <kbd>Ctrl</kbd>+<kbd>C</kbd> did not kill meteor for me, so when i tried ```kill -9 `ps ax | grep node | grep meteor  | awk '{print $1}'````  I realized I still needed to shut down mongo

However when I run the meteor windows preview <kbd>Ctrl</kbd>+<kbd>C</kbd> works for me.  I am on a windows 8.1

I am assuming on windows you could just open the task manager and kill the node and mongod processes or you could use the commands below
```taskkill /f /im mongod.exe```
```taskkill /f /im node.exe```

**Comment by sdarnell** [comment]
I believe the way it is meant to work (or at least used to be) is that the server should detect that the outer process had gone away, and die a clean and tidy death. This may not be immediate, but should be relatively quickly.

**Comment by Slava** [comment]
I couldn't reproduce this. Here is what I did:

- opened cmd.exe
- ran Meteor for an app
- opened Chrome and ensured that localhost:3000 indeed works with the app
- closed cmd.exe
- refreshed the page in Chrome and ensure that the app is dead and gone

Can you please provide me more details to reproduce the issue?

**Comment by KyleMit** [comment]
@Slava, sorry for the delay, this appears to only be occurring in Powershell ISE (not powershell.exe or cmd.exe)

Here are all the steps to reproduce:

```
cd MeteorApps
meteor create ExitTest
cd ExitTest
meteor
```

Try to stop script or exit ... then reopen like this

```
cd MeteorApps
cd ExitTest
meteor
```

Should return error:

Here's a gif of the process in action

![powershell ise][ise]

But its working in [regular powershell][powershell] and the [command prompt][cmd]

If Powershell ISE isn't fully supported, that's fine too.

[album]: http://imgur.com/a/FiQqm
[ise]: http://i.imgur.com/9XwpzXq.gif
[powershell]: http://i.imgur.com/FZs0uKL.gif
[cmd]: http://i.imgur.com/FG7kTgX.gif

**Comment by Slava** [comment]
@KyleMit thanks for getting back to us!

I will be honest, PowerShell ISE has other issues too (like treating any stderr output as a critical error dealing terrible terrible damage).

**Comment by stubailo** [comment]
I think we are likely to document PowerShell ISE as not being supported for the initial release (but regular PowerShell will be)

**Comment by KyleMit** [comment]
@stubailo / @Slava I think not supporting PowerShell ISE at this point is a great idea.  Adding supported / unsupported terminals to the Windows Docs could save future travelers some confusion.

**Comment by stubailo** [comment]
@KyleMit Added it to the list of "known limitations".
