### ISSUE TITLE
Installer throwing exception of Access denied

### ISSUE THREAD

**Issue by indcoder** [meteor/windows-preview#31]
![screenshot 2015-01-14 15 46 55](https://cloud.githubusercontent.com/assets/2099300/5737299/3b8b8a36-9c05-11e4-9bc5-70ae8e649efe.png)

The installer is throwing an uncaught exception. Is there some log thats installer spits out so that we can see at what step it is tripping?

May not apply here....but I'm also having an issue with the Atom editor that cannot be installed on a comp with a space in the profile name

OS : Win 7

**Comment by stubailo** [comment]
Yeah, I think there are other issues saying that the installer might not be happy about spaces in file names.

**Comment by brycekmartin** [comment]
Try right clicking on the .exe and going to Properties.  In there go to Compatibility.  At the bottom there is a section called Privilege Level.  Make sure "Run this program as administrator" is checked.  Hit Apply and Ok.  Then, right click on the .exe and tell it to Run as Administrator.  

That worked for me when I was getting this error.

**Comment by indcoder** [comment]
![meteorinstaller_wadminprivi](https://cloud.githubusercontent.com/assets/2099300/5759340/24a55a1a-9cf3-11e4-84fe-1012c8e8f25b.png)
@brycekmartin Tried that....same result in the sense that it fails to install successfully but there are fewer exception errors with Admin provileges

**Comment by ManuelDeLeon** [comment]
Same error here =(
No spaces in my path
Win 7 x64

**Comment by ilanah** [comment]
I get:

C:\temp>install-meteor-0.0.27.exe
Downloading initial Meteor files...
07 ###########-------------------------------
Unhandled Exception:

C:\temp>

I don't even see any exception details.
Running on Win 7 Enterprise, behind company proxy.
did Run As administrator.

**Comment by ManuelDeLeon** [comment]
I don't get this error with the latest installer: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

**Comment by stubailo** [comment]
Interesting, the installer has not changed at all :]

We are working on a new installer rewritten completely from scratch to avoid some of these errors.

**Comment by brycekmartin** [comment]
I got it to install on one computer after about 7 tries.  My laptop, however, still getting this error and I've tried everything that I tried on my desktop machine.  Can't wait for a new installer :)

Great job, keep up the good work.  It is really coming around.

**Comment by dandv** [comment]
@ManuelDeLeon: was this the first time you installed? I've found that I get the exception reliably, whether the installer has Admini privileged or not, and what fixes it is to delete the `%USERPROFILE%\AppData\Local\.meteor` folder. That was the only thing I did to fix the exception; [no registry changes](https://github.com/meteor/windows-preview/issues/2#issuecomment-72339156) actually.

**Comment by sdarnell** [comment]
If nothing else, I suspect we should add a try catch that prints the directory name. And preferably also retry the deletion (with a small delay in between retries).

I suspect it is either windows search indexing the dir or a virus scanner. Even the command line delete can have issues and need to be run multiple times.

**Comment by indcoder** [comment]
This error is still there in the latest build of Feb 9th, 2015
![image](https://cloud.githubusercontent.com/assets/2099300/6151590/e15dcd00-b23c-11e4-9157-afa8dd3f7222.png)

**Comment by Slava** [comment]
We have a new installer. Closing this.

**Comment by brycekmartin** [comment]
Any idea when that release will drop with the new installer?

**Comment by Slava** [comment]
We are actively working on it. Expected to get it into a releasable state
this week.
