### ISSUE TITLE
Excpetion from meteor create

### ISSUE THREAD

**Issue by brycekmartin** [meteor/windows-preview#32]
I got the following exception when trying to do a meteor create.
![meteorerror](https://cloud.githubusercontent.com/assets/682042/5746966/1c160fc6-9c02-11e4-89de-441cd33db2f3.png)

**Comment by Slava** [comment]
@brycekmartin thanks for the report, what version are you running?

**Comment by brycekmartin** [comment]
Windows 7 x64, sorry I forgot to put that detail.

**Comment by Slava** [comment]
I meant the version of meteor ;)

oh, I see, our code assumes that "C:\" is always capitalized, which is not the case. A workaround for you would be changing your path to "C:\src\meteorapps" (capitalized C), will fix it for the future releases.

**Comment by brycekmartin** [comment]
hahaha.... ohh... 0.0.27

**Comment by brycekmartin** [comment]
Hmmm ok.  Interesting.  Well I changed the path and the create is running right now.  The real test will be if mongo works properly for me.

**Comment by Slava** [comment]
should be fixed in https://github.com/meteor/meteor/commit/e97c2dd164bc7ce0bcd392c92381ee8ea98fd305

**Comment by stubailo** [comment]
Try the new release: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

This should be fixed now.
