### ISSUE TITLE
Server restarts when unused local package is modified

### ISSUE THREAD

**Issue by emgee3** [meteor/windows-preview#33]
Steps to reproduce:
 
* `meteor create test-app`
* `cd test-app`
* `mkdir packages`
* `meteor create --package local-package`

At this point the server restarts. This matches Meteor behaviour in OS X. However, making any modification in `test-app\local-package` triggers a time-consuming application rebuild and server restart, despite the package not actually being added to the project (not listed in `.meteor\packages`)

This is when running Meteor WINDOWS-PREVIEW@0.0.27 or WINDOWS-PREVIEW@0.0.37 on Windows Server 2012 R2 x64.

**Comment by stubailo** [comment]
Hi, in my attempted reproduction the server restarts if the `package.js` in the local package is edited, and doesn't restart if a different file is edited. This matches the behavior of the Mac version, so I'm going to say this not a bug.
