### ISSUE TITLE
Mongo lock not removed when updating meteor

### ISSUE THREAD

**Issue by emgee3** [meteor/windows-preview#34]
Steps to reproduce:

First cmd.exe:

* `meteor create test-app`
* `cd test-app`
* `meteor`

Second cmd.exe:

* `cd test-app`
* `meteor update --release WINDOWS-PREVIEW@0.0.37`

Meteor will list the following:

    => App running at: http://localhost:3000/
    Your app has been updated to WINDOWS-PREVIEW@0.0.37 from
    WINDOWS-PREVIEW@0.0.27. Restart meteor to use the new release.

However, when running `meteor` you receive the following error:

    => Started proxy.
    Unexpected mongo exit code 100. Restarting.
    Unexpected mongo exit code 100. Restarting.
    Unexpected mongo exit code 100. Restarting.
    Can't start Mongo server.
    MongoDB had an unspecified uncaught exception.
    This can be caused by MongoDB being unable to write to a local database.
    Check that you have permissions to write to .meteor/local. MongoDB does
    not support filesystems like NFS that do not allow file locking.

Removing `.meteor\local\db\mongod.lock` handles the error.

Running Meteor on Windows Server 2012 R2 x64.

**Comment by funkybunky** [comment]
I receive the same error.
Using v 0.1.1, running on W 7 Pro 64
steps to reproduce:
-  meteor create --example todos
-  cd todos
-  meteor
then I just changed the first char of the title-tag in head.html in client/templates
also, removing the mondod.lock file solved the error

**Comment by MyMate** [comment]
I have added the following 3 lines to my meteor.bat file

@echo Cleaning up MongoDB
@echo off
del %CD%\.meteor\local\db\mongod.lock

This cleans up the lock every time you start meteor
