### ISSUE TITLE
"System.Configuration" error upon running install-meteor-0.0.27.exe

### ISSUE THREAD

**Issue by ayal** [meteor/windows-preview#35]
here is there error message:

ERROR: A problem occurred while downloading the bootstrap package.

If this persists, you can download it manually from:
  https://warehouse.meteor.com/windows/bootstrap/meteor-bootstrap-os.windows.x86
_32-0.0.27.tar.gz
and put it in the same directory as LaunchMeteor.exe and run:
  LaunchMeteor.exe -downloaded

Here are some details of the error:
Unexpected exception: System.Configuration.ConfigurationErrorsException: Configu
ration system failed to initialize ---> System.Configuration.ConfigurationErrors
Exception: Unrecognized configuration section system.serviceModel. (F:\Windows\M
icrosoft.NET\Framework\v2.0.50727\Config\machine.config line 148)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignor
eLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(Configurat
ionSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey
)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey
)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(S
tring sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Intern
al.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(String sect
ionName)
   at System.Net.Configuration.DefaultProxySectionInternal.GetSection()
   at System.Net.WebRequest.get_InternalDefaultWebProxy()
   at System.Net.WebClient.get_Proxy()
   at LaunchMeteor.Program.DownloadBoostrapFile()
   at LaunchMeteor.Program.BootstrapWarehouse(String warehouse)
   at LaunchMeteor.Program.Main(String[] args)

Please press any key to exit.

**Comment by sdarnell** [comment]
@ayal Please could you give some details of which version of Windows you have, and which versions of .Net you think are installed?

From the error details, it looks as if you somehow have got some confused .Net configuration file settings. Specifically, I think the "system.serviceModel" section in the machine.config file is a .net 3.0 WCF feature, but for it not to be recognised, it suggests that the runtime that is being used is a pure 2.0 (without 3/3.5).

For reference, here's the documentation on: system.serviceModel : https://msdn.microsoft.com/en-us/library/ms731354(v=vs.85).aspx

Another possibility is that you have added the system.serviceModel to your machine.config file for some reason in the past (e.g. if you have some WCF services that need some mappings).

As for work-arounds, you could probably remove or comment out that section from the config file temporarily, and then after that has completed it should be OK.

Another possibility is to add a config file 'InstallMeteor.exe.config' in the same directory as the InstallMeteor.exe file, and force a 4.0 or 4.5 runtime (whichever you have installed).

See http://stackoverflow.com/questions/12612166/how-to-force-net-3-5-application-run-on-net-4-5-runtime

I think the config file should look like this:
```
<configuration>
   <startup>
      <supportedRuntime version="v4.5"/>
   </startup>
</configuration>
``` 

More info about supportedRuntime : https://msdn.microsoft.com/en-us/library/w4atty68(v=vs.110).aspx

**Comment by stubailo** [comment]
Hi, we just released an initial version of the brand new completely rebuilt installer.

Please try it and see if you still get this issue: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

**Comment by ayal** [comment]
this worked almost 100% smoothly - 
after the installer finished I ran "meteor" in a new cmd window and it didn't recognize it, I went to look at the environment variables and saw the "...\AppData\Local\.meteor\" in the PATH of the current user context, I don't know why that didn't work. When I appended this value to the global PATH it worked.

I went on to run the server that complained about 
"This project uses METEOR@1.0.1, which isn't available on Windows" which I didn't quite understand if it's because it's not the latest version of meteor or it just needs a different version. Also I didn't feel safe running the update on my master branch.. should one version of the code play nice on both linux and windows? Or should I create a different "windows" branch and merge chunks of code from there..?

After running the update the meteor server ran smoothly.

**Comment by sdarnell** [comment]
There should be an extra slash between Local and  .meteor

**Comment by stubailo** [comment]
@sdarnell I think this is a markdown formatting bug

**Comment by stubailo** [comment]
@ayal currently if you want to use the same project on Windows, Mac, and Linux, the only option is to use one of the preview releases on all platforms. When the first official release for Windows comes out, this won't be a problem.

Unfortunately, `METEOR@1.0.1` will never be supported on windows - you will have to upgrade your app to `METEOR@1.1.0` (when it is released) to run it on all platforms.
