### ISSUE TITLE
Meteor exits

### ISSUE THREAD

**Issue by doleksy1** [meteor/windows-preview#36]
Hello,

Meteor 0.0.8 worked fine but now I updated (deleted .meteor from AppData and installed a fresh copy) it  to 0.0.27 and it won't start anymore - Meteor exits after building the application and does not throw any errors.

Win 8.1 x64

![meteor](https://cloud.githubusercontent.com/assets/5719513/5799413/6b416586-9fd2-11e4-9a4b-f4be699bbb0d.PNG)

**Comment by stubailo** [comment]
What version of Windows are you running?

**Comment by doleksy1** [comment]
Win 8.1 x64

**Comment by stubailo** [comment]
Try the new release, 0.1.0: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

Let me know if this still happens.

**Comment by doleksy1** [comment]
builds the application and quits :/

**Comment by pajenkin** [comment]
I have the same bug. It seems to be  a problem with Mongo and/or updated packages. Running Win   8 x64 with version 1.1 and 1.0. Below are screenshots.

![image](https://cloud.githubusercontent.com/assets/5466101/5881518/625f05aa-a30f-11e4-8a8e-e13ee7cf5861.png)

The solved problems on StackOverflow (
http://stackoverflow.com/questions/15610385/meteor-unexpected-mongo-exit-code-100
http://stackoverflow.com/questions/25102414/unexpected-mongo-exit-code-100-restarting
) are not working with this release.

I also am getting these errors when looking at the packages:

![image](https://cloud.githubusercontent.com/assets/5466101/5881535/7f1378a2-a30f-11e4-9bca-409edcb85e6a.png)

I hope this may help. Not sure if it does or if you have any idea how to run it.

**Comment by doleksy1** [comment]
the mongodb fix works for me, just gotta do it before each launch (mongod.lock should be removed automatically but it's not because of the appcrash...) my output from meteor -v is similar, it  stops after/while downloading packages
![meteor bug](https://cloud.githubusercontent.com/assets/5719513/5898578/1721f734-a551-11e4-91a1-8fe8c7ea2df3.JPG)

**Comment by doleksy1** [comment]
any ideas?

**Comment by Slava** [comment]
@doleksy1  We recently discovered a bug in our code: the stderr would not be flushed when the process crashes. Please try the latest version of 0.1.5 where this bug is fixed. You would probably get a better error message that is worth a separate issue.

**Comment by Slava** [comment]
I am closing this issue as the actionable step was already taken. With the new releases we flush the output correctly, so you would get a better error message.

**Comment by doleksy1** [comment]
I installed 0.1.6 but the only difference I see is that Meteor quits at "Starting app". When I run "meteor -v", i get following: 

![meteor2](https://cloud.githubusercontent.com/assets/5719513/6077680/acc42c0a-adf1-11e4-8222-5d7f8752b089.JPG)

**Comment by doleksy1** [comment]
i found a fix for this one :) 

Meteor works in compatibility mode ("set __COMPAT_LAYER=WIN7RTM" does the magic) !

@pajenkin can you confirm?
