### ISSUE TITLE
Error when creating ?

### ISSUE THREAD

**Issue by daveit** [meteor/windows-preview#38]
I get the error below when running meteor create todo - to test the latest installation
I'm on Windows-7 Pro
I manually deleted the old folder and ran the 0.1.1 release (showing 2 hours ago)
regards, Dave

```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
C:\meteor>meteor create todo

C:\Users\daveport\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\dev_bun
dle\lib\node_modules\fibers\future.js:173
                                                throw(ex);
                                                      ^
TypeError: Cannot use 'in' operator to search for 'track' in null
    at C:\Users\daveport\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\
dev_bundle\lib\node_modules\underscore\underscore.js:834:18
    at Array.forEach (native)
    at _.each._.forEach (C:\Users\daveport\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-
os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at Function._.pick (C:\Users\daveport\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-o
s.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:833:5)
    at [object Object]._.extend.getDefaultReleaseVersion (C:\Users\daveport\AppData\Local\.meteor\pack
ages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\catalog-remote.js:849:14)
    at Object.release.latestKnown (C:\Users\daveport\AppData\Local\.meteor\packages\meteor-tool\1.1.0-
winr.0\mt-os.windows.x86_32\tools\release.js:185:41)
    at C:\Users\daveport\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\
tools\main.js:833:29
C:\meteor>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

**Comment by stubailo** [comment]
This path is interesting: `C:\Users\daveport\AppData\Local.meteor`

**Comment by stubailo** [comment]
What Windows version are you on?

**Comment by daveit** [comment]
Windows-7 Pro, 64 bit
If I type Path, the meteor part is correct - and on the end of string.
...;C:\Users\daveport\AppData\Local\.meteor

**Comment by daveit** [comment]
Further info.
I installed 0.1.1 on another Windows-7 Pro machine and it worked fine!
(It also had a previous version on, which I manually removed!)

So I went back to my first machine - un-installed - removed the meteor entry in the path, restarted Windows - Re-installed, but exactly the same problem!
Most odd!
Back to my Mac until this is sorted :)
Cheers, Dave

**Comment by stubailo** [comment]
Interesting - any ideas what is different between the two machines?

**Comment by daveit** [comment]
No idea at this stage - will have another look at it over the weekend!
rgds, Dave

**Comment by tnedich** [comment]
I have installed   0.1.1 on Windows 7 Ultimate...same problem as @daveit

**Comment by daveit** [comment]
I revisited this following the 0.1.5 release.
I have a second profile on the W7 PC that has the issue - so I switched to that profile and the install works and I can create a project...
So not sure if that helps :)
Dave

**Comment by stubailo** [comment]
So you're saying the issue was fixed for you?

**Comment by daveit** [comment]
Well I know it does not make much sense!
But my main account (profile) on my machine nothing has changed - same error as initially reported with any command using meteor.bat
But when I login to the other profile it all works fine!
I have no idea what could be different - the path for all users is the same, and the user path gets appended to that default path!
Regards, Dave

**Comment by stubailo** [comment]
I'm going to close this for now, it might be a result of some old state left over from a previous install.

**Comment by wujekbogdan** [comment]
Same issue here
```
TypeError: Cannot use 'in' operator to search for 'track' in null
    at C:\Users\UserName\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:834:18
    at Array.forEach (native)
    at _.each._.forEach (C:\Users\UserName\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at Function._.pick (C:\Users\UserName\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.7\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:833:5)
    at [object Object]._.extend.getDefaultReleaseVersion (C:\Users\UserName\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.7\mt-os.windows.x86_32\tools\catalog-remote.js:849:14)
    at Object.release.latestKnown (C:\Users\UserName\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.7\mt-os.windows.x86_32\tools\release.js:185:41) at C:\Users\UserName\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.7\mt-os.windows.x86_32\tools\main.js:835:29
```

I think it might be related to the previous Meteor install. As far i remember i tried an unofficial meteor port from win.meteor.com. Before installing the official port I've removed %LOCALAPPDATA%/.meteor and %USERPROFILE%/.meteor directories.

Is there anything else that should be removed?

**Comment by coostendorp** [comment]
Same issue here, I fixed it.
I had previous installs as well, but I'm not sure if that makes a difference.

Problem: The meteor installation is looking for packages db in (not existing there): 
C:\Users\UserName\.meteor\package-metadata\v2.0.1\packages.data.db

While the installer put the packages db here:
C:\Users\UserName\AppData\Local\.meteor\package-metadata\v2.0.1\packages.data.db

I just copied the .db for now, and that seems to resolve it. My guess is that there is still a reference to %USERPROFILE% in the code somewhere that needs to be changed to %LOCALAPPDATA%.

**Comment by daveit** [comment]
I got excited when I read this, but it does not work for me Casper :(
The files in the folder C:\Users\UserName\.meteor\package-metadata\v2.0.1
get created the first time meteor is run - so this is not working for me

**Comment by coostendorp** [comment]
@daveit I deleted the existing packages.data.db* files first, then hardlinked the ones from AppData\Local.

**Comment by daveit** [comment]
Thanks Casper,
Can you be more detailed for me please?
In the Local folder there is only one file (much larger that the one in UserName)
But there are three files in the UserName folder (.db, .db-wal & .db-shm )
Thanks, Dave

**Comment by coostendorp** [comment]
@daveit This is the dirty side of my fix: the db-wal and db-shm are temporary files used by SQLite. I am guessing its "ok" or actually better not to link those. But, theoretically, bad stuff could happen. (so pls dont blame me if weird stuff happens, this is just a stopgap i found to get it working for now )

I just deleted all the files in C:\Users\UserName\\.meteor\package-metadata\v2.0.1\ before hardlinking only the packages.data.db

**Comment by daveit** [comment]
OK, I tried that, but still no joy!
By hardlinking, I assume you mean add  C:\Users\UserName.meteor\package-metadata\v2.0.1 to the path ?
Maybe my situation is different - on this PC, I can get it working by switching to a different profile (user), as discussed earlier in the thread)
By the way, this is no big issue for me, it is just out of interest - I have a Mac Book pro that I do my Meteor work on!
Cheers, Dave

**Comment by coostendorp** [comment]
@daveit Nope, I hardlink just like in *nix, using the ln command from http://gnuwin32.sourceforge.net/packages/coreutils.htm

cd C:\Users\UserName\\.meteor\package-metadata\v2.0.1
ln C:\Users\UserName\AppData\Local\\.meteor\package-metadata\v2.0.1\packages.data.db .

Btw, just copying the .db file will also work, but updating the packages/meteor will cause more weirdness  then i guess. At least it will make it work too.

**Comment by coostendorp** [comment]
Ok, much cleaner fix:

Add a User Environment Variable as follows:
METEOR_WAREHOUSE_DIR=C:\Users\UserName\AppData\Local\\.meteor

**Comment by daveit** [comment]
Yep, that got it working!
(METEOR_WAREHOUSE_DIR)
Thanks so much...
Dave

**Comment by stubailo** [comment]
Oh, thanks for finding the issue. We should correctly use `HOME` on linux/mac and `LOCALAPPDATA` on windows. Instead, we assumed that people on Windows wouldn't have `HOME` set.

**Comment by avital** [comment]
Just got this after running the installer from latest devel, so we haven't fixed the problem.

**Comment by stubailo** [comment]
@avital were you using Meteor from the default install location, or somewhere else?

**Comment by avital** [comment]
Oh wait, I was running an old release.
