### ISSUE TITLE
TypeError: Object #<Object> has no method 'getDefaultReleaseVersion'

### ISSUE THREAD

**Issue by ManuelDeLeon** [meteor/windows-preview#39]
I tried running one of my apps (https://github.com/ManuelDeLeon/viewmodel-docs) but got the following error:

```
C:\Temp\test\viewmodel-docs>meteor

C:\Users\Manuel\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:173
                                                throw(ex);
                                                      ^
TypeError: Object #<Object> has no method 'getDefaultReleaseVersion'
    at C:\Users\Manuel\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\main.js:416:39
    at [object Object]._.extend.withProgressDisplayVisible (C:\Users\Manuel\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\console.js:612:14)
    at springboard (C:\Users\Manuel\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\main.js:402:11)
    at C:\Users\Manuel\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\main.js:992:5

C:\Temp\test\viewmodel-docs>
```

**Comment by esgy** [comment]
Same here. I tried to follow a tutorial from here: http://meteortuts.com/category/startwithaboilerplate

1. Cloned git clone https://github.com/Differential/meteor-boilerplate.git testapp
2. cd testapp
3. meteor update
4. Got the error 

---
It works like this with a new app:
1. meteor create newapp
2. cd newapp
3. meteor update

**Comment by esgy** [comment]
UPDATE:

In the clone repository I updated: .meteor/release
and replaced the value with: WINDOWS-PREVIEW@0.1.1

Then meteor update works. 
It says though that there is already on the current version so it might just update the packages and not meteor... ?

**Comment by stubailo** [comment]
OK, I think I might have broken using `meteor update` to go from the `METEOR` release track to `WINDOWS-PREVIEW`.

**Comment by stubailo** [comment]
I think this is fixed in the newest relese.
