### ISSUE TITLE
TypeError: Object # has no method 'getDefaultReleaseVersion'

### ISSUE THREAD

**Issue by Slava** [meteor/windows-preview#41]
Reported by @dcsan at https://github.com/meteor/meteor/issues/3549

```
OUTPUT:

C:\Users\jfarmer\Documents\GitHub\WelcomeToWisconsin\metapp>meteor run --settings "config/config.json"

C:\Users\jfarmer\AppData\Local.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:173
throw(ex);
^
TypeError: Object # has no method 'getDefaultReleaseVersion'
at C:\Users\jfarmer\AppData\Local.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\main.js:416:39
at [object Object]._.extend.withProgressDisplayVisible (C:\Users\jfarmer\AppData\Local.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\console.js:612:14)
at springboard (C:\Users\jfarmer\AppData\Local.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\main.js:402:11)

at C:\Users\jfarmer\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\main.js:992:5
```

**Comment by Slava** [comment]
This is a "undefined is not a function" style bug but the real issue here is - the project @dcsan tried to run was pinned to a release that is not available on Windows (because we didn't release an official version of Windows yet!). An obvious workaround would be to upgrade to a preview release track:

    meteor update --release WINDOWS-PREVIEW@0.1.1

**Comment by Slava** [comment]
Also see #3 at https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows#things-to-try

**Comment by dcsan** [comment]
yeah that sounds right. he was trying to run my code from an OsX dev'ved app.

**Comment by landmaxcanada** [comment]
1) I just had this same issue on Azure Windows 2012 VM.
2) ran  -  meteor update --release WINDOWS-PREVIEW@0.1.1
3) all is working now!

Good job Meteor Team!

**Comment by stubailo** [comment]
There is now a nice message in the case that an app uses a release that is not available on Windows, so hopefully this won't happen anymore.
