### ISSUE TITLE
EBUSY error occurs when interrupting `test-packages` with Ctrl+C

### ISSUE THREAD

**Issue by yeputons** [meteor/windows-preview#42]
Steps to reproduce (on WINDOWS-PREVIEW@0.1.1):

1. `meteor create --package test`
2. `cd test`
3. `meteor test-packages ./`
4. Wait till it's up and running
5. Press Ctrl+C
6. Node and mongo exit, as expected, but long <a href="http://pastebin.com/7rg9p0ga">error message</a> is displayed: `Error: EBUSY, resource busy or locked '...\.meteor\local\build\programs\server`

My antivirus software was disabled during testing.

**Comment by Slava** [comment]
Looks like the error means "I couldn't remove temporary directory". We should look into it, otherwise you will have piles of temp files accumulating.

**Comment by stubailo** [comment]
Hi, I just tried to repro this on my machine and couldn't following those directions.

What Windows version are you running?

**Comment by yeputons** [comment]
@stubailo Windows 7 Professional SP1 x64 (version 6.1.7601), all updates are installed. It's attached to Windows domain, but user's folders are completely local.
