### ISSUE TITLE
Neither `win.meteor.com` nor official installation guide mention this preview

### ISSUE THREAD

**Issue by yeputons** [meteor/windows-preview#43]
<a href="http://win.meteor.com">win.meteor.com</a> have information about Stephen Darnell's version only (which, as far as I can see, is now used a base for this version), not a word about this repository.

**Comment by stubailo** [comment]
This repository is a preview not meant to be widely used yet, we would like to make some improvements and bug fixes before releasing to a wider audience. We will definitely mention it on that website once we think we have something users will be happy with.

**Comment by sdarnell** [comment]
FYI I have added a note on https://github.com/sdarnell/meteor/wiki/Windows but to update win.meteor.com you'll need @gabrielhpugliese

**Comment by gabrielhpugliese** [comment]
What exactly should I update @sdarnell ? Just a link to your wiki?

**Comment by sdarnell** [comment]
I had previously removed the link to the MSI based installer (0.6.4.1) but I see the app hasn't been updated. However the key thing here is whether or not to refer to the official windows preview that is currently in progress. I think Sashko and Slava would prefer to wait a little. (see discussion in  https://github.com/sdarnell/meteor/issues/67).

But for future reference I wanted to clarify that I didn't have the rights to update win.meteor,com.

**Comment by gabrielhpugliese** [comment]
Stephen, I can give you permission if you want/need.

**Comment by dalerka** [comment]
I was just going to ask someone at MDG to update the **http://win.meteor.com** because **many articles direct to that address** *for windows version* of Meteor. 
I think that page should be updated as soon as possible, because on one hand the MDG is asking people to **try and help test the preview version for Windows** and on the other hand the people who would like to **try** Meteor end up being misguided to the very old release.

**Comment by Slava** [comment]
I think the time has come, we should start replacing win.meteor.com with something that either forwards to the latest installer (aka install.meteor.com/windows) or a page that has a big download button.

**Comment by avital** [comment]
As of Meteor 1.1, http://win.meteor.com points to the official installer.
