### ISSUE TITLE
Running on Windows Azure 2012 R2 Virtual Machine - Port Issues?

### ISSUE THREAD

**Issue by landmaxcanada** [meteor/windows-preview#44]
Hi, I remote desktop into 2012 VM and the install and running of Meteor on localhost:3000 worked fine. Tried to access via IP xxx.xxx.xxx:3000 after setting up the port on the VM and the request times out. 

Also, I tried to get a simple Node.js server running on xxx.xxx.xxx:3000 and failed. So it appears that the issue is with the configuration of the Azure Virtual Machine Windows Server 2012 R2.  When I Google the issue, the answer seems to always involve IIS and IISnode. I want Node or Meteor to run separate from any IIS that may or may not be also running.

Can anyone help set-up the Azure Windows VM to run Meteor? I already did the obvious of setting the private and public port to 3000.

Just to be clear, both Node.js and Meteor.js run fine on localhost:3000 (from RDP session). But I can't reach them from outside browser via IP and Port.

Microsoft Azure is very nice and it would be great to host Meteor on it!

**Comment by yeputons** [comment]
@landmaxcanada I guess you have some firewall configuration issues. On Windows Server 2008 R2 it's located under Start -> Administrative tools -> Windows firewall with advanced security. Allow incoming connections to port 3000 here.

**Comment by landmaxcanada** [comment]
One of the reasons to put this question to the Meteor community is to "suggest" that if demos are created, Windows Azure 2012 R2  would be a useful platform.

**Comment by Slava** [comment]
Sorry, we don't support Azure as a deployment platform officially. If you figure out a way to do it or it just works out of the box - great! Currently people working on the Windows port a knee-deep in dealing with Windows quirks and setting up the release process.

As @yeputons says, opening a port on your VM is a purely ops task.

**Comment by landmaxcanada** [comment]
Hi, I did get a demo working on Azure thanks to "yeputons" above with the "open port in firewall". Yes sometimes it is the most obvious that we forget to check.

Regarding the "Windows Quirks", putting a optimized image on Azure or a Docker container may help get everyone started at the same base configuration.   Azure has lots of free test options, or apply for Bizspark and get $1800/year for three years. Nice!

**Comment by Slava** [comment]
@landmaxcanada I no longer understand what is your request in this ticket named "Port Issues?". We do not plan putting out "an optimized Azure container". Right now the word "Azure" really is not present in any our plans or intentions for the future.

Docker containers are only for linux.

**Comment by bjimdar** [comment]
@landmaxcanada For what it's worth, I'm hosting a Meteor project on Azure using their stock Ubuntu 14 VM image. Setup and deployment with Meteor-up is really easy and Azure's VM extensions for Linux makes administration easy as well.

If there's some reason you still want to use Cloud services, previously I had a deployment process going using de-meteor and following the Nodejs-for-Azure procedure. I've had both solutions working great for a while without using the meteor-windows branch. 

Ping me if you want and I can send you my deployment procedure doc.

https://github.com/arunoda/meteor-up
https://github.com/onmodulus/demeteorizer

**Comment by landmaxcanada** [comment]
Thanks bjimdar, don't know how to "ping you".

I thought of the de-meteorize option, but it just does not sound like a good idea. Also tried a Ubuntu VM, but then I have to learn Linux ;)  I like my WIndows Servers ;)
