### ISSUE TITLE
Error: EPERM, unlink '.meteor\local\.build801981.build\programs\server\node_modules\adm-zip''

### ISSUE THREAD

**Issue by fredrikekelund** [meteor/windows-preview#46]
I got the following error after using the Windows preview for an hour or so:

```bash
C:\Git\MeteorDataTool\meteor>meteor
[[[[[ C:\Git\MeteorDataTool\meteor ]]]]]

=> Started proxy.

C:\Users\Fredrik\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.w
indows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:206
                                                throw(ex);
                                                      ^
Error: EPERM, unlink 'C:\Git\MeteorDataTool\meteor\.meteor\local\.build801981.bu
ild\programs\server\node_modules\adm-zip'
    at Object.Future.wait (C:\Users\Fredrik\AppData\Local\.meteor\packages\meteo
r-tool\1.1.0-winr.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\futu
re.js:326:15)
    at Object.files.rm_recursive (C:\Users\Fredrik\AppData\Local\.meteor\package
s\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\files.js:262:9)
    at [object Object]._.extend.abort (C:\Users\Fredrik\AppData\Local\.meteor\pa
ckages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\builder.js:491:11)
    at writeSiteArchive (C:\Users\Fredrik\AppData\Local\.meteor\packages\meteor-
tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\bundler.js:1894:13)
    at C:\Users\Fredrik\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\
mt-os.windows.x86_32\tools\bundler.js:2097:20
    at C:\Users\Fredrik\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\
mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\Fredrik\AppData\Local\.meteo
r\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:
115:14)
    at C:\Users\Fredrik\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\
mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\Fredrik\AppData\Local\.meteo
r\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:
115:14)
    at C:\Users\Fredrik\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\
mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\Fredrik\AppData\Local\.meteo
r\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:
115:14)
    at C:\Users\Fredrik\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\
mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\Fredrik\AppData\Local\.meteo
r\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\fiber-helpers.js:
115:14)
    at Object.capture (C:\Users\Fredrik\AppData\Local\.meteor\packages\meteor-to
ol\1.1.0-winr.0\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at Object.exports.bundle (C:\Users\Fredrik\AppData\Local\.meteor\packages\me
teor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\bundler.js:1984:31)
    at bundleApp (C:\Users\Fredrik\AppData\Local\.meteor\packages\meteor-tool\1.
1.0-winr.0\mt-os.windows.x86_32\tools\run-app.js:521:34)
    at [object Object]._.extend._runOnce (C:\Users\Fredrik\AppData\Local\.meteor
\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\run-app.js:557:35)

    at [object Object]._.extend._fiber (C:\Users\Fredrik\AppData\Local\.meteor\p
ackages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\run-app.js:792:28)
    at C:\Users\Fredrik\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\
mt-os.windows.x86_32\tools\run-app.js:379:12
    - - - - -
C:\Git\MeteorDataTool\meteor>
```

Removing `.meteor\local\.build801981.build` fixes the problem, so it doesn't seem to be a grave issue, but thought I'd report it to let you guys be the judges.

**Comment by stubailo** [comment]
Thanks for reporting!

**Comment by stubailo** [comment]
I haven't seen this before or since, so I'm going to close it for now. @fredrikekelund have you encountered this error again?

**Comment by fredrikekelund** [comment]
Nope, haven't ecountered it again. 0.1.8 has actually been running really well, still the occasional crash, but so much better and more performant than previously

**Comment by stubailo** [comment]
Are you using it regularly? If so, I'm glad it is stable enough to build real apps!

**Comment by fredrikekelund** [comment]
Unfortunately not regularly enough to vouch for the current version, but our company will be using Meteor to build the next generation of our software

**Comment by vicktor3** [comment]
I saw this error the first time I started up my meteor app with Meteor 1.1. Simply re-running meteor solved the problem for me. Could the error have something to do with Windows file permissions in the AppData directory?

**Comment by cgudrian** [comment]
I'm currently seeing this error on a regular basis. I'm using Meteor 1.1.0.2 on Windows 7. Perhaps it's virus scanner temporarily locking a folder.

**Comment by shrimpster00** [comment]
I get the same error often, on Meteor 1.1 on Windows 8, and it is very inconvenient. It appears that it means that MongoDB is having issues starting.
As vicktor3 commented, re-running Meteor can allow it to run again, but that is not always the case.

**Comment by wildeyes** [comment]
same issue here +1

**Comment by EvilJohnny** [comment]
Same problem here... Meteor 1.1.02 on Windows 8.1 x64
Same thing as @shrimpster00, re-running Meteor can work, but not always. Also, the file you should "unlink" usually changes with each crash.

**Comment by SollyTaylor** [comment]
I encountered such problem when simple copy the development folder from Windwos 7 to Mac. I've tried : meteor 'reset', 'meteor build', 'meteor update' and simple 'meteor'. The errors persisted.

**Comment by SollyTaylor** [comment]
I resolved such problem by recreate the meteor project and copy all folders but '.meteor' folder of files into the new directory. Readd all dependent packages into the project. meteor it again. 'App running at: http://localhost:3000' showed up.

**Comment by kidsil** [comment]
Ran into the exact same problem, try running `meteor run` again. Worked on my end.

**Comment by philcruz** [comment]
Was hitting a similar error...on a hunch I looked in .meteor\local\db and found a mongodb.lock file. I deleted the file and it started working again.
