### ISSUE TITLE
Fibers: Win Meteor 0.1.1 throws Assertion fail

### ISSUE THREAD

**Issue by AdrianJMartin** [meteor/windows-preview#48]
Was very interested in looking through Meteor. But failed at the first command.

![image](https://cloud.githubusercontent.com/assets/1681191/5973983/cdf9bf10-a866-11e4-8198-8d0792ca29cc.png)

This is a fresh install of Meteor....Win7 Pro 64 bit.

**Comment by stubailo** [comment]
Do you have any antivirus software running? We're still investigating how to fix this issue.

**Comment by Slava** [comment]
I wonder if this is the Fibers failure @sdarnell told us about 2 month ago.

**Comment by AdrianJMartin** [comment]
Yep Sophos, version 10

**Comment by sdarnell** [comment]
Yes, I'm pretty sure it is the issue I mentioned. As a work-around some users have found that setting one of these environment variables before running meteor sometimes helps:
```
set __COMPAT_LAYER=WIN7RTM
or
set __COMPAT_LAYER=Win2000
```

There are essentially two related problems:
Fibers relies on the position of thread locals to find the isolate pointer etc., and whilst this seems to be very reliable on Linux/Mac/Posix, it is a different story on Windows.
For one thing Windows allows certain applications (e.g. virus scanners) to execute when programs, threads and DLLs get loaded. Some of these programs allocate thread locals.
Windows also allows thread locals to be freed, and re-used, which means the order of allocation of thread locals is much less predictable and the heuristics fibers uses fails.
One final issue is that there are many variants of Windows, and of the libraries (e.g. networking libraries in particular).

So in my version, I rebuilt fibers to expand the range of thread locals that are considered, for some users this helped.

Longer term, the next major version of Node (and the V8) the interface has improved and fibers no longer needs to use the dark arts. I guess io.js would also work. At least for Windows support, this may be a good enough reason to move forward to a newer node (maybe even an 'unstable' 11.x version?).

Another work-around for now, or at least experiment is to replace the fibers.node file with the version from my github repo.

And just to clarify, the floor_thread_key assert is essentially saying that it got to the bottom of the search range and didn't find a matching marker thread local.

**Comment by stubailo** [comment]
Hopefully this is now fixed. We are using a fork of fibers here: https://github.com/meteor/node-fibers

**Comment by sdarnell** [comment]
Should do the trick :)  I also notice that fibers has recently added some improved checking for the validity of the detected thread locals so that it should result in a more stable version than I had been using.

**Comment by stubailo** [comment]
Yep, that fork is based on the newest version.
