### ISSUE TITLE
Meteor's download bar does not overwrite itself if running from cmd

### ISSUE THREAD

**Issue by yeputons** [meteor/windows-preview#49]
Here is what happens if I open cmd session and type `meteor`:

![](https://cloud.githubusercontent.com/assets/1297325/5988589/e6c89a5e-a977-11e4-8489-e45878c32d8e.png)

And here is what happens if I do the same inside Far Manager (as it should be):

![2015-01-31 18-36-18 meteor - far 3 0 3800 x64](https://cloud.githubusercontent.com/assets/1297325/5988593/105d5332-a978-11e4-84bc-bbee13920c7f.png)

However, if I `start meteor` from Far Manager, same effect as with cmd appears

**Comment by Slava** [comment]
I suspect it is related to the way we print `'\b'` char in the beginning of the line. In CMD printing it in the beginning wouldn't erase anything from the previous line, thus the behavior.

**Comment by Slava** [comment]
Yeah, after looking at this more, some terminal emulators work better than others. I tested in ConEmu and the behavior was great. In CMD.exe it is just like on a picture above.

**Comment by Slava** [comment]
Ugh weird. I used a different font in my cmd.exe settings and now it works just fine.

**Comment by Slava** [comment]
OK, figured it out. Apparently, when the width of the window is not large enough to print all the characters, cmd.exe automatically inserts a new line char to break the long line into chunks. There is no automatic reflow or anything. So later, when we print a bunch of "BS" chars (backspace `\b`), nothing happens, as BS chars can't erase those new line chars.

**Comment by Slava** [comment]
Fixed in https://github.com/meteor/meteor/commit/89e037325935ce8e0113278c703d8c763dd4f6e6
