### ISSUE TITLE
After updating to `meteor-tool 1.1.0-winr.1` meteor do not start at all

### ISSUE THREAD

**Issue by yeputons** [meteor/windows-preview#50]
After I've run Meteor today, it have downloaded newer version of `meteor-tool`, updated it and how I have the following message any time I try to run `meteor`, arguments or current directory do not affect it:

```
module.js:340
    throw err;
          ^
Error: Cannot find module '../packages/package-version-parser/package-version-parser.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\e.suvorov\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.1\mt-os.windows.x86_32\tools\package-version-parser.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by yeputons** [comment]
Looks like the problem is caused by meteor/meteor@f428b55e20884949ae889c22b75f8ce253365a07

**Comment by yeputons** [comment]
Looks like the problem is related to meteor/meteor@f428b55 by @stubailo

**Comment by stubailo** [comment]
Oh, darn, I accidentally made this release recommended. For now, run with meteor --release WINDOWS-PREVIEW@0.1.1

**Comment by tnedich** [comment]
Same problem here. Win 7 Ultimate 64 bit OS.

**Comment by yeputons** [comment]
@tnedich removing `%LOCALAPPDATA%/.meteor` completely and installing it again from Wiki page helped me.

**Comment by tnedich** [comment]
@yeputons thank you, i will try that. Now I am using vagrant.

**Comment by digioak** [comment]
@yeputons that did not work for me -- @stubailo 's solution worked.

**Comment by Slava** [comment]
Just released 0.1.5. This error should be fixed, can you please try? [Installer](http://s3.amazonaws.com/meteor-windows/installers/WINDOWS-PREVIEW@0.1.5/InstallMeteor.exe)

**Comment by tnedich** [comment]
@Slava  I have deleted .meteor from User\AppData\Local and installed 0.1.5.  - Everything is working now. (Windows 7 Ultimate - 64 bit). Thank you Slava ! (In my native language Slava means - glory  :) )

**Comment by Slava** [comment]
@tnedich you wouldn't believe, but in my native language it means "glory", too!
