### ISSUE TITLE
"Surprising path" error should be renamed to something more useful

### ISSUE THREAD

**Issue by dandv** [meteor/windows-preview#51]
[Turns out](https://github.com/meteor/windows-preview/issues/37#issuecomment-72340605) that I had PACKAGE_DIRS set to a non-existent directory. This caused `meteor` to complain

> Error: Surprising path: /prg/meteor/$packages

If possible, It would be more helpful to report what exactly was surprising about that path, i.e. that it doesn't exist. I presume this is an upstream Node.js error message?

**Comment by Slava** [comment]
no, it is an assertion in our codebase for absolute paths: https://github.com/meteor/meteor/blob/e2c358dd45a568902b58324a1e29e0c58b0faf41/tools/files.js#L1178-L1180

Can you please explain why you supplied "/prg/meteor/$packages" path and expected it to work?

**Comment by dandv** [comment]
I didn't supply that path explicitly. It's an environment variable that I had set in the old days of Meteor for Windows (v0.8). In the meantime I moved development to Linux, renamed that directory on my Windows machine, and forgot about the variable.

When I got back to Meteor on Windows today after this time away from it, I had no idea where `/prg/meteor/$packages` was coming from.

**Comment by Slava** [comment]
@dandv so I guess it is a path that was passed by mistake? I don't expect such path to mean anything on Windows, a good requirement can be sanitizing path to be something matching `/^[a-z]:(\\[^:\/!@#$%^&*]*|$)/ig`

**Comment by dandv** [comment]
`/prg/meteor/$packages` is a valid path on Windows. Try this on a cmd prompt:

![image](https://cloud.githubusercontent.com/assets/33569/5991276/c5fb11f6-a997-11e4-8060-64ef46ff5805.png)

**Comment by Slava** [comment]
@dandv if `cd` accepts it as an argument, it doesn't mean it is a valid path. I refer to this https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#fully_qualified_vs._relative_paths
