### ISSUE TITLE
How to set MONGO_URL when using "meteor run"

### ISSUE THREAD

**Issue by Hopewp** [meteor/windows-preview#52]
"MONGO_URL=mongodb://localhost:19019/aking meteor" is worked on linux,but it isn't useful on windows

**Comment by stubailo** [comment]
Hi on Windows, you have to set environment variables the Windows way. You need to call a separate command, `set`.

Like this:
```
set MONGO_URL=mongodb://localhost:19019/aking
meteor
```

**Comment by Hopewp** [comment]
Thank you!

**Comment by satmari** [comment]
Not working, on both variants.
On windows platform!

set MONGO_URL=mongodb://my_ip:27017/db (with bind_ip = my_ip)
set MONGO_URL=mongodb://localhost:27017/db

Can you help me?
