### ISSUE TITLE
unknown:-1: error

### ISSUE THREAD

**Issue by ManuelDeLeon** [meteor/windows-preview#53]
Installed fine but creating a new project was weird. The progress didn't update in place. Instead it spit out one line per change. When I tried to run it game me an unknown error -1
```
   Downloading meteor-tool@1.1.0-winr.0...   [========================] 99% 0.3s

   Downloading meteor-tool@1.1.0-winr.0...   [========================] 99% 0.3s

   Downloading meteor-tool@1.1.0-winr.0...   [========================] 99% 0.3s

   Downloading meteor-tool@1.1.0-winr.0...   [========================] 99% 0.3s

   Downloading meteor-tool@1.1.0-winr.0...   [========================] 99% 0.3s

   Downloading meteor-tool@1.1.0-winr.0...   [========================] 99% 0.3s

   Downloading meteor-tool@1.1.0-winr.0...   [========================] 99% 0.3s

   Downloading meteor-tool@1.1.0-winr.0...   [========================] 99% 0.3s

   Downloading meteor-tool@1.1.0-winr.0...   [========================] 99% 0.3s

   Downloading meteor-tool@1.1.0-winr.0...   [========================] 99% 0.3s

   Downloading meteor-tool@1.1.0-winr.0...   [========================] 99% 0.3s

   Downloading meteor-tool@1.1.0-winr.0...   [========================] 99% 0.3s

   Downloading meteor-tool@1.1.0-winr.0...   [========================] 99% 0.3s

   Downloading meteor-tool@1.1.0-winr.0...   [========================] 99% 0.3s

   Downloading meteor-tool@1.1.0-winr.0...   [========================] 99% 0.3s

   Downloading meteor-tool@1.1.0-winr.0...   [========================] 99% 0.3s

   Downloading meteor-tool@1.1.0-winr.0...   [=======================] 100% 0.0s

   Downloading meteor-tool@1.1.0-winr.0...   [=======================] 100% 0.0s

   Downloading meteor-tool@1.1.0-winr.0...   [=======================] 100% 0.0s

   Downloading meteor-tool@1.1.0-winr.0      [=======================] 100% 0.0s

test: created.

To run your new app:
  cd test
  meteor
C:\Temp\WebTest>cd test

C:\Temp\WebTest\test>meteor
<unknown>:-1: <error>
C:\Temp\WebTest\test>
```

**Comment by Slava** [comment]
The progress bar is a known issue.

The unknown:-1 error is interesting. Can you give me please more info? Like try `meteor.bat` instead of `meteor` and try `meteor.bat --version` or `C:\users\youruser\appdata\local\.meteor\meteor.bat`?

**Comment by ManuelDeLeon** [comment]
meteor.bat doesn't work
C:\users\youruser\appdata\local\.meteor\meteor.bat does work however.

It's probably something an old install left behind in the path. I'll look into it tonight.

**Comment by stubailo** [comment]
Hi, are you sure the path is exactly `C:\users\youruser\appdata\local.meteor\meteor.bat`?

There should be a slash between local and .meteor, and I think some other users might have reported the lack of a slash there. Maybe this path is the reason the path variable doesn't work?

**Comment by stubailo** [comment]
@ManuelDeLeon any updates?

**Comment by ManuelDeLeon** [comment]
Ack!  Sorry. It's working on another box so I forgot to deal with the box
that threw this error. I'm pretty sure I copy pasted Kim's line and
replaced my user name. I'll test it tonight.

**Comment by ManuelDeLeon** [comment]
Got the error once, then tried "C:\users\manuel\appdata\local\.meteor\meteor.bat" which worked. Then tried "meteor" and this time it worked! (no clue why)
I'd say let's close this since it's most likely that it was because of old install files.
