### ISSUE TITLE
Installer needs to be run twice

### ISSUE THREAD

**Issue by landmaxcanada** [meteor/windows-preview#55]
It seems that the Windows Preview InstallMeteor.exe always fails on the first install, then works fine on a second attempt. The first time there is a "permissions" issue. Doing nothing but re-installing and it works fine the second time.

**Comment by stubailo** [comment]
We're working on a completely new installer that will hopefully have fewer issues. hang tight!

**Comment by landmaxcanada** [comment]
Until then, you may want to add a comment to the instructions to tell testers to try and install twice.

**Comment by sdarnell** [comment]
Please could you give details of the error you're seeing?

**Comment by ThusStyles** [comment]
I get this error every time, tried running as admin same issue - http://i.gyazo.com/4ed6240dc6e5123559413285764b2373.png

**Comment by stubailo** [comment]
Hi, we just released an initial version of the brand new completely rebuilt installer.

Please try it and see if you still get this issue: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

**Comment by avital** [comment]
It's been a month since the last comment here, so I'm going to assume that the new installer solves this issue.

If not, please file an issue against the [meteor/meteor](https://github.com/meteor/meteor) repository. This repository will be closed soon.
