### ISSUE TITLE
Time frame for Mobile?

### ISSUE THREAD

**Issue by landmaxcanada** [meteor/windows-preview#56]
Hi, I am working through the sample simple-todo demo. So far everything works up until Step7 "meteor install-sdk android" which fails to load.
Is there a work around for this?

**Comment by Slava** [comment]
There is currently no workaround, the mobile part is supported on Windows yet and we don't have a concrete time-frame either.

You can skip step 7 in the tutorial entirely, it walks you through running an ios app and android app in case you are on Linux or Mac.
