### ISSUE TITLE
Assets.getText does not handle windows paths

### ISSUE THREAD

**Issue by MattiLehtinen** [meteor/windows-preview#58]
I encountered this issue when trying to use `nemo64:bootstrap` package on Windows.
The package seems to use `path.join` when importing assets which produces following error on windows:

    Unknown asset: bootstrap\less\mixins\hide-text.less (compiling lib/custom.bootstrap.json)

It seems that Assets.getText doesn't standardize windows-style paths.

How to resolve:
Add `assetPath = files.convertToStandardPath(assetPath);` to `getAsset`-function on `tools/bundler.js`. (`tools/server/boot.js` has this fix in place on nearly identical function)

**Comment by Slava** [comment]
I applied the fix on devel, thank you!

**Comment by stubailo** [comment]
This is the best bug report ever. Thanks again!

**Comment by MattiLehtinen** [comment]
No problem. Glad to help and thanks for fixing it very quickly!
