### ISSUE TITLE
Client-only changes still causes server restart.

### ISSUE THREAD

**Issue by jcoder58** [meteor/windows-preview#62]
When I make a client-only change on Linux, (a change to a file in the client subdirectory), Meteor on Linux will just update the clients and the server will not restart.

With Windows preview 0.1.7, meteor rebuilds and restarts the server for changes that are only on the client side.

**Comment by stubailo** [comment]
This is probably the next performance-related issue we will tackle, but it might not be for the first Windows release. Unfortunately, it requires some re-engineering because we can't send interprocess signals on Windows, which is how this is implemented on Linux and Mac currently.

**Comment by sdarnell** [comment]
I came across a potentially simple replace for Unix style signals, which appears to be portable across platforms.

See http://nodejs.org/api/child_process.html#child_process_child_send_message_sendhandle

From recollection, listening for this event would be very similar to the way the signals are listened to.

**Comment by stubailo** [comment]
Wow, looks great! We'll try that.

**Comment by Slava** [comment]
fixed in https://github.com/meteor/meteor/pull/3704

**Comment by Slava** [comment]
@sdarnell thanks, I used your advice and looked at the `child_process.fork` implementation, which apparently just opens an `ipc` pipe.

**Comment by Slava** [comment]
Fixed and merged, I am closing this. Should land in the next preview release
