### ISSUE TITLE
During installation, Access to the Path is denied.

### ISSUE THREAD

**Issue by KyleMit** [meteor/windows-preview#63]
When doing a fresh install of [0.1.7][0], I get the following message:

![screenshot][1]

It successfully downloads and extracts the installer, but fails at the following point:

> Unexpected exception System.IO.IOException: Access to the Path '%LocalAppData%\.meteor~' is denied.
&nbsp;&nbsp;at System.IO.Directory.Move(String sourceDirName, String destDirName)
&nbsp;&nbsp;at Launch.Meteor.Program.BootstrapWarehouse(String warehouse)
&nbsp;&nbsp;at Launch.Meteor.Program.Main(String[] args)

My account has admin privileges on the computer and for the appropriate directory.

This may be a regression of [Installer throwing exception of Access denied][2], but the error message looks different, so I thought I'd throw more data at the solution.

**Notes**: 

* There are no spaces in the path for %LocalAppData%
* This happens even when I run the installer As Administrator
* I can't fix via deleting the `\Local\.meteor` because it doesn't exist yet.
* I'm on a Windows 7 Machine

[0]: http://s3.amazonaws.com/meteor-windows/installers/WINDOWS-PREVIEW@0.1.7/InstallMeteor.exe
[1]: http://i.imgur.com/JZHNIdM.png
[2]: https://github.com/meteor/windows-preview/issues/31

**Comment by stubailo** [comment]
We're currently working on a completely new installer, I'll let you know when it's out!

**Comment by stubailo** [comment]
Hi, we just released an initial version of the brand new completely rebuilt installer.

Please try it and see if you still get this issue: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

**Comment by avital** [comment]
It's been a month since the last comment here, so I'm going to assume that the new installer solves this issue.

If not, please file an issue against the [meteor/meteor](https://github.com/meteor/meteor) repository. This repository will be closed soon.
