### ISSUE TITLE
Digital Signature for the Installer

### ISSUE THREAD

**Issue by indcoder** [meteor/windows-preview#65]
While clicking on the installer, it is displayed to the user that the installer's publisher cannot be verified. Its advisable and a best practice to code sign the installer with a digital certificate.

![screenshot 2015-02-11 22 06 40](https://cloud.githubusercontent.com/assets/2099300/6151713/9dfcd91a-b23d-11e4-8c90-6d5c881035ab.png)

**Comment by Slava** [comment]
we are working on a new installer that doesn't have this issue

**Comment by rbabayoff** [comment]
Publisher is still unknown

**Comment by stubailo** [comment]
Yes, this is on my todo list - for the final release we will add signing the exe to the build system.

**Comment by stubailo** [comment]
https://twitter.com/stubailo/status/581178936773648384 check it yo!

**Comment by avital** [comment]
We believe that this has been resolved with the new installer for Meteor 1.1.

If not, please file an issue against the [meteor/meteor](https://github.com/meteor/meteor) repository. This repository will be closed soon.
