### ISSUE TITLE
deployed app crashes for WINDOWS-PREVIEW@0.1.7

### ISSUE THREAD

**Issue by pdavidow** [meteor/windows-preview#66]
http://meteoronome.meteor.com
built from
https://github.com/pdavidow/meteoronome/tree/954b222ed05e3f18b756ba68dca621a6ed7edaa1
crashes on load:

![image](https://cloud.githubusercontent.com/assets/220924/6177934/7eccccbc-b2d8-11e4-8636-671b20ecce5c.png)

**Comment by lpartan** [comment]
easy to fix:  reduce boot.js node.js version from 36 to 33

**Comment by pdavidow** [comment]
And how exactly do I do that?

**Comment by lpartan** [comment]
It looks like the NODE.JS installed on meteor.com is v0.10.33.
That's a bit old.  The code in the Windows preview package is asking for v0.10.36.
The real solution is probably to upgrade the NODE.JS installed on meteor.com.

So, here is a temporary solution that anyone can do:
--Change one line inside the file boot.js on your PC.
Boot.js is located inside the appdata\local\.meteor folder.

On my PC, %localappdata% is "C:\Users\lpartan\AppData\Local".
To quickly navigate to this directory, try this string in file explorer:
  %localappdata%\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\tools\server\

 -- Edit boot.js
 -- change line 12 
 from  var MIN_NODE_VERSION = 'v0.10.36';
 to    var MIN_NODE_VERSION = 'v0.10.33';

 -- or, alternatively, make line 17 into a comment like this:
 // process.exit(1)
 -- save the file

Now you can deploy to meteor.com, and it will run.
Apparently when "deploy" runs, it grabs a fresh copy from %localappdata%

**Comment by Slava** [comment]
closing as dup #64
