### ISSUE TITLE
mongodb.lock not dropped 

### ISSUE THREAD

**Issue by mdinesh7** [meteor/windows-preview#67]
When the server is running and if there are errors in the app. Meteor stops running sometimes and it doesn't drop mongodb.lock causing mongodb error.

# More Info:
=> Started proxy.
Unexpected mongo exit code 100. Restarting.
Can't start Mongo server.
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local databa
Check that you have permissions to write to .meteor/local. MongoDB do
not support filesystems like NFS that do not allow file locking.

To solve this problem - before starting meteor, I am deleting the mongodb.lock file from .meteor/local/db/

This needs to be fixed?

**Comment by avital** [comment]
Yes, this is fixed in https://github.com/meteor/meteor/commit/504e05326fc3c70dc097608279bec3db9c7c27c5, and will be out with the next preview release.

**Comment by mdinesh7** [comment]
Thanks.
