### ISSUE TITLE
Double events

### ISSUE THREAD

**Issue by davidlighty** [meteor/windows-preview#69]
In 1.7 it appears that 'click .element' is being fired twice.

Sample would be
'click .element':function(){
           myCollection.update(this._id,{$set:{boolVar:!this.boolVar}});
           console.log('boolVar',boolVar);  // This will show up twice.
}

win10 preview + firefox + meteor win build 1.7

**Comment by lpartan** [comment]
seeing the same behavior (win8)

**Comment by davidlighty** [comment]
Further review showed this was an error on my part.  Not an issue.  Please delete.
