### ISSUE TITLE
needs to restart cmd after install

### ISSUE THREAD

**Issue by tomByrer** [meteor/windows-preview#70]
Seems a reboot is needed for the PATH; should it be noted [here](https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows#downloading-the-preview)?
Looked for a way to edit the page myself, but can't find the edit link in the new layout.

**Comment by sdarnell** [comment]
You don't need to reboot, you just need to start a new console window.

**Comment by Slava** [comment]
I thought it is a well known behavior: when you start a new shell (or cmd), it reads some init file with all the environment. After you modify the environment, you either need to reload the file or start a new shell. We can also add that to the instructions for people who don't know that.

**Comment by avital** [comment]
This is now explicitly stated at the last step of the installer.
