### ISSUE TITLE
No "client modified" on Windows; always "Meteor server restarted"

### ISSUE THREAD

**Issue by dandv** [meteor/windows-preview#74]
This seems too big of a difference between Windows and *nix, so I'm surprised it hasn't been reported already; please feel free to close this issue if I just wasn't able to find an existing one.

1. Create the default app
2. Run it and open http://localhost:3000
3. Change the HTML in a minor way, e.g. "Welcome to Meteor!" -> "Hey Meteor"
4. Watch what the server does.

On Windows 7 64-bit, the output from the server running in a `cmd` prompt is:
```
Preparing [...]
Selecting package versions
Downloading missing packages
Building the application
Meteor server restarted
```

On Linux, the output is correctly just
```
Client modified -- refreshing
```

It takes 6 seconds for the browser to refresh on Windows and 3 on the Linux VM running within that Windows.

**Comment by Slava** [comment]
I have implemented it several weeks ago on Windows. Can you try the `devel` branch? https://github.com/meteor/meteor/pull/3704

**Comment by dandv** [comment]
This may be a silly question, but how do I try any branch with the Windows preview?

**Comment by dandv** [comment]
I've tried that and ran into a problem with .meteor\local\build\programs\server\packages\autoupdate.js being incompletely generated after source line 187.

**Comment by Slava** [comment]
I don't understand the issue. Please give more information. What does "different Meteor source code" mean? You can run from a checkout if you want, devel branch works fine (if you have 7zip installed in path). What combined form? How to reproduce?

**Comment by stubailo** [comment]
This should be fixed in the newest release. Try updating your app: `meteor update --release WINDOWS-PREVIEW@0.2.0`

**Comment by dandv** [comment]
@stubailo: I'm getting an error when trying to update:

```
D:\prg\met\> meteor update --release WINDOWS-PREVIEW@0.2.0

C:\Users\dandv\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.12\mt-os.windows.x86_32\tools\server\mini-files.js:18
  if (p[0] === "\\" && (! partialPath)) {
       ^
TypeError: Cannot read property '0' of undefined
    at toPosixPath (C:\Users\Rambo\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.12\mt-os.windows.x86_32\tools\server\mini-files.js:18:8)
    at Object.convertToStandardPath (C:\Users\Rambo\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.12\mt-os.windows.x86_32\tools\server\mini-files.js:55:12)
    at Object.files.getHomeDir (C:\Users\Rambo\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.12\mt-os.windows.x86_32\tools\files.js:1165:13)
    at defaultWarehouseDir (C:\Users\Rambo\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.12\mt-os.windows.x86_32\tools\tropohouse.js:30:43)
    at Object.<anonymous> (C:\Users\Rambo\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.12\mt-os.windows.x86_32\tools\tropohouse.js:39:42)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

@Slava: what I meant is that when installing the Windows preview, the Meteor source code is deployed to `%LOCALAPPDATA%\.meteor\`. The .js files there are in combined form, with numbered lines:

```js
(function () {

///////////////////////////////////////////////////////////////////////////////////
//                                                                               //
// packages/autoupdate/autoupdate_server.js                                      //
//                                                                               //
///////////////////////////////////////////////////////////////////////////////////
                                                                                 //
// Publish the current client versions to the client.  When a client             // 1
// sees the subscription change and that there is a new version of the           // 2
// client available on the server, it can reload.                                // 3
//                                                                               // 4
```

I was trying to patch those files properly with those from a checkout and run `meteor` from where it was installed in the PATH, but now I see that the way to run the checkout is to run [meteor.bat](https://github.com/meteor/meteor/blob/devel/meteor.bat) from the checkout and not care about the installed code in `%LOCALAPPDATA%\.meteor\`.

**Comment by stubailo** [comment]
Ahh we accidentally released a broken preview - we'll have to fix that asap!

**Comment by Slava** [comment]
@dandv does it mean you don't have any issues any more and we can close this ticket?

**Comment by stubailo** [comment]
@dandv we accidentally broke `meteor update` in `0.1.7` and just found out now. Please run the new installer to update.

**Comment by dandv** [comment]
:heart: the new shiny installer GUI :)

![meteor windows installer screenshot - installr](https://cloud.githubusercontent.com/assets/33569/6513747/1ac20e84-c332-11e4-8a37-2837a826a4f2.png)


> Client modified -- refreshing

:+1:
