### ISSUE TITLE
Cannot create directory - invalid argument

### ISSUE THREAD

**Issue by lukemadera** [meteor/windows-preview#75]
When cloning a project I've been working on in Virtual Machine Linux (Ubuntu), I get this error when trying to clone a local package for the project:
fatal: cannot create directory at 'packages/lukemadera:auth': Invalid argument

I'm using Windows preview 0.1.7 on Windows 7

**Comment by sdarnell** [comment]
On windows you can't have colons in file names. I would suggest that you rename the directory containing your package to just 'author' or replace the colon with an underscore. Then edit the package to ensure it has a name set in the package.is. (should be lukemadera:auth).

Then try cloning again, as there is no longer a colon, it should be OK.

**Comment by lukemadera** [comment]
Thanks @sdarnell for the info. I didn't purposefully name my package with a colon / I followed the conventions in atmospherejs and in the Meteor docs which specifically say to name packages with `username:package`
http://docs.meteor.com/#/full/writingpackages

So a few questions:
1. what's the reason for the colon convention in the documentation if they can't be used on Windows?
2. it seems like a really good idea to keep package naming consistent across all packages - meaning if Windows does not support colons, all should be changed. In which case, what should we change to? An underscore as you suggested?
3. Can we reflect the Meteor docs to update this? Both switching from colons to underscores everywhere and/or detailing it's okay NOT to use the colon convention and that on Windows specifically it won't work?
4. Is the colon convention arbitrary? I.e. Can I not use colons and be okay? How do I go about changing my existing packages? Just rename them all? Is that possible with atmospherejs or do I have to delete the existing one and create new ones from scratch?

This seems like a pretty big deal that should be addressed and clarified up front.
If I should post this somewhere else as well please just let me know - I'm happy to help get this resolved ASAP and update my packages so they work everywhere!

Thanks again!

**Comment by Slava** [comment]
@lukemadera automatic conversion from Mac/Linux and "'_' by default" measures are already implemented on `devel` branch. They will be released in the next major Meteor release.

**Comment by lukemadera** [comment]
Awesome @Slava - so future packages will be created with underscores instead of colons and I can start doing that now? And existing colons will be auto converted to underscores?
And if I want to use Windows now / in the interim, I should convert my existing packages to underscores manually?

**Comment by Slava** [comment]
@lukemadera the display name and id still has a colon. The representation on disk has an underscore. To do it manually:

- rename your package folder from colon to underscore
- in the package.js file introduce the `name` field and give it a name with a colon

**Comment by lukemadera** [comment]
Thanks @Slava - getting closer..
I also had to change:

1. all file names to underscores
2. all file name references (i.e. `api.use` in `package.js`) to underscores

Then I got a note on Windows that I had to "downgrade" my versions from `meteor@1.0.3.1` to work with windows so I did the `meteor update --release WINDOWS-PREVIEW@0.1.7` command but now my (internal) packages don't work - I get:

```bash
=> Errors prevented startup:

   While reading package from `/C/wamp/www/test/rexus-meteor/packages/lukemadera_auth`:
   error: Unknown release WINDOWS-PREVIEW@1.0.3.1
```

I'm not sure where that is coming from as my package.js is like:

```js
Package.onUse(function(api) {
  api.versionsFrom('1.0.3.1');
  api.addFiles('lukemadera_auth.js');
```

Do I just have to change the `1.0.3.1` there to `0.1.7`? And then do the same for ALL packages? And does that mean I can NOT use any 3rd party (atmosphere) packages that use `1.0.3.1`? I can change my own packages but if I can't use other packages that would probably be a deal breaker at this point..
I know this is all pre-release for Windows so I'd understand if it's not ready yet and I just have to wait but I'd like to help test/debug it if I can!
Thanks for all your hard work on Meteor for Windows!

**Comment by Slava** [comment]
Well, the release you are looking for is `WINDOWS-PREVIEW@0.1.7`. `1.0.3.1` is the latest official Meteor release that was supported for Mac and Linux.

**Comment by Slava** [comment]
You can *temporarily* change you line to

```
  api.versionsFrom('WINDOWS-PREVIEW@0.1.7');
```

**Comment by lukemadera** [comment]
Right @Slava , but what about 3rd party packages (that I don't control) - if they're set to 1.0.3.1 (which I presume they will be - the default `meteor create --package` will set it to the most recent one, yes?) will I not be able to use those?

**Comment by Slava** [comment]
Just wait until we release the official Windows port if you find it
difficult to work with the pre preleases. I don't quite understand why do
you think 3rd party packages wouldn't work.

**Comment by stubailo** [comment]
`versionsFrom` is evaluated at the time the package is published. What @lukemadera  is seeing is a bug resulting from the hack that we have in the Windows preview that makes Meteor think `WINDOWS-PREVIEW` is the default release track instead of `METEOR`. So usually, when you put `versionsFrom("1.0.3.1")`, it's short for `versionsFrom("METEOR@1.0.3.1")`, but in this case it becomes `versionsFrom("WINDOWS-PREVIEW@1.0.3.1")`, which doesn't exist.

Like @Slava said, this will all be fixed as soon as we are on the official release track, where we won't need this hack anymore.

**Comment by lukemadera** [comment]
Gotcha, thanks @stubailo and @Slava !

**Comment by stubailo** [comment]
@Slava this could be a reason to switch to the `METEOR` track as soon as possible?

**Comment by Slava** [comment]
Given that the estimated time between an RC and the release is less than a week, we can do it only for the release, I think we will save more time this way.

**Comment by stubailo** [comment]
Sounds good to me.
