### ISSUE TITLE
Error: failed to connect to [localhost:27017]

### ISSUE THREAD

**Issue by dan335** [meteor/windows-preview#76]
I'm getting this error when running an app that works in linux.

```
W20150221-11:24:23.548(-8)? (STDERR) C:\Users\danph_000\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:278
W20150221-11:24:23.548(-8)? (STDERR)                                            throw(ex);
W20150221-11:24:23.549(-8)? (STDERR)                                                  ^
W20150221-11:24:23.549(-8)? (STDERR) Error: failed to connect to [localhost:27017]
W20150221-11:24:23.549(-8)? (STDERR)     at Object.Future.wait (C:\Users\danph_000\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.8\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:398:15)
W20150221-11:24:23.549(-8)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:200:1)
W20150221-11:24:23.549(-8)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
W20150221-11:24:23.549(-8)? (STDERR)     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
W20150221-11:24:23.549(-8)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
W20150221-11:24:23.549(-8)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:98:1)
W20150221-11:24:23.549(-8)? (STDERR)     at packages/accounts-base/accounts_common.js:141:1
W20150221-11:24:23.549(-8)? (STDERR)     at C:\meteor\dominus\.meteor\local\build\programs\server\packages\accounts-base.js:216:4
W20150221-11:24:23.549(-8)? (STDERR)     at C:\meteor\dominus\.meteor\local\build\programs\server\packages\accounts-base.js:1657:3
W20150221-11:24:23.550(-8)? (STDERR)     at C:\meteor\dominus\.meteor\local\build\programs\server\boot.js:222:10
W20150221-11:24:23.550(-8)? (STDERR)     - - - - -
W20150221-11:24:23.550(-8)? (STDERR)     at [object Object].<anonymous> (C:\Users\danph_000\AppData\Local\.meteor\packages\mongo\1.0.12-winr.4\npm\node_modules\mongodb\lib\mongodb\connection\server.js:555:74)
W20150221-11:24:23.550(-8)? (STDERR)     at [object Object].emit (events.js:106:17)
W20150221-11:24:23.550(-8)? (STDERR)     at [object Object].<anonymous> (C:\Users\danph_000\AppData\Local\.meteor\packages\mongo\1.0.12-winr.4\npm\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:150:15)
W20150221-11:24:23.550(-8)? (STDERR)     at [object Object].emit (events.js:98:17)
W20150221-11:24:23.550(-8)? (STDERR)     at Socket.<anonymous> (C:\Users\danph_000\AppData\Local\.meteor\packages\mongo\1.0.12-winr.4\npm\node_modules\mongodb\lib\mongodb\connection\connection.js:534:10)
W20150221-11:24:23.550(-8)? (STDERR)     at Socket.emit (events.js:95:17)
W20150221-11:24:23.550(-8)? (STDERR)     at net.js:441:14
W20150221-11:24:23.550(-8)? (STDERR)     at process._tickCallback (node.js:442:13)

```

This works fine

    meteor create test
    cd test
    meteor

**Comment by Slava** [comment]
Port 27017 is related to MongoDB.

**Comment by Slava** [comment]
@dan335 does it still happen to you? Can you make sure no other mongod.exe process is running before you start your app? What are the differences between a brand-new app and your app?

**Comment by dan335** [comment]
I tried again and still get the error.  Mongodb isn't installed.  The app I'm trying to run is https://github.com/dan335/dominus Maybe you could reproduce it?  It errors when running "meteor".  You don't need to start it with the settings.json or set environment variables like it says in the readme.

**Comment by Slava** [comment]
@dan335 I just ran it on my windows machine, it ran OK, mongo started. I got exceptions from you JS code on the server but otherwise it looked fine.

**Comment by dan335** [comment]
Ok, thanks Slava. I guess it's something on my machine although I have no idea what it could be.

**Comment by stubailo** [comment]
We should try to figure out what happens and if there's any workaround.

**Comment by dan335** [comment]
I'll try again sometime this weekend with the new release.

**Comment by dan335** [comment]
meteor create test2
    cd test2
    meteor

Everything works. If I add

    Messages = new Mongo.Collection('messages');

I get

	W20150307-17:15:20.930(-8)? (STDERR)     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
	W20150307-17:15:20.930(-8)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
	W20150307-17:15:20.930(-8)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:98:1)
	W20150307-17:15:20.930(-8)? (STDERR)     at app\test2.js:1:47
	W20150307-17:15:20.930(-8)? (STDERR)     at app\test2.js:27:3
	W20150307-17:15:20.930(-8)? (STDERR)     at C:\meteor\test2\.meteor\local\build\programs\server\boot.js:222:10
	W20150307-17:15:20.930(-8)? (STDERR)     at Array.forEach (native)
	W20150307-17:15:20.930(-8)? (STDERR)     - - - - -
	W20150307-17:15:20.930(-8)? (STDERR)     at [object Object].<anonymous> (C:\Users\danph_000\AppData\Local\.meteor\packages\mongo\1.0.12-winr.7\npm\node_modules\mongodb\lib\mongodb\connection\server.js:555:74)
	W20150307-17:15:20.930(-8)? (STDERR)     at [object Object].emit (events.js:106:17)
	W20150307-17:15:20.930(-8)? (STDERR)     at [object Object].<anonymous> (C:\Users\danph_000\AppData\Local\.meteor\packages\mongo\1.0.12-winr.7\npm\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:156:15)
	W20150307-17:15:20.931(-8)? (STDERR)     at [object Object].emit (events.js:98:17)
	W20150307-17:15:20.931(-8)? (STDERR)     at Socket.<anonymous> (C:\Users\danph_000\AppData\Local\.meteor\packages\mongo\1.0.12-winr.7\npm\node_modules\mongodb\lib\mongodb\connection\connection.js:534:10)
	W20150307-17:15:20.931(-8)? (STDERR)     at Socket.emit (events.js:95:17)
	W20150307-17:15:20.931(-8)? (STDERR)     at net.js:441:14
	W20150307-17:15:20.931(-8)? (STDERR)     at process._tickCallback (node.js:442:13)

Mongodb was installed at one point but is not anymore.  Any ideas on what to try?

**Comment by dan335** [comment]
I cut off some of the error message in the last post.

	W20150307-17:29:51.933(-8)? (STDERR)                                                  ^
	W20150307-17:29:51.933(-8)? (STDERR) Error: failed to connect to [localhost:27017]
	W20150307-17:29:51.933(-8)? (STDERR)     at Object.Future.wait (C:\Users\danph_000\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.12\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:398:15)
	W20150307-17:29:51.933(-8)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:200:1)
	W20150307-17:29:51.934(-8)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
	W20150307-17:29:51.934(-8)? (STDERR)     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
	W20150307-17:29:51.934(-8)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
	W20150307-17:29:51.934(-8)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:98:1)
	W20150307-17:29:51.934(-8)? (STDERR)     at app\test2.js:1:47
	W20150307-17:29:51.934(-8)? (STDERR)     at app\test2.js:27:3
	W20150307-17:29:51.934(-8)? (STDERR)     at C:\meteor\test2\.meteor\local\build\programs\server\boot.js:222:10
	W20150307-17:29:51.934(-8)? (STDERR)     at Array.forEach (native)
	W20150307-17:29:51.934(-8)? (STDERR)     - - - - -
	W20150307-17:29:51.934(-8)? (STDERR)     at [object Object].<anonymous> (C:\Users\danph_000\AppData\Local\.meteor\packages\mongo\1.0.12-winr.7\npm\node_modules\mongodb\lib\mongodb\connection\server.js:555:74)
	W20150307-17:29:51.934(-8)? (STDERR)     at [object Object].emit (events.js:106:17)
	W20150307-17:29:51.935(-8)? (STDERR)     at [object Object].<anonymous> (C:\Users\danph_000\AppData\Local\.meteor\packages\mongo\1.0.12-winr.7\npm\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:156:15)
	W20150307-17:29:51.935(-8)? (STDERR)     at [object Object].emit (events.js:98:17)
	W20150307-17:29:51.935(-8)? (STDERR)     at Socket.<anonymous> (C:\Users\danph_000\AppData\Local\.meteor\packages\mongo\1.0.12-winr.7\npm\node_modules\mongodb\lib\mongodb\connection\connection.js:534:10)
	W20150307-17:29:51.935(-8)? (STDERR)     at Socket.emit (events.js:95:17)
	W20150307-17:29:51.935(-8)? (STDERR)     at net.js:441:14
	W20150307-17:29:51.935(-8)? (STDERR)     at process._tickCallback (node.js:442:13)

**Comment by Slava** [comment]
@dan335 again, this error doesn't mean that Mongodb is not installed. Rather it says, it is not running on port 27017. There could be various reasons why it happens though.

**Comment by Slava** [comment]
Honestly, I run out of ideas, what can go wrong. When you run your app, do you see a line saying that "MongoDB is running"?

**Comment by dan335** [comment]
Here's the output without the error.

	C:\meteor\test2>meteor
	[[[[[ C:\meteor\test2 ]]]]]

	=> Started proxy.
	=> Started your app.

	=> App running at: http://localhost:3000/

With the error.

	C:\meteor\test2>meteor
	[[[[[ C:\meteor\test2 ]]]]]

	=> Started proxy.
	=> Exited with code: 8
	W20150307-22:43:40.191(-7)? (STDERR)
	W20150307-22:43:40.192(-7)? (STDERR) C:\Users\danph_000\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.12\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:278

**Comment by Slava** [comment]
@dan335 so sometimes you get the error and sometimes you don't? Or how does it happen?

**Comment by dan335** [comment]
It always errors when I add Messages = new Mongo.Collection('messages');

I noticed when I take that out it starts but still doesn't say anything about starting mongodb.  Not sure if it's supposed to.

**Comment by dan335** [comment]
I uninstalled node and it's working now. :D

**Comment by dan335** [comment]
After restarting my computer it errors again. :(

**Comment by dan335** [comment]
I got it working.  I think node was the issue.  I uninstalled meteor, removed everything about node, npm, mongo from my path, program files and appData.  Restarted my computer, installed meteor and now it's working.

**Comment by stubailo** [comment]
@Slava we should document this. It might be because we use the `NODE_PATH`?

**Comment by Slava** [comment]
@stubailo unclear, I wish I knew what global npm modules @dan335 had in his global installation. I am a bit confused by not seeing "Started MongoDB." in his logs, too.

**Comment by dan335** [comment]
It's been over a year since I've worked with those so I'm not sure.  If you're trying to reproduce it maybe try installing express, mongoose, mongodb globally?

**Comment by Slava** [comment]
I tried to reproduce by installing the `mongodb` npm modules of version `1.0.0` (should be old enough?) to both C:\ and globally. I also tried setting the global `NODE_PATH` to a location containing the old version of mongodb. My apps worked out OK.
