### ISSUE TITLE
Running Meteor Deploy from Powershell ISE

### ISSUE THREAD

**Issue by KyleMit** [meteor/windows-preview#77]
When I run the following command in Powershell in Windows 8.1:

    C:\GitHub\MeteorApps\simple-todos> meteor deploy Kyle-Todos.meteor.com

I get the following error:

>     meteor : To instantly deploy your app on a free testing server, just enter your email
    At line:1 char:1
    + meteor deploy Kyle-Todos.meteor.com
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (To instantly de...nter your email:String) [], RemoteException
        + FullyQualifiedErrorId : NativeCommandError
    address!
    Email: 

**Powershell**:

![Powershell Deploy](http://i.imgur.com/1zoHcfk.png)

It does however work in the Command Prompt.  Is there something special that needs to happen for Powershell support, or is it a PS specific issue?

**Command Prompt**:

![Command Prompt Deploy](http://i.imgur.com/iiuAo9H.png)

**Comment by Slava** [comment]
We are not big on PowerShell and mostly tested out cmd.exe. If anyone can help us with this, it would be great.

**Comment by stubailo** [comment]
It looks like we output something to stderr, and powershell in its infinite wisdom treats any output to stderr as a cue to terminate the program and display the error.

It's possible that we should either set a flag in powershell to ignore errors, or stop using stderr to print things on Windows.

**Comment by Slava** [comment]
I couldn't reproduce this. @KyleMit, can you please provide more details on how you run Powershell and what settings do you have set?

I ran a plain powershell from cmd.exe with `powershell.exe`, then ran `.\meteor.bat login` and got a welcome message to stderr. Nothing crashed.

**Comment by GiraffeSlacks** [comment]
For what it's worth I had no problem deploying in PowerShell. I also logged out and then deployed again. I was prompted for email and password without a problem.

**Comment by stubailo** [comment]
@KyleMit are you using PowerShell ISE by any chance?

**Comment by KyleMit** [comment]
@stubailo,
Yes, I'm using PowerShell ISE

This is working fine on regular powershell and regular command prompt.

A simpler test that produces this issue in ISE would be using either:

```
meteor login
meteor logout
```

Both of which cause issues in ISE, but not elsewhere.

Powershell ISE seems to be causing enough issues on it's own that it's not an issue (for me) if it's not fully supported; I'll just migrate away from using it as my terminal of choice for meteor apps.

**Comment by stubailo** [comment]
@KyleMit if you are still encountering issues, please file a new issue on meteor/meteor.
