### ISSUE TITLE
Installer throws recursive directory deletion errors and does not complete installation

### ISSUE THREAD

**Issue by devblazer** [meteor/windows-preview#80]
It seems like this error occurs when you run the installer from a different drive letter than C:

When I moved the installer to C: and ran it again I no longer got this error and the installation concluded successfully.

Although I suspect with this particular issue it does not matter, but I am running windows 7 64bit

**Comment by Slava** [comment]
This is weird, but we have a new installer that shouldn't have these problems.

**Comment by stubailo** [comment]
Hi, we just released an initial version of the brand new completely rebuilt installer.

Please try it and see if you still get this issue: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

**Comment by stubailo** [comment]
@devblazer, any updates?

**Comment by avital** [comment]
It's been a month since the last comment here, so I'm going to assume that the new installer solves this issue.

If not, please file an issue against the [meteor/meteor](https://github.com/meteor/meteor) repository. This repository will be closed soon.
