### ISSUE TITLE
Can't choose the install location of Meteor tool

### ISSUE THREAD

**Issue by tomByrer** [meteor/windows-preview#89]
I have 2-4 physical & several virtual drives.  I try not to instal everything into C:.  Installation program failed to ask where I wanted to instal Meteor.

**Comment by sdarnell** [comment]
Meteor is put in your LOCALAPPDATA, and this is where lots of programs will store local data. It is in your profile local to the machine.

So if you configure your LOCALAPPDATA to be on a different drive it will work OK. 

Note that meteor is not installing machine wide, it is a per user installation. Like for example chrome.

**Comment by Slava** [comment]
@tomByrer as Stephen said, Meteor installs itself to LOCALAPPDATA. We don't plan to offer an alternative installation in the first release. We had it at first, but then we decided to simplify the install process.

What you can do as a workaround, you can move your .meteor folder to a different location yourself and then link to it in your %PATH% env variable.

**Comment by avital** [comment]
FYI, both Chrome and Dropbox installers follow this scheme.

**Comment by tomByrer** [comment]
> FYI, both Chrome and Dropbox installers follow this scheme.

Which is why I don't use Dropbox, & Chrome is not my main browser ;)

Thanks for the workaround @Slava

**Comment by CaptainPalapa** [comment]
Yah, I'm with @tomByrer Would have VERY much preferred to install Metoer in my d:\Development\Servers instead of wherever *IT* decided to go.  Recommend changing, or at least offering an install executable option.
