### ISSUE TITLE
Stuck "Selecting package versions"

### ISSUE THREAD

**Issue by ThaumRystra** [meteor/windows-preview#9]
Using `meteor run` it gets to the `Selecting package versions` line and then spins indefinitely. `--verbose` doesn't provide any further info.

**Comment by stubailo** [comment]
Sorry, I can't reproduce this. It might be related to package constraint solver issues that are being fixed as we speak. @Slava ideas?

**Comment by Slava** [comment]
I agree, this looks like a constraint-solver problem
