### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by pdavidow** [meteor/windows-preview#91]
https://github.com/pdavidow/meteor-issue-infiniteLoop

Login by creating new user. Hit Import button to get infinite loop.
The culprit has something to do with method "isPieceListDisabled" in template.js.

Note that this problem was very difficult to narrow down, as system simply hangs.  
(I whittled away plenty of code to reproduce, and probably could whittle away some more.)

**Comment by stubailo** [comment]
Hi @pdavidow, it looks like this is general issue with Meteor, rather than an issue with Meteor on Windows specifically. Can you please report it on the [main repo](https://github.com/meteor/meteor/issues) or ask about it on the [forums](https://forums.meteor.com/)?

**Comment by pdavidow** [comment]
Ok, I just reported it in main repo.

**Comment by stubailo** [comment]
Thanks!
