### ISSUE TITLE
Starting 'meteor' in newly created app gives "'Meteor' is undefined"

### ISSUE THREAD

**Issue by Alber70g** [meteor/windows-preview#93]
Whenever I create a new app using `meteor create app` and I `cd app` and `meteor` I get the following. http://i.imgur.com/3wKOTSf.png It seems from Internet Explorer or something?

**Comment by Alber70g** [comment]
Well, I tried to launch in PowerShell (http://i.imgur.com/9fI9gRB.png). Seems to work now.

**Comment by stubailo** [comment]
@Alber70g I'm curious what the first thing you tried was. Did you double-click on `meteor.js`?

**Comment by Slava** [comment]
> Microsoft JScript runtime

**Comment by Alber70g** [comment]
@stubailo What I said in the opening post. Open cmd. Cd to direcory, create meteor app, run it with the meteor command. That din't use the nodejs, I think. But when I use powershell it works fine.

**Comment by stubailo** [comment]
Ohhhhhhhhh - I think what happened is that when your ran `meteor` it looked up the `meteor.js` from your current directory instead of `meteor` from your PATH. Interesting.

**Comment by Alber70g** [comment]
Ahh yeaaah oke, yea that's it I guess. Maybe the example apps tutorial should have some hints to that because its quite vital to use the app :). + it's probably the first thing people will look at, so if it doesn't work it's more likely they'll abandon meteor
