### ISSUE TITLE
error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by pdavidow** [meteor/windows-preview#94]
I upgraded to WINDOWS-PREVIEW@0.2.0, and now get these errors when running 'meteor':

=====================================================

=> Started proxy.
=> Errors prevented startup:

   While downloading npm-bcrypt@0.7.8-winr.3...:
   error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

   While downloading mizzao:accounts-testing@0.1.0...:
   error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

=> Your application has errors. Waiting for file change.
=> Started MongoDB.

=====================================================

Packages used:

standard-app-packages
underscore
reactive-dict
reactive-var
mizzao:accounts-testing
accounts-ui
accounts-password

=====================================================

Note that the standard 'Default' meteor project runs fine, but when I give it the above packages I then get the same errors.   But I was using these same packages with no problem in v0.1.7, so I then decided to reinstall that, which I did -- but the problems (which were never there before) persisted.  Seeing that that didn't help, I reinstalled the latest again (v0.2.0), and still have the problem.

Note also that if I take out the 'mizzao:accounts-testing' line, I still get:

=====================================================

=> Started proxy.
=> Errors prevented startup:

   While downloading npm-bcrypt@0.7.8-winr.3...:
   error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

=> Your application has errors. Waiting for file change.
=> Started MongoDB.

=====================================================

So, at this point, I cannot do any work at all with Meteor.

**Comment by stubailo** [comment]
Hi @pdavidow! This looks like a pretty serious issue - sorry that it's blocking you from using Meteor right now.

First question: what version of Windows are you running?

**Comment by pdavidow** [comment]
Windows7 Home Premium, ServicePack1, 64bit

**Comment by pdavidow** [comment]
In the meantime, I would be happy to totally uninstall Meteor such that I could then do a fresh install of v0.1.7 to restore my prior state.  Kindly advise.

**Comment by stubailo** [comment]
Have you tried running the uninstall from Add/Remove Programs in the Control Panel?

**Comment by pdavidow** [comment]
Yes. I ran the uninstall from Add/Remove Programs in the Control Panel, then restarted Windows, then re-installed v0.1.7, but I still get the same errors.  

Note that after the re-install was finished, a Windows 'Program Compatibility' dialog popped up saying that the install might not have completed successfully, but I dismissed it (http://stackoverflow.com/questions/5098747/reasons-for-getting-the-program-compatibility-assistant-dialog).

**Comment by pdavidow** [comment]
I uninstalled again, and then installed v0.3.0, and now get all these errors:

=================================================================

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While selecting package versions:
   error: Potentially incompatible change required to top-level dependency: standard-app-packages 1.0.5-rc.0, was
   1.0.5-winr.2.
   Constraints on package "standard-app-packages":
   * standard-app-packages@=1.0.5-rc.0 <- top level

   Potentially incompatible change required to top-level dependency: underscore 1.0.3-rc.0, was 1.0.3-winr.2.
   Constraints on package "underscore":
   * underscore@=1.0.3-rc.0 <- top level
   * underscore@1.0.3-rc.0 <- meteor 1.1.5-rc.0 <- accounts-base 1.2.0-rc.0 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- meteor 1.1.5-rc.0 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- meteor-platform 1.2.2-rc.0 <- standard-app-packages 1.0.5-rc.0
   * underscore@1.0.3-rc.0 <- reload 1.1.3-rc.0 <- autoupdate 1.2.0-win.0 <- meteor-platform 1.2.2-rc.0 <-
   standard-app-packages 1.0.5-rc.0
   * underscore@1.0.3-rc.0 <- reload 1.1.3-rc.0 <- ddp 1.1.0-rc.1 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- logging 1.0.7-rc.0 <- ddp 1.1.0-rc.1 <- accounts-base 1.2.0-rc.0 <- accounts-password
   1.1.0-win.1
   * underscore@1.0.3-rc.0 <- logging 1.0.7-rc.0 <- ddp 1.1.0-rc.1 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- ejson 1.0.6-rc.0 <- accounts-base 1.2.0-rc.0 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- ejson 1.0.6-rc.0 <- reactive-dict 1.1.0-rc.0
   * underscore@1.0.3-rc.0 <- autoupdate 1.2.0-win.0 <- meteor-platform 1.2.2-rc.0 <- standard-app-packages 1.0.5-rc.0
   * underscore@1.0.3-rc.0 <- webapp 1.2.0-rc.1 <- autoupdate 1.2.0-win.0 <- meteor-platform 1.2.2-rc.0 <-
   standard-app-packages 1.0.5-rc.0
   * underscore@1.0.3-rc.0 <- webapp 1.2.0-rc.1 <- ddp 1.1.0-rc.1 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- routepolicy 1.0.5-rc.0 <- ddp 1.1.0-rc.1 <- accounts-base 1.2.0-rc.0 <- accounts-password
   1.1.0-win.1
   * underscore@1.0.3-rc.0 <- routepolicy 1.0.5-rc.0 <- ddp 1.1.0-rc.1 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- boilerplate-generator 1.0.3-rc.0 <- webapp 1.2.0-rc.1 <- autoupdate 1.2.0-win.0 <-
   meteor-platform 1.2.2-rc.0 <- standard-app-packages 1.0.5-rc.0
   * underscore@1.0.3-rc.0 <- boilerplate-generator 1.0.3-rc.0 <- webapp 1.2.0-rc.1 <- ddp 1.1.0-rc.1 <- accounts-password
   1.1.0-win.1
   * underscore@1.0.3-rc.0 <- spacebars-compiler 1.0.5-rc.0 <- boilerplate-generator 1.0.3-rc.0 <- webapp 1.2.0-rc.1 <-
   autoupdate 1.2.0-win.0 <- meteor-platform 1.2.2-rc.0 <- standard-app-packages 1.0.5-rc.0
   * underscore@1.0.3-rc.0 <- spacebars-compiler 1.0.5-rc.0 <- boilerplate-generator 1.0.3-rc.0 <- webapp 1.2.0-rc.1 <- ddp
   1.1.0-rc.1 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- spacebars-compiler 1.0.5-rc.0 <- templating 1.1.0-win.0 <- accounts-ui-unstyled 1.1.7-rc.0 <-
   accounts-ui 1.1.5-rc.0
   * underscore@1.0.3-rc.0 <- blaze-tools 1.0.3-rc.0 <- spacebars-compiler 1.0.5-rc.0 <- boilerplate-generator 1.0.3-rc.0 <-
   webapp 1.2.0-rc.1 <- autoupdate 1.2.0-win.0 <- meteor-platform 1.2.2-rc.0 <- standard-app-packages 1.0.5-rc.0
   * underscore@1.0.3-rc.0 <- blaze-tools 1.0.3-rc.0 <- spacebars-compiler 1.0.5-rc.0 <- boilerplate-generator 1.0.3-rc.0 <-
   webapp 1.2.0-rc.1 <- ddp 1.1.0-rc.1 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- blaze-tools 1.0.3-rc.0 <- spacebars-compiler 1.0.5-rc.0 <- templating 1.1.0-win.0 <-
   accounts-ui-unstyled 1.1.7-rc.0 <- accounts-ui 1.1.5-rc.0
   * underscore@1.0.3-rc.0 <- spacebars 1.0.6-rc.0 <- boilerplate-generator 1.0.3-rc.0 <- webapp 1.2.0-rc.1 <- autoupdate
   1.2.0-win.0 <- meteor-platform 1.2.2-rc.0 <- standard-app-packages 1.0.5-rc.0
   * underscore@1.0.3-rc.0 <- spacebars 1.0.6-rc.0 <- boilerplate-generator 1.0.3-rc.0 <- webapp 1.2.0-rc.1 <- ddp 1.1.0-rc.1
   <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- spacebars 1.0.6-rc.0 <- meteor-platform 1.2.2-rc.0 <- standard-app-packages 1.0.5-rc.0
   * underscore@1.0.3-rc.0 <- blaze 2.1.0-rc.2 <- accounts-base 1.2.0-rc.0 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- observe-sequence 1.0.5-win.0 <- blaze 2.1.0-rc.2 <- accounts-base 1.2.0-rc.0 <-
   accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- minimongo 1.0.7-rc.0 <- ddp 1.1.0-rc.1 <- accounts-base 1.2.0-rc.0 <- accounts-password
   1.1.0-win.1
   * underscore@1.0.3-rc.0 <- minimongo 1.0.7-rc.0 <- ddp 1.1.0-rc.1 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- id-map 1.0.3-rc.0 <- binary-heap 1.0.3-rc.0 <- mongo 1.1.0-rc.0 <- accounts-base 1.2.0-rc.0 <-
   accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- id-map 1.0.3-rc.0 <- binary-heap 1.0.3-rc.0 <- mongo 1.1.0-rc.0 <- reactive-dict 1.1.0-rc.0
   * underscore@1.0.3-rc.0 <- ordered-dict 1.0.3-rc.0 <- minimongo 1.0.7-rc.0 <- ddp 1.1.0-rc.1 <- accounts-base 1.2.0-rc.0 <-
   accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- ordered-dict 1.0.3-rc.0 <- minimongo 1.0.7-rc.0 <- ddp 1.1.0-rc.1 <- accounts-password
   1.1.0-win.1
   * underscore@1.0.3-rc.0 <- random 1.0.3-rc.0 <- accounts-base 1.2.0-rc.0 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- random 1.0.3-rc.0 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- templating 1.1.0-win.0 <- accounts-ui-unstyled 1.1.7-rc.0 <- accounts-ui 1.1.5-rc.0
   * underscore@1.0.3-rc.0 <- minifiers 1.1.4-win.0 <- spacebars-compiler 1.0.5-rc.0 <- boilerplate-generator 1.0.3-rc.0 <-
   webapp 1.2.0-rc.1 <- autoupdate 1.2.0-win.0 <- meteor-platform 1.2.2-rc.0 <- standard-app-packages 1.0.5-rc.0
   * underscore@1.0.3-rc.0 <- minifiers 1.1.4-win.0 <- spacebars-compiler 1.0.5-rc.0 <- boilerplate-generator 1.0.3-rc.0 <-
   webapp 1.2.0-rc.1 <- ddp 1.1.0-rc.1 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- minifiers 1.1.4-win.0 <- spacebars-compiler 1.0.5-rc.0 <- templating 1.1.0-win.0 <-
   accounts-ui-unstyled 1.1.7-rc.0 <- accounts-ui 1.1.5-rc.0
   * underscore@1.0.3-rc.0 <- minifiers 1.1.4-win.0 <- templating 1.1.0-win.0 <- accounts-ui-unstyled 1.1.7-rc.0 <-
   accounts-ui 1.1.5-rc.0
   * underscore@1.0.3-rc.0 <- webapp-hashing 1.0.3-rc.0 <- webapp 1.2.0-rc.1 <- autoupdate 1.2.0-win.0 <- meteor-platform
   1.2.2-rc.0 <- standard-app-packages 1.0.5-rc.0
   * underscore@1.0.3-rc.0 <- webapp-hashing 1.0.3-rc.0 <- webapp 1.2.0-rc.1 <- ddp 1.1.0-rc.1 <- accounts-password
   1.1.0-win.1
   * underscore@1.0.3-rc.0 <- ddp 1.1.0-rc.1 <- accounts-base 1.2.0-rc.0 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- ddp 1.1.0-rc.1 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- check 1.0.5-rc.0 <- accounts-base 1.2.0-rc.0 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- check 1.0.5-rc.0 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- retry 1.0.3-rc.0 <- autoupdate 1.2.0-win.0 <- meteor-platform 1.2.2-rc.0 <-
   standard-app-packages 1.0.5-rc.0
   * underscore@1.0.3-rc.0 <- retry 1.0.3-rc.0 <- ddp 1.1.0-rc.1 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- callback-hook 1.0.3-rc.0 <- accounts-base 1.2.0-rc.0 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- mongo 1.1.0-rc.0 <- accounts-base 1.2.0-rc.0 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- mongo 1.1.0-rc.0 <- reactive-dict 1.1.0-rc.0
   * underscore@1.0.3-rc.0 <- binary-heap 1.0.3-rc.0 <- mongo 1.1.0-rc.0 <- accounts-base 1.2.0-rc.0 <- accounts-password
   1.1.0-win.1
   * underscore@1.0.3-rc.0 <- binary-heap 1.0.3-rc.0 <- mongo 1.1.0-rc.0 <- reactive-dict 1.1.0-rc.0
   * underscore@1.0.3-rc.0 <- http 1.1.0-rc.0 <- autoupdate 1.2.0-win.0 <- meteor-platform 1.2.2-rc.0 <- standard-app-packages
   1.0.5-rc.0
   * underscore@1.0.3-rc.0 <- url 1.0.4-rc.0 <- http 1.1.0-rc.0 <- autoupdate 1.2.0-win.0 <- meteor-platform 1.2.2-rc.0 <-
   standard-app-packages 1.0.5-rc.0
   * underscore@1.0.3-rc.0 <- session 1.1.0-rc.0 <- accounts-ui-unstyled 1.1.7-rc.0 <- accounts-ui 1.1.5-rc.0
   * underscore@1.0.3-rc.0 <- reactive-dict 1.1.0-rc.0
   * underscore@1.0.3-rc.0 <- accounts-base 1.2.0-rc.0 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- accounts-ui-unstyled 1.1.7-rc.0 <- accounts-ui 1.1.5-rc.0
   * underscore@1.0.3-rc.0 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- srp 1.0.3-rc.0 <- accounts-password 1.1.0-win.1
   * underscore@1.0.3-rc.0 <- email 1.0.6-rc.0 <- accounts-password 1.1.0-win.1

   Potentially incompatible change required to top-level dependency: reactive-var 1.0.5-rc.0, was 1.0.5-winr.2.
   Constraints on package "reactive-var":
   * reactive-var@=1.0.5-rc.0 <- top level
   * reactive-var@1.0.5-rc.0 <- blaze 2.1.0-rc.2 <- accounts-base 1.2.0-rc.0 <- accounts-password 1.1.0-win.1

   Potentially incompatible change required to top-level dependency: accounts-ui 1.1.5-rc.0, was 1.1.5-winr.2.
   Constraints on package "accounts-ui":
   * accounts-ui@=1.1.5-rc.0 <- top level
   * accounts-ui@1.0.0 <- mizzao:accounts-testing 0.1.0

   To allow potentially incompatible changes to top-level dependencies, you must pass --allow-incompatible-update on the
   command line.

   While refreshing package catalog to resolve previous errors:
   error: Network error: wss://packages.meteor.com/websocket: UNABLE_TO_VERIFY_LEAF_SIGNATURE

=> Your application has errors. Waiting for file change.

**Comment by pdavidow** [comment]
I then tried deleting the 'versions' file  (for v0.3.0), and am back to just the familiar errors:

==========================

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While downloading mizzao:accounts-testing@0.1.0...:
   error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

   While downloading npm-bcrypt@0.7.8_2...:
   error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

=> Your application has errors. Waiting for file change.

**Comment by pdavidow** [comment]
So I then tried also uninstalling Node besides Meteor (http://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows), and then reinstalling Meteor (v0.3.0), but still get the same 2 'LEAF' errors. However, if I then commented out both packages:

mizzao:accounts-testing
accounts-password

there are no more errors, and I can bring up my app -- except 'No login services configured', which is a big problem.

**Comment by stubailo** [comment]
We think that this is a similar problem to what NPM users sometimes experience: http://stackoverflow.com/questions/20082893/unable-to-verify-leaf-signature

Unfortunately, we haven't gotten many reports of this issue and so we probably won't get to it before the initial Windows release. Maybe if you look around for how people have solved this issue for other programs you can find a workaround, and it would be great if you could post it here.

I'll let you know if we are able to fix this issue in the future.

**Comment by pdavidow** [comment]
No sweat. I already switched to Nitrous.
:)
