### ISSUE TITLE
Can't update project since 0.2.8

### ISSUE THREAD

**Issue by 255kb** [meteor/windows-preview#95]
Hi, 

When running an existing project I got the following message:
*Meteor 0.2.8 is available. Update this project with 'meteor update'.*

But either by running `meteor update` or `meteor update --release WINDOWS-PREVIEW@0.2.8` the project is still showing version 'Meteor 0.2.0'.

Creating a new project is working.

I am using Windows 7 64bits

**Comment by stubailo** [comment]
Did Meteor print something like "This project is at the latest release which is compatible with your current package constraints"?

**Comment by stubailo** [comment]
@255kb, unfortunately there is some snafu with the version numbers. As a workaround until we figure that out, please delete the `.meteor/versions` file of your project, then run `meteor update --release WINDOWS-PREVIEW@0.2.8`.

**Comment by 255kb** [comment]
You are right I got the message "This project is at the latest release which is compatible with your current package constraints".
I tried the workaround and it works like a charm! Thank you !

btw the windows version is improving really fast and it is near perfect now. :+1:

**Comment by stubailo** [comment]
Going to close since it won't be an issue after release.
