### ISSUE TITLE
meteor (meteor.bat) not found when using Git Bash cmd

### ISSUE THREAD

**Issue by jonagoldman** [meteor/windows-preview#96]
The meteor path was added correctly to my system variables, but I can't run it when using the Git Bash.
When using the regular windows cmd it works correctly.
![image](https://cloud.githubusercontent.com/assets/1297559/6637792/54b1d8ee-c987-11e4-993d-33971aadeb0c.png)
And here is when using the cmd:
![image](https://cloud.githubusercontent.com/assets/1297559/6637804/777570d4-c987-11e4-9c6e-36f30b78740c.png)

**Comment by stubailo** [comment]
Currently we don't support Git Bash, but we might in the future if enough people ask for it. As a workaround, you can run:

```
cmd //c meteor
```

**Comment by Dessix** [comment]
As you did mention "people asking for this feature", I'd like to put myself on that list- Command prompt handles so badly compared to even git bash. As for the workaround, I can at least call most meteor commands by placing this in a file named `meteor` in `%appdata%/../local/.meteor`:
```
#!/bin/bash
cmd //c meteor "$@"
```
... which passes bash arguments in, most of the time.

**Comment by stubailo** [comment]
Can you elaborate on "most of the time"? Is there a situation where that doesn't work?

**Comment by Dessix** [comment]
It cannot pass pipes into the executable- I assume there are other edge-cases involved with leaving a virtualized posix system this way.

**Comment by stubailo** [comment]
are there cases in which you need to pipe to `meteor`?

**Comment by Dessix** [comment]
As far as I've seen, no, but a solution that doesn't rely on `cmd` will allow for proper catching of Ctrl+C and Ctrl+D, for usage in (As an example I've noted) `meteor shell`.

**Comment by stubailo** [comment]
I think making Meteor work correctly in both cygwin and CMD/powershell will take some time - maybe in a future release.

**Comment by Dessix** [comment]
Alrighty.

**Comment by stubailo** [comment]
I will keep this open until then, though - it is definitely an important issue for a lot of people.

**Comment by bratanon** [comment]
+1 for git bash support.

**Comment by emilime** [comment]
+1 for git bash support.

**Comment by angele-smell** [comment]
+1 !!!

**Comment by dmartines** [comment]
+1

**Comment by ashe540** [comment]
+1

**Comment by Shekharrajak** [comment]
:+1:

**Comment by Appnostic** [comment]
+1

**Comment by HydraOrc** [comment]
+1 for git bash support.

**Comment by piton13** [comment]
+1 for git bash support

**Comment by sergeyeremeev** [comment]
+1

**Comment by jmlv** [comment]
+1

**Comment by batjko** [comment]
Out of interest, why are you guys using git bash in the first place?
I do all my git stuff in the standard command window and never felt any need to use the git bash.
Does it have any special niceties that `cmd` doesn't have?

**Comment by Shekharrajak** [comment]
@batjko  If there is no git bash , then there would be very less number of developers who use windows system.

**Comment by tomagladiator** [comment]
+1 
@batjko : right click on my folder and "Git Bash Here"

**Comment by QCmu** [comment]
I got here 'cause I can't run it on Git Bash either.
But I found that meteor works well on Git Shell. Maybe you guys could switch to it

**Comment by marcelsouza** [comment]
+1 for git bash support

**Comment by stubailo** [comment]
Going to continue this as a FR here: https://github.com/meteor/meteor/issues/4938

I'm closing this repo.
