### ISSUE TITLE
Cannot convert null to object

### ISSUE THREAD

**Issue by snowcxt** [meteor/windows-preview#99]
I downloaded 0.3.0 and run the project I created couple days ago. But got this error:
![image](https://cloud.githubusercontent.com/assets/1463415/6650519/c85c5476-c9d3-11e4-8ff5-e7d4ecd42c56.png)

**Comment by Slava** [comment]
Can you update by using the installer? We are aware of one of the previous versions being buggy on updates.

**Comment by snowcxt** [comment]
I download the installer from https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows. 

I just found that actually ostrio:neo4jreactivity causes this problem.

**Comment by 255kb** [comment]
Got exactly the same error here for any command on an existing project (meteor update, meteor --version, etc). Solve this by uninstalling and reinstalling Meteor. New projects creation was working fine.

**Comment by okosokolovo** [comment]
Got similar errors. Thanks to @255kb suggestion, solved by uninstalling and installing again.
